// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchCplaneFile maps one `<action-command> [args]` invocation to its typed
// CplaneFileService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchCplaneFile(ctx context.Context, c pb.CplaneFileServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "upload":
		dto := &pbaccess.ResourceCplaneFileActionUploadArgsDTO{}
		dto.FileName = args["file_name"]
		if v, ok := args["content"]; ok {
			b, err := os.ReadFile(v)
			if err != nil {
				return "", fmt.Errorf("arg content: %w", err)
			}
			dto.Content = b
		}
		resp, err := c.Upload(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "list":
		dto := &pbaccess.ResourceCplaneFileActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "delete":
		dto := &pbaccess.ResourceCplaneFileActionDeleteArgsDTO{}
		dto.FileName = args["file_name"]
		resp, err := c.Delete(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
