// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchDataplaneNode maps one `<action-command> [args]` invocation to its typed
// DataplaneNodeService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchDataplaneNode(ctx context.Context, c pb.DataplaneNodeServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "list":
		dto := &pbaccess.ResourceDataplaneNodeActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "get":
		dto := &pbaccess.ResourceDataplaneNodeActionGetArgsDTO{}
		dto.CommonName = args["common_name"]
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "watch":
		dto := &pbaccess.ResourceDataplaneNodeActionWatchArgsDTO{}
		stream, err := c.Watch(ctx, dto)
		if err != nil {
			return "", err
		}
		for {
			item, err := stream.Recv(ctx)
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				return "", err
			}
			b, err := json.MarshalIndent(item, "", "  ")
			if err != nil {
				return "", err
			}
			fmt.Println(string(b))
		}
		return "", nil
	case "start":
		dto := &pbaccess.ResourceDataplaneNodeActionStartArgsDTO{}
		dto.CommonName = args["common_name"]
		if v, ok := args["force"]; ok {
			if err := json.Unmarshal([]byte(v), &dto.Force); err != nil {
				return "", fmt.Errorf("arg force: %w", err)
			}
		}
		resp, err := c.Start(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "stop":
		dto := &pbaccess.ResourceDataplaneNodeActionStopArgsDTO{}
		dto.CommonName = args["common_name"]
		resp, err := c.Stop(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
