// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchDnsConfig maps one `<action-command> [args]` invocation to its typed
// DnsConfigService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchDnsConfig(ctx context.Context, c pb.DnsConfigServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "apply":
		dto := &pbaccess.ResourceDnsConfigActionApplyArgsDTO{}
		dto.Name = args["name"]
		if v, ok := args["port"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg port: %w", err)
			}
			dto.Port = uint32(n)
		}
		dto.Domain = args["domain"]
		dto.Mail = args["mail"]
		dto.ApiToken = args["api_token"]
		dto.ApiZoneId = args["api_zone_id"]
		resp, err := c.Apply(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "get":
		dto := &pbaccess.ResourceDnsConfigActionGetArgsDTO{}
		dto.Name = args["name"]
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "list":
		dto := &pbaccess.ResourceDnsConfigActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
