// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchDpFile maps one `<action-command> [args]` invocation to its typed
// DpFileService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchDpFile(ctx context.Context, c pb.DpFileServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "list":
		dto := &pbaccess.ResourceDpFileActionListArgsDTO{}
		dto.CommonName = args["common_name"]
		if v, ok := args["dir"]; ok {
			dto.Dir = v
		} else {
			dto.Dir = "."
		}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "send":
		dto := &pbaccess.ResourceDpFileActionSendArgsDTO{}
		dto.CommonName = args["common_name"]
		dto.CplaneFile = args["cplane_file"]
		dto.SaveAs = args["save_as"]
		resp, err := c.Send(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "delete":
		dto := &pbaccess.ResourceDpFileActionDeleteArgsDTO{}
		dto.CommonName = args["common_name"]
		dto.File = args["file"]
		resp, err := c.Delete(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
