// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchL4LbObject maps one `<action-command> [args]` invocation to its typed
// L4LbObjectService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchL4LbObject(ctx context.Context, c pb.L4LbObjectServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "apply":
		dto := &pbaccess.ResourceL4LbObjectActionApplyArgsDTO{}
		dto.Node = args["node"]
		dto.Object = args["object"]
		dto.CryptoObject = args["crypto_object"]
		dto.PinDir = args["pin_dir"]
		resp, err := c.Apply(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "get":
		dto := &pbaccess.ResourceL4LbObjectActionGetArgsDTO{}
		dto.Node = args["node"]
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "list":
		dto := &pbaccess.ResourceL4LbObjectActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "delete":
		dto := &pbaccess.ResourceL4LbObjectActionDeleteArgsDTO{}
		dto.Node = args["node"]
		resp, err := c.Delete(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
