// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchPopcacheConfig maps one `<action-command> [args]` invocation to its typed
// PopcacheConfigService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchPopcacheConfig(ctx context.Context, c pb.PopcacheConfigServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "apply":
		dto := &pbaccess.ResourcePopcacheConfigActionApplyArgsDTO{}
		dto.Name = args["name"]
		dto.Origin = args["origin"]
		if v, ok := args["http_port"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg http_port: %w", err)
			}
			dto.HttpPort = uint32(n)
		}
		if v, ok := args["https_port"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg https_port: %w", err)
			}
			dto.HttpsPort = uint32(n)
		}
		if v, ok := args["http3_port"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg http3_port: %w", err)
			}
			dto.Http3Port = uint32(n)
		}
		if v, ok := args["qlog_enabled"]; ok {
			if err := json.Unmarshal([]byte(v), &dto.QlogEnabled); err != nil {
				return "", fmt.Errorf("arg qlog_enabled: %w", err)
			}
		}
		if v, ok := args["wasm_compute_default_ms"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg wasm_compute_default_ms: %w", err)
			}
			dto.WasmComputeDefaultMs = uint32(n)
		}
		if v, ok := args["wasm_compute_max_ms"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg wasm_compute_max_ms: %w", err)
			}
			dto.WasmComputeMaxMs = uint32(n)
		}
		dto.CertPath = args["cert_path"]
		dto.KeyPath = args["key_path"]
		resp, err := c.Apply(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "get":
		dto := &pbaccess.ResourcePopcacheConfigActionGetArgsDTO{}
		dto.Name = args["name"]
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "list":
		dto := &pbaccess.ResourcePopcacheConfigActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
