// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchRouterConfig maps one `<action-command> [args]` invocation to its typed
// RouterConfigService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchRouterConfig(ctx context.Context, c pb.RouterConfigServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "apply":
		dto := &pbaccess.ResourceRouterConfigActionApplyArgsDTO{}
		dto.Node = args["node"]
		dto.Hostname = args["hostname"]
		dto.Username = args["username"]
		dto.Password = args["password"]
		resp, err := c.Apply(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "get":
		dto := &pbaccess.ResourceRouterConfigActionGetArgsDTO{}
		dto.Node = args["node"]
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "list":
		dto := &pbaccess.ResourceRouterConfigActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
