// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"time"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchStats maps one `<action-command> [args]` invocation to its typed
// StatsService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchStats(ctx context.Context, c pb.StatsServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "get":
		dto := &pbaccess.ResourceStatsActionGetArgsDTO{}
		if v, ok := args["common_name"]; ok {
			dto.CommonName = v
		} else {
			dto.CommonName = "*"
		}
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "watch":
		dto := &pbaccess.ResourceStatsActionWatchArgsDTO{}
		if v, ok := args["common_name"]; ok {
			dto.CommonName = v
		} else {
			dto.CommonName = "*"
		}
		if v, ok := args["interval"]; ok {
			d, err := time.ParseDuration(v)
			if err != nil {
				return "", fmt.Errorf("arg interval: %w", err)
			}
			dto.Interval = d
		}
		stream, err := c.Watch(ctx, dto)
		if err != nil {
			return "", err
		}
		for {
			item, err := stream.Recv(ctx)
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				return "", err
			}
			b, err := json.MarshalIndent(item, "", "  ")
			if err != nil {
				return "", err
			}
			fmt.Println(string(b))
		}
		return "", nil
	case "transfer-state":
		dto := &pbaccess.ResourceStatsActionTransferStateArgsDTO{}
		dto.CommonName = args["common_name"]
		resp, err := c.TransferState(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "scrape-metrics":
		dto := &pbaccess.ResourceStatsActionScrapeMetricsArgsDTO{}
		dto.CommonName = args["common_name"]
		resp, err := c.ScrapeMetrics(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
