// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchVip maps one `<action-command> [args]` invocation to its typed
// VipService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchVip(ctx context.Context, c pb.VipServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "apply":
		dto := &pbaccess.ResourceVipActionApplyArgsDTO{}
		dto.Vip = args["vip"]
		if v, ok := args["icmp_echo"]; ok {
			if err := json.Unmarshal([]byte(v), &dto.IcmpEcho); err != nil {
				return "", fmt.Errorf("arg icmp_echo: %w", err)
			}
		}
		resp, err := c.Apply(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "list":
		dto := &pbaccess.ResourceVipActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "delete":
		dto := &pbaccess.ResourceVipActionDeleteArgsDTO{}
		dto.Vip = args["vip"]
		resp, err := c.Delete(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "get":
		dto := &pbaccess.ResourceVipActionGetArgsDTO{}
		dto.Vip = args["vip"]
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
