// Code generated by kscale/access/generator. DO NOT EDIT.
package client

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// DispatchWasmModule maps one `<action-command> [args]` invocation to its typed
// WasmModuleService RPC: it binds the request DTO from args (keyed by the yaml arg
// names), calls the typed client, and returns the response as JSON ("" for
// no-response actions). action is the action's command_name.
func DispatchWasmModule(ctx context.Context, c pb.WasmModuleServiceClient, action string, args map[string]string) (string, error) {
	switch action {
	case "apply":
		dto := &pbaccess.ResourceWasmModuleActionApplyArgsDTO{}
		if v, ok := args["module_id"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg module_id: %w", err)
			}
			dto.ModuleId = uint32(n)
		}
		dto.FilePath = args["file_path"]
		dto.Method = args["method"]
		dto.Path = args["path"]
		dto.MatchType = args["match_type"]
		if v, ok := args["allowed_hosts"]; ok {
			l, err := parseStringList(v)
			if err != nil {
				return "", fmt.Errorf("arg allowed_hosts: %w", err)
			}
			dto.AllowedHosts = l
		}
		if v, ok := args["compute_budget_ms"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg compute_budget_ms: %w", err)
			}
			dto.ComputeBudgetMs = uint32(n)
		}
		resp, err := c.Apply(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "list":
		dto := &pbaccess.ResourceWasmModuleActionListArgsDTO{}
		resp, err := c.List(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "delete":
		dto := &pbaccess.ResourceWasmModuleActionDeleteArgsDTO{}
		if v, ok := args["module_id"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg module_id: %w", err)
			}
			dto.ModuleId = uint32(n)
		}
		resp, err := c.Delete(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "get":
		dto := &pbaccess.ResourceWasmModuleActionGetArgsDTO{}
		if v, ok := args["module_id"]; ok {
			n, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return "", fmt.Errorf("arg module_id: %w", err)
			}
			dto.ModuleId = uint32(n)
		}
		resp, err := c.Get(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	case "diff":
		dto := &pbaccess.ResourceWasmModuleActionDiffArgsDTO{}
		resp, err := c.Diff(ctx, dto)
		if err != nil {
			return "", err
		}
		b, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return "", err
		}
		return string(b), nil
	default:
		return "", fmt.Errorf("unknown action %q", action)
	}
}
