// Code generated by kscale/access/generator. DO NOT EDIT.
package nodefile

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// Handlers is the generated node_file desired-state store.
type Handlers struct {
	pb.UnimplementedNodeFileServiceServer
	mu       sync.Mutex
	store    map[string]*pbaccess.ResourceNodeFileActionGetResponseDTO
	onChange []func()
	// ConfirmPush, set by the control plane, returns the resource's current per-node
	// reconcile push error (nil if all good); called right after notify() so apply
	// reports a failed push synchronously instead of a silent OK. Optional.
	ConfirmPush func() error
}

var _ pb.NodeFileServiceServer = (*Handlers)(nil)

// New returns an empty node_file store.
func New() *Handlers {
	return &Handlers{store: map[string]*pbaccess.ResourceNodeFileActionGetResponseDTO{}}
}

// Apply idempotently upserts one node_file by Name.
func (h *Handlers) Apply(ctx context.Context, req *pbaccess.ResourceNodeFileActionApplyArgsDTO) (*pbaccess.ResourceNodeFileActionApplyResponseDTO, error) {
	h.mu.Lock()
	obj := &pbaccess.ResourceNodeFileActionGetResponseDTO{
		Name:       req.Name,
		Node:       req.Node,
		SaveAs:     req.SaveAs,
		CplaneFile: req.CplaneFile,
	}
	h.store[req.Name] = obj
	resp := &pbaccess.ResourceNodeFileActionApplyResponseDTO{
		Name:       req.Name,
		Node:       req.Node,
		SaveAs:     req.SaveAs,
		CplaneFile: req.CplaneFile,
	}
	h.mu.Unlock()
	h.notify()
	if h.ConfirmPush != nil {
		return resp, h.ConfirmPush()
	}
	return resp, nil
}

// Get returns one node_file by Name.
func (h *Handlers) Get(ctx context.Context, req *pbaccess.ResourceNodeFileActionGetArgsDTO) (*pbaccess.ResourceNodeFileActionGetResponseDTO, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	obj, ok := h.store[req.Name]
	if !ok {
		return nil, fmt.Errorf("node_file %q not found", req.Name)
	}
	return obj, nil
}

// List returns every node_file (sorted by key for determinism).
func (h *Handlers) List(ctx context.Context, _ *pbaccess.ResourceNodeFileActionListArgsDTO) (*pbaccess.ResourceNodeFileActionListResponseDTO, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	keys := make([]string, 0, len(h.store))
	for k := range h.store {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	items := make([]*pbaccess.ResourceNodeFileActionGetResponseDTO, 0, len(keys))
	for _, k := range keys {
		items = append(items, h.store[k])
	}
	return &pbaccess.ResourceNodeFileActionListResponseDTO{Items: items}, nil
}

// Delete removes one entry by Name.
func (h *Handlers) Delete(ctx context.Context, req *pbaccess.ResourceNodeFileActionDeleteArgsDTO) (*pbaccess.ResourceNodeFileActionDeleteResponseDTO, error) {
	h.mu.Lock()
	delete(h.store, req.Name)
	h.mu.Unlock()
	h.notify()
	return &pbaccess.ResourceNodeFileActionDeleteResponseDTO{Name: req.Name}, nil
}

// OnChange registers a callback fired on every desired-state mutation — the
// reconcile loop subscribes to re-push to the dataplane.
func (h *Handlers) OnChange(f func()) {
	h.mu.Lock()
	h.onChange = append(h.onChange, f)
	h.mu.Unlock()
}

func (h *Handlers) notify() {
	h.mu.Lock()
	cbs := append([]func(){}, h.onChange...)
	h.mu.Unlock()
	for _, f := range cbs {
		f()
	}
}

// Desired returns the full desired set (WITH sensitive fields) for the reconcile
// loop to push to the dataplane.
func (h *Handlers) Desired() []*pbaccess.ResourceNodeFileActionGetResponseDTO {
	h.mu.Lock()
	defer h.mu.Unlock()
	out := make([]*pbaccess.ResourceNodeFileActionGetResponseDTO, 0, len(h.store))
	for _, c := range h.store {
		out = append(out, c)
	}
	return out
}

// Snapshot/Restore persist the desired state (desiredstate.Store). The full map
// (including sensitive fields) is serialized; the desiredstate file is encrypted.
func (h *Handlers) Snapshot() (json.RawMessage, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	return json.Marshal(h.store)
}

func (h *Handlers) Restore(raw json.RawMessage) error {
	var m map[string]*pbaccess.ResourceNodeFileActionGetResponseDTO
	if err := json.Unmarshal(raw, &m); err != nil {
		return err
	}
	if m == nil {
		m = map[string]*pbaccess.ResourceNodeFileActionGetResponseDTO{}
	}
	h.mu.Lock()
	defer h.mu.Unlock()
	h.store = m
	return nil
}
