// Code generated by ksdk/access/generator. DO NOT EDIT.

package predefined

import (
	"github.com/on-keyday/kscale/access"
	"github.com/on-keyday/kscale/access/policy"
)

func Resources() []access.ResourceTemplate {
	return []access.ResourceTemplate{
		access.NewResourceTemplate("user_hierarchy_authority", nil, []access.Attribute{}, []access.Action{
			ResourceUserHierarchyAuthorityActionCreate,
			ResourceUserHierarchyAuthorityActionGet,
			ResourceUserHierarchyAuthorityActionList,
			ResourceUserHierarchyAuthorityActionDelete,
			ResourceUserHierarchyAuthorityActionWatch,
			ResourceUserHierarchyAuthorityActionApply,
		}),
		access.NewResourceTemplate("certificate", nil, []access.Attribute{}, []access.Action{
			ResourceCertificateActionList,
			ResourceCertificateActionGet,
			ResourceCertificateActionDelete,
			ResourceCertificateActionGarbageCollect,
		}),
		access.NewResourceTemplate("session_management", nil, []access.Attribute{}, []access.Action{
			ResourceSessionManagementActionListSessions,
			ResourceSessionManagementActionTerminateSession,
			ResourceSessionManagementActionSelfInfo,
		}),
		access.NewResourceTemplate("logs", nil, []access.Attribute{}, []access.Action{
			ResourceLogsActionStream,
			ResourceLogsActionTail,
			ResourceLogsActionSetLevel,
			ResourceLogsActionGetLevel,
		}),
		access.NewResourceTemplate("monitor_chat", nil, []access.Attribute{}, []access.Action{
			ResourceMonitorChatActionSend,
			ResourceMonitorChatActionResume,
		}),
		access.NewResourceTemplate("dp_operations", nil, []access.Attribute{}, []access.Action{
			ResourceDpOperationsActionDownloadFile,
			ResourceDpOperationsActionRealtimeStats,
			ResourceDpOperationsActionMessage,
			ResourceDpOperationsActionReportStatus,
		}),
		access.NewResourceTemplate("remote_shell", nil, []access.Attribute{}, []access.Action{
			ResourceRemoteShellActionDpExecuteCommand,
			ResourceRemoteShellActionCplaneExecuteCommand,
		}),
		access.NewResourceTemplate("http_proxy", nil, []access.Attribute{}, []access.Action{
			ResourceHttpProxyActionConnectToTarget,
			ResourceHttpProxyActionRequestViaProxy,
		}),
		access.NewResourceTemplate("acme", nil, []access.Attribute{}, []access.Action{
			ResourceAcmeActionObtain,
			ResourceAcmeActionList,
			ResourceAcmeActionGetCert,
			ResourceAcmeActionDeleteCert,
			ResourceAcmeActionDeleteAccount,
		}),
		access.NewResourceTemplate("wasm_module", nil, []access.Attribute{}, []access.Action{
			ResourceWasmModuleActionApply,
			ResourceWasmModuleActionList,
			ResourceWasmModuleActionDelete,
			ResourceWasmModuleActionGet,
			ResourceWasmModuleActionDiff,
		}),
		access.NewResourceTemplate("popcache_config", nil, []access.Attribute{}, []access.Action{
			ResourcePopcacheConfigActionApply,
			ResourcePopcacheConfigActionGet,
			ResourcePopcacheConfigActionList,
		}),
		access.NewResourceTemplate("open_port", nil, []access.Attribute{}, []access.Action{
			ResourceOpenPortActionApply,
			ResourceOpenPortActionList,
			ResourceOpenPortActionDelete,
			ResourceOpenPortActionGet,
			ResourceOpenPortActionDiff,
		}),
		access.NewResourceTemplate("node_file", nil, []access.Attribute{}, []access.Action{
			ResourceNodeFileActionApply,
			ResourceNodeFileActionList,
			ResourceNodeFileActionDelete,
			ResourceNodeFileActionGet,
		}),
		access.NewResourceTemplate("container", nil, []access.Attribute{}, []access.Action{
			ResourceContainerActionApply,
			ResourceContainerActionGet,
			ResourceContainerActionList,
			ResourceContainerActionDelete,
			ResourceContainerActionDiff,
		}),
		access.NewResourceTemplate("l4lb_object", nil, []access.Attribute{}, []access.Action{
			ResourceL4LbObjectActionApply,
			ResourceL4LbObjectActionGet,
			ResourceL4LbObjectActionList,
			ResourceL4LbObjectActionDelete,
		}),
		access.NewResourceTemplate("bootstrap_token", nil, []access.Attribute{}, []access.Action{
			ResourceBootstrapTokenActionIssue,
			ResourceBootstrapTokenActionRevoke,
		}),
		access.NewResourceTemplate("expected_node", nil, []access.Attribute{}, []access.Action{
			ResourceExpectedNodeActionApply,
			ResourceExpectedNodeActionList,
			ResourceExpectedNodeActionDelete,
			ResourceExpectedNodeActionGet,
		}),
		access.NewResourceTemplate("vip", nil, []access.Attribute{}, []access.Action{
			ResourceVipActionApply,
			ResourceVipActionList,
			ResourceVipActionDelete,
			ResourceVipActionGet,
		}),
		access.NewResourceTemplate("interface", nil, []access.Attribute{}, []access.Action{
			ResourceInterfaceActionApply,
			ResourceInterfaceActionList,
			ResourceInterfaceActionDelete,
			ResourceInterfaceActionGet,
		}),
		access.NewResourceTemplate("router_config", nil, []access.Attribute{}, []access.Action{
			ResourceRouterConfigActionApply,
			ResourceRouterConfigActionGet,
			ResourceRouterConfigActionList,
		}),
		access.NewResourceTemplate("dns_config", nil, []access.Attribute{}, []access.Action{
			ResourceDnsConfigActionApply,
			ResourceDnsConfigActionGet,
			ResourceDnsConfigActionList,
		}),
		access.NewResourceTemplate("mtu", nil, []access.Attribute{}, []access.Action{
			ResourceMtuActionApply,
			ResourceMtuActionList,
			ResourceMtuActionDelete,
			ResourceMtuActionGet,
		}),
		access.NewResourceTemplate("secret", nil, []access.Attribute{}, []access.Action{
			ResourceSecretActionApply,
			ResourceSecretActionList,
			ResourceSecretActionDelete,
			ResourceSecretActionGet,
		}),
		access.NewResourceTemplate("dataplane_node", nil, []access.Attribute{}, []access.Action{
			ResourceDataplaneNodeActionList,
			ResourceDataplaneNodeActionGet,
			ResourceDataplaneNodeActionWatch,
			ResourceDataplaneNodeActionStart,
			ResourceDataplaneNodeActionStop,
		}),
		access.NewResourceTemplate("connection", nil, []access.Attribute{}, []access.Action{
			ResourceConnectionActionList,
			ResourceConnectionActionGet,
		}),
		access.NewResourceTemplate("alert", nil, []access.Attribute{}, []access.Action{
			ResourceAlertActionList,
			ResourceAlertActionGet,
		}),
		access.NewResourceTemplate("cplane_file", nil, []access.Attribute{}, []access.Action{
			ResourceCplaneFileActionUpload,
			ResourceCplaneFileActionList,
			ResourceCplaneFileActionDelete,
		}),
		access.NewResourceTemplate("dp_file", nil, []access.Attribute{}, []access.Action{
			ResourceDpFileActionList,
			ResourceDpFileActionSend,
			ResourceDpFileActionDelete,
		}),
		access.NewResourceTemplate("stats", nil, []access.Attribute{}, []access.Action{
			ResourceStatsActionGet,
			ResourceStatsActionWatch,
			ResourceStatsActionTransferState,
			ResourceStatsActionScrapeMetrics,
		}),
	}
}

// DataplaneTypes are the distinct reconcile dp_type values declared in
// resource.yaml (excluding "*"). A new dp_type appears here automatically
// when a resource declares reconcile.dp_type.
func DataplaneTypes() []string {
	return []string{"dns", "l4lb", "popcache", "router", "workload"}
}

// IsDataplaneType reports whether app is one of the generated dataplane dp_types.
func IsDataplaneType(app string) bool {
	switch app {
	case "dns", "l4lb", "popcache", "router", "workload":
		return true
	}
	return false
}

const ResourceUserHierarchyAuthority = "user_hierarchy_authority"

var ResourceUserHierarchyAuthorityActionCreate = access.NewAction("create", []string{"authority_name"})

const ResourceUserHierarchyAuthorityActionCreateArgAuthorityName = "authority_name"

var ResourceUserHierarchyAuthorityActionGet = access.NewAction("get", []string{"authority_name"})

const ResourceUserHierarchyAuthorityActionGetArgAuthorityName = "authority_name"

var ResourceUserHierarchyAuthorityActionList = access.NewAction("list", []string{})
var ResourceUserHierarchyAuthorityActionDelete = access.NewAction("delete", []string{"authority_name"})

const ResourceUserHierarchyAuthorityActionDeleteArgAuthorityName = "authority_name"

var ResourceUserHierarchyAuthorityActionWatch = access.NewAction("watch", []string{})
var ResourceUserHierarchyAuthorityActionApply = access.NewAction("apply", []string{"authority_name"})

const ResourceUserHierarchyAuthorityActionApplyArgAuthorityName = "authority_name"

const ResourceCertificate = "certificate"

var ResourceCertificateActionList = access.NewAction("list", []string{})
var ResourceCertificateActionGet = access.NewAction("get", []string{"common_name"})

const ResourceCertificateActionGetArgCommonName = "common_name"

var ResourceCertificateActionDelete = access.NewAction("delete", []string{"common_name"})

const ResourceCertificateActionDeleteArgCommonName = "common_name"

var ResourceCertificateActionGarbageCollect = access.NewAction("garbage_collect", []string{})

const ResourceSessionManagement = "session_management"

var ResourceSessionManagementActionListSessions = access.NewAction("list_sessions", []string{})
var ResourceSessionManagementActionTerminateSession = access.NewAction("terminate_session", []string{"conn_id", "session_kind"})

const ResourceSessionManagementActionTerminateSessionArgConnId = "conn_id"
const ResourceSessionManagementActionTerminateSessionArgSessionKind = "session_kind"

var ResourceSessionManagementActionSelfInfo = access.NewAction("self_info", []string{})

const ResourceLogs = "logs"

var ResourceLogsActionStream = access.NewAction("stream", []string{"common_name"})

const ResourceLogsActionStreamArgCommonName = "common_name"

var ResourceLogsActionTail = access.NewAction("tail", []string{"common_name", "level", "contains", "lines"})

const ResourceLogsActionTailArgCommonName = "common_name"
const ResourceLogsActionTailArgLevel = "level"
const ResourceLogsActionTailArgContains = "contains"
const ResourceLogsActionTailArgLines = "lines"

var ResourceLogsActionSetLevel = access.NewAction("set_level", []string{"node", "level"})

const ResourceLogsActionSetLevelArgNode = "node"
const ResourceLogsActionSetLevelArgLevel = "level"

var ResourceLogsActionGetLevel = access.NewAction("get_level", []string{"node"})

const ResourceLogsActionGetLevelArgNode = "node"

const ResourceMonitorChat = "monitor_chat"

var ResourceMonitorChatActionSend = access.NewAction("send", []string{"agent", "session_id", "message"})

const ResourceMonitorChatActionSendArgAgent = "agent"
const ResourceMonitorChatActionSendArgSessionId = "session_id"
const ResourceMonitorChatActionSendArgMessage = "message"

var ResourceMonitorChatActionResume = access.NewAction("resume", []string{"agent", "session_id", "tool", "result", "denied"})

const ResourceMonitorChatActionResumeArgAgent = "agent"
const ResourceMonitorChatActionResumeArgSessionId = "session_id"
const ResourceMonitorChatActionResumeArgTool = "tool"
const ResourceMonitorChatActionResumeArgResult = "result"
const ResourceMonitorChatActionResumeArgDenied = "denied"

const ResourceDpOperations = "dp_operations"

var ResourceDpOperationsActionDownloadFile = access.NewAction("download_file", []string{"file_name", "file_seq"})

const ResourceDpOperationsActionDownloadFileArgFileName = "file_name"
const ResourceDpOperationsActionDownloadFileArgFileSeq = "file_seq"

var ResourceDpOperationsActionRealtimeStats = access.NewAction("realtime_stats", []string{"enable", "dp_type", "address", "interval", "filter"})

const ResourceDpOperationsActionRealtimeStatsArgEnable = "enable"
const ResourceDpOperationsActionRealtimeStatsArgDpType = "dp_type"
const ResourceDpOperationsActionRealtimeStatsArgAddress = "address"
const ResourceDpOperationsActionRealtimeStatsArgInterval = "interval"
const ResourceDpOperationsActionRealtimeStatsArgFilter = "filter"

var ResourceDpOperationsActionMessage = access.NewAction("message", []string{"message"})

const ResourceDpOperationsActionMessageArgMessage = "message"

var ResourceDpOperationsActionReportStatus = access.NewAction("report_status", []string{})

const ResourceRemoteShell = "remote_shell"

var ResourceRemoteShellActionDpExecuteCommand = access.NewAction("dp_execute_command", []string{"dp_type", "address", "command", "args", "pty"})

const ResourceRemoteShellActionDpExecuteCommandArgDpType = "dp_type"
const ResourceRemoteShellActionDpExecuteCommandArgAddress = "address"
const ResourceRemoteShellActionDpExecuteCommandArgCommand = "command"
const ResourceRemoteShellActionDpExecuteCommandArgArgs = "args"
const ResourceRemoteShellActionDpExecuteCommandArgPty = "pty"

var ResourceRemoteShellActionCplaneExecuteCommand = access.NewAction("cplane_execute_command", []string{"command", "args", "pty"})

const ResourceRemoteShellActionCplaneExecuteCommandArgCommand = "command"
const ResourceRemoteShellActionCplaneExecuteCommandArgArgs = "args"
const ResourceRemoteShellActionCplaneExecuteCommandArgPty = "pty"

const ResourceHttpProxy = "http_proxy"

var ResourceHttpProxyActionConnectToTarget = access.NewAction("connect_to_target", []string{"target"})

const ResourceHttpProxyActionConnectToTargetArgTarget = "target"

var ResourceHttpProxyActionRequestViaProxy = access.NewAction("request_via_proxy", []string{"proxy_dp_type", "proxy_address", "host", "method", "url", "headers"})

const ResourceHttpProxyActionRequestViaProxyArgProxyDpType = "proxy_dp_type"
const ResourceHttpProxyActionRequestViaProxyArgProxyAddress = "proxy_address"
const ResourceHttpProxyActionRequestViaProxyArgHost = "host"
const ResourceHttpProxyActionRequestViaProxyArgMethod = "method"
const ResourceHttpProxyActionRequestViaProxyArgUrl = "url"
const ResourceHttpProxyActionRequestViaProxyArgHeaders = "headers"

const ResourceAcme = "acme"

var ResourceAcmeActionObtain = access.NewAction("obtain", []string{"domain", "email", "ca_dir_url"})

const ResourceAcmeActionObtainArgDomain = "domain"
const ResourceAcmeActionObtainArgEmail = "email"
const ResourceAcmeActionObtainArgCaDirUrl = "ca_dir_url"

var ResourceAcmeActionList = access.NewAction("list", []string{"ca_dir_url"})

const ResourceAcmeActionListArgCaDirUrl = "ca_dir_url"

var ResourceAcmeActionGetCert = access.NewAction("get-cert", []string{"domain", "ca_dir_url"})

const ResourceAcmeActionGetCertArgDomain = "domain"
const ResourceAcmeActionGetCertArgCaDirUrl = "ca_dir_url"

var ResourceAcmeActionDeleteCert = access.NewAction("delete-cert", []string{"domain", "ca_dir_url"})

const ResourceAcmeActionDeleteCertArgDomain = "domain"
const ResourceAcmeActionDeleteCertArgCaDirUrl = "ca_dir_url"

var ResourceAcmeActionDeleteAccount = access.NewAction("delete-account", []string{"ca_dir_url"})

const ResourceAcmeActionDeleteAccountArgCaDirUrl = "ca_dir_url"

const ResourceWasmModule = "wasm_module"

var ResourceWasmModuleActionApply = access.NewAction("apply", []string{"module_id", "file_path", "method", "path", "match_type", "allowed_hosts", "compute_budget_ms"})

const ResourceWasmModuleActionApplyArgModuleId = "module_id"
const ResourceWasmModuleActionApplyArgFilePath = "file_path"
const ResourceWasmModuleActionApplyArgMethod = "method"
const ResourceWasmModuleActionApplyArgPath = "path"
const ResourceWasmModuleActionApplyArgMatchType = "match_type"
const ResourceWasmModuleActionApplyArgAllowedHosts = "allowed_hosts"
const ResourceWasmModuleActionApplyArgComputeBudgetMs = "compute_budget_ms"

var ResourceWasmModuleActionList = access.NewAction("list", []string{})
var ResourceWasmModuleActionDelete = access.NewAction("delete", []string{"module_id"})

const ResourceWasmModuleActionDeleteArgModuleId = "module_id"

var ResourceWasmModuleActionGet = access.NewAction("get", []string{"module_id"})

const ResourceWasmModuleActionGetArgModuleId = "module_id"

var ResourceWasmModuleActionDiff = access.NewAction("diff", []string{})

const ResourcePopcacheConfig = "popcache_config"

var ResourcePopcacheConfigActionApply = access.NewAction("apply", []string{"name", "origin", "http_port", "https_port", "http3_port", "qlog_enabled", "wasm_compute_default_ms", "wasm_compute_max_ms", "cert_path", "key_path"})

const ResourcePopcacheConfigActionApplyArgName = "name"
const ResourcePopcacheConfigActionApplyArgOrigin = "origin"
const ResourcePopcacheConfigActionApplyArgHttpPort = "http_port"
const ResourcePopcacheConfigActionApplyArgHttpsPort = "https_port"
const ResourcePopcacheConfigActionApplyArgHttp3Port = "http3_port"
const ResourcePopcacheConfigActionApplyArgQlogEnabled = "qlog_enabled"
const ResourcePopcacheConfigActionApplyArgWasmComputeDefaultMs = "wasm_compute_default_ms"
const ResourcePopcacheConfigActionApplyArgWasmComputeMaxMs = "wasm_compute_max_ms"
const ResourcePopcacheConfigActionApplyArgCertPath = "cert_path"
const ResourcePopcacheConfigActionApplyArgKeyPath = "key_path"

var ResourcePopcacheConfigActionGet = access.NewAction("get", []string{"name"})

const ResourcePopcacheConfigActionGetArgName = "name"

var ResourcePopcacheConfigActionList = access.NewAction("list", []string{})

const ResourceOpenPort = "open_port"

var ResourceOpenPortActionApply = access.NewAction("apply", []string{"acl_name", "ports"})

const ResourceOpenPortActionApplyArgAclName = "acl_name"
const ResourceOpenPortActionApplyArgPorts = "ports"

var ResourceOpenPortActionList = access.NewAction("list", []string{})
var ResourceOpenPortActionDelete = access.NewAction("delete", []string{"acl_name"})

const ResourceOpenPortActionDeleteArgAclName = "acl_name"

var ResourceOpenPortActionGet = access.NewAction("get", []string{"acl_name"})

const ResourceOpenPortActionGetArgAclName = "acl_name"

var ResourceOpenPortActionDiff = access.NewAction("diff", []string{})

const ResourceNodeFile = "node_file"

var ResourceNodeFileActionApply = access.NewAction("apply", []string{"name", "node", "save_as", "cplane_file"})

const ResourceNodeFileActionApplyArgName = "name"
const ResourceNodeFileActionApplyArgNode = "node"
const ResourceNodeFileActionApplyArgSaveAs = "save_as"
const ResourceNodeFileActionApplyArgCplaneFile = "cplane_file"

var ResourceNodeFileActionList = access.NewAction("list", []string{})
var ResourceNodeFileActionDelete = access.NewAction("delete", []string{"name"})

const ResourceNodeFileActionDeleteArgName = "name"

var ResourceNodeFileActionGet = access.NewAction("get", []string{"name"})

const ResourceNodeFileActionGetArgName = "name"

const ResourceContainer = "container"

var ResourceContainerActionApply = access.NewAction("apply", []string{"name", "node", "image", "command", "args", "env", "mounts", "restart", "network", "ports"})

const ResourceContainerActionApplyArgName = "name"
const ResourceContainerActionApplyArgNode = "node"
const ResourceContainerActionApplyArgImage = "image"
const ResourceContainerActionApplyArgCommand = "command"
const ResourceContainerActionApplyArgArgs = "args"
const ResourceContainerActionApplyArgEnv = "env"
const ResourceContainerActionApplyArgMounts = "mounts"
const ResourceContainerActionApplyArgRestart = "restart"
const ResourceContainerActionApplyArgNetwork = "network"
const ResourceContainerActionApplyArgPorts = "ports"

var ResourceContainerActionGet = access.NewAction("get", []string{"name"})

const ResourceContainerActionGetArgName = "name"

var ResourceContainerActionList = access.NewAction("list", []string{})
var ResourceContainerActionDelete = access.NewAction("delete", []string{"name"})

const ResourceContainerActionDeleteArgName = "name"

var ResourceContainerActionDiff = access.NewAction("diff", []string{})

const ResourceL4LbObject = "l4lb_object"

var ResourceL4LbObjectActionApply = access.NewAction("apply", []string{"node", "object", "crypto_object", "pin_dir"})

const ResourceL4LbObjectActionApplyArgNode = "node"
const ResourceL4LbObjectActionApplyArgObject = "object"
const ResourceL4LbObjectActionApplyArgCryptoObject = "crypto_object"
const ResourceL4LbObjectActionApplyArgPinDir = "pin_dir"

var ResourceL4LbObjectActionGet = access.NewAction("get", []string{"node"})

const ResourceL4LbObjectActionGetArgNode = "node"

var ResourceL4LbObjectActionList = access.NewAction("list", []string{})
var ResourceL4LbObjectActionDelete = access.NewAction("delete", []string{"node"})

const ResourceL4LbObjectActionDeleteArgNode = "node"

const ResourceBootstrapToken = "bootstrap_token"

var ResourceBootstrapTokenActionIssue = access.NewAction("issue", []string{"duration", "appName", "domain", "expires_period"})

const ResourceBootstrapTokenActionIssueArgDuration = "duration"
const ResourceBootstrapTokenActionIssueArgAppName = "appName"
const ResourceBootstrapTokenActionIssueArgDomain = "domain"
const ResourceBootstrapTokenActionIssueArgExpiresPeriod = "expires_period"

var ResourceBootstrapTokenActionRevoke = access.NewAction("revoke", []string{"token"})

const ResourceBootstrapTokenActionRevokeArgToken = "token"

const ResourceExpectedNode = "expected_node"

var ResourceExpectedNodeActionApply = access.NewAction("apply", []string{"common_name", "dp_type"})

const ResourceExpectedNodeActionApplyArgCommonName = "common_name"
const ResourceExpectedNodeActionApplyArgDpType = "dp_type"

var ResourceExpectedNodeActionList = access.NewAction("list", []string{})
var ResourceExpectedNodeActionDelete = access.NewAction("delete", []string{"common_name"})

const ResourceExpectedNodeActionDeleteArgCommonName = "common_name"

var ResourceExpectedNodeActionGet = access.NewAction("get", []string{"common_name"})

const ResourceExpectedNodeActionGetArgCommonName = "common_name"

const ResourceVip = "vip"

var ResourceVipActionApply = access.NewAction("apply", []string{"vip", "icmp_echo"})

const ResourceVipActionApplyArgVip = "vip"
const ResourceVipActionApplyArgIcmpEcho = "icmp_echo"

var ResourceVipActionList = access.NewAction("list", []string{})
var ResourceVipActionDelete = access.NewAction("delete", []string{"vip"})

const ResourceVipActionDeleteArgVip = "vip"

var ResourceVipActionGet = access.NewAction("get", []string{"vip"})

const ResourceVipActionGetArgVip = "vip"

const ResourceInterface = "interface"

var ResourceInterfaceActionApply = access.NewAction("apply", []string{"node", "interface"})

const ResourceInterfaceActionApplyArgNode = "node"
const ResourceInterfaceActionApplyArgInterface = "interface"

var ResourceInterfaceActionList = access.NewAction("list", []string{})
var ResourceInterfaceActionDelete = access.NewAction("delete", []string{"node"})

const ResourceInterfaceActionDeleteArgNode = "node"

var ResourceInterfaceActionGet = access.NewAction("get", []string{"node"})

const ResourceInterfaceActionGetArgNode = "node"

const ResourceRouterConfig = "router_config"

var ResourceRouterConfigActionApply = access.NewAction("apply", []string{"node", "hostname", "username", "password"})

const ResourceRouterConfigActionApplyArgNode = "node"
const ResourceRouterConfigActionApplyArgHostname = "hostname"
const ResourceRouterConfigActionApplyArgUsername = "username"
const ResourceRouterConfigActionApplyArgPassword = "password"

var ResourceRouterConfigActionGet = access.NewAction("get", []string{"node"})

const ResourceRouterConfigActionGetArgNode = "node"

var ResourceRouterConfigActionList = access.NewAction("list", []string{})

const ResourceDnsConfig = "dns_config"

var ResourceDnsConfigActionApply = access.NewAction("apply", []string{"name", "port", "domain", "mail", "api_token", "api_zone_id"})

const ResourceDnsConfigActionApplyArgName = "name"
const ResourceDnsConfigActionApplyArgPort = "port"
const ResourceDnsConfigActionApplyArgDomain = "domain"
const ResourceDnsConfigActionApplyArgMail = "mail"
const ResourceDnsConfigActionApplyArgApiToken = "api_token"
const ResourceDnsConfigActionApplyArgApiZoneId = "api_zone_id"

var ResourceDnsConfigActionGet = access.NewAction("get", []string{"name"})

const ResourceDnsConfigActionGetArgName = "name"

var ResourceDnsConfigActionList = access.NewAction("list", []string{})

const ResourceMtu = "mtu"

var ResourceMtuActionApply = access.NewAction("apply", []string{"node", "mtu"})

const ResourceMtuActionApplyArgNode = "node"
const ResourceMtuActionApplyArgMtu = "mtu"

var ResourceMtuActionList = access.NewAction("list", []string{})
var ResourceMtuActionDelete = access.NewAction("delete", []string{"node"})

const ResourceMtuActionDeleteArgNode = "node"

var ResourceMtuActionGet = access.NewAction("get", []string{"node"})

const ResourceMtuActionGetArgNode = "node"

const ResourceSecret = "secret"

var ResourceSecretActionApply = access.NewAction("apply", []string{"name", "length"})

const ResourceSecretActionApplyArgName = "name"
const ResourceSecretActionApplyArgLength = "length"

var ResourceSecretActionList = access.NewAction("list", []string{})
var ResourceSecretActionDelete = access.NewAction("delete", []string{"name"})

const ResourceSecretActionDeleteArgName = "name"

var ResourceSecretActionGet = access.NewAction("get", []string{"name"})

const ResourceSecretActionGetArgName = "name"

const ResourceDataplaneNode = "dataplane_node"

var ResourceDataplaneNodeActionList = access.NewAction("list", []string{})
var ResourceDataplaneNodeActionGet = access.NewAction("get", []string{"common_name"})

const ResourceDataplaneNodeActionGetArgCommonName = "common_name"

var ResourceDataplaneNodeActionWatch = access.NewAction("watch", []string{})
var ResourceDataplaneNodeActionStart = access.NewAction("start", []string{"common_name", "force"})

const ResourceDataplaneNodeActionStartArgCommonName = "common_name"
const ResourceDataplaneNodeActionStartArgForce = "force"

var ResourceDataplaneNodeActionStop = access.NewAction("stop", []string{"common_name"})

const ResourceDataplaneNodeActionStopArgCommonName = "common_name"

const ResourceConnection = "connection"

var ResourceConnectionActionList = access.NewAction("list", []string{})
var ResourceConnectionActionGet = access.NewAction("get", []string{"connection_id"})

const ResourceConnectionActionGetArgConnectionId = "connection_id"

const ResourceAlert = "alert"

var ResourceAlertActionList = access.NewAction("list", []string{})
var ResourceAlertActionGet = access.NewAction("get", []string{"node"})

const ResourceAlertActionGetArgNode = "node"

const ResourceCplaneFile = "cplane_file"

var ResourceCplaneFileActionUpload = access.NewAction("upload", []string{"file_name", "content"})

const ResourceCplaneFileActionUploadArgFileName = "file_name"
const ResourceCplaneFileActionUploadArgContent = "content"

var ResourceCplaneFileActionList = access.NewAction("list", []string{})
var ResourceCplaneFileActionDelete = access.NewAction("delete", []string{"file_name"})

const ResourceCplaneFileActionDeleteArgFileName = "file_name"

const ResourceDpFile = "dp_file"

var ResourceDpFileActionList = access.NewAction("list", []string{"common_name", "dir"})

const ResourceDpFileActionListArgCommonName = "common_name"
const ResourceDpFileActionListArgDir = "dir"

var ResourceDpFileActionSend = access.NewAction("send", []string{"common_name", "cplane_file", "save_as"})

const ResourceDpFileActionSendArgCommonName = "common_name"
const ResourceDpFileActionSendArgCplaneFile = "cplane_file"
const ResourceDpFileActionSendArgSaveAs = "save_as"

var ResourceDpFileActionDelete = access.NewAction("delete", []string{"common_name", "file"})

const ResourceDpFileActionDeleteArgCommonName = "common_name"
const ResourceDpFileActionDeleteArgFile = "file"

const ResourceStats = "stats"

var ResourceStatsActionGet = access.NewAction("get", []string{"common_name"})

const ResourceStatsActionGetArgCommonName = "common_name"

var ResourceStatsActionWatch = access.NewAction("watch", []string{"common_name", "interval"})

const ResourceStatsActionWatchArgCommonName = "common_name"
const ResourceStatsActionWatchArgInterval = "interval"

var ResourceStatsActionTransferState = access.NewAction("transfer_state", []string{"common_name"})

const ResourceStatsActionTransferStateArgCommonName = "common_name"

var ResourceStatsActionScrapeMetrics = access.NewAction("scrape_metrics", []string{"common_name"})

const ResourceStatsActionScrapeMetricsArgCommonName = "common_name"

var PolicyAcmeManager = policy.NewAndPolicy("AcmeManager",
	policy.MustParsePolicy("ResourceIsAcme", "$resource.name == `acme`"),
	policy.NewOrPolicy("AcmeManagerActions",
		policy.MustParsePolicy("ActionIsObtain", "$action.name == `obtain`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGetCert", "$action.name == `get-cert`"),
		policy.MustParsePolicy("ActionIsDeleteCert", "$action.name == `delete-cert`"),
		policy.MustParsePolicy("ActionIsDeleteAccount", "$action.name == `delete-account`"),
	),
	policy.NewOrPolicy("AcmeManager",
		policy.NewAndPolicy("CanManageAcme",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyAlertViewer = policy.NewAndPolicy("AlertViewer",
	policy.MustParsePolicy("ResourceIsAlert", "$resource.name == `alert`"),
	policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
	policy.NewOrPolicy("AlertViewer",
		policy.NewAndPolicy("CanViewAlerts",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasManagerRole",
				policy.MustParsePolicy("AdminRole", "$user.roles list_contains `admin`"),
				policy.MustParsePolicy("ViewerRole", "$user.roles list_contains `viewer`"),
				policy.MustParsePolicy("MonitorRole", "$user.roles list_contains `monitor`"),
			),
		),
	),
)

var PolicyAllowIssueBootstrapToken = policy.NewAndPolicy("AllowIssueBootstrapToken",
	policy.MustParsePolicy("ResourceIsBootstrapToken", "$resource.name == `bootstrap_token`"),
	policy.MustParsePolicy("ActionIsIssue", "$action.name == `issue`"),
	policy.NewOrPolicy("AllowIssueBootstrapToken",
		policy.NewAndPolicy("CanIssueBootstrapToken",
			policy.MustParsePolicy("ArgumentsHaveDesiredValues", "$env.args.duration duration_lte `5m` and $env.args.appName in [`admin`,`monitor`,`popcache`, `l4lb`, `metrics`, `dns`, `router`, `workload`]"),
			policy.NewOrPolicy("CertificateExpiresPeriodIsValid",
				policy.MustParsePolicy("ExpiresPeriodIsLessThan1WeekForMachine", "$env.args.domain suffix $env.authority.system. and $env.args.expires_period duration_lte `168h`"),
				policy.MustParsePolicy("ExpiresPeriodIsLessThan1WeekForAdmin", "$env.args.domain suffix $env.authority.admin. and $env.args.expires_period duration_lte `168h`"),
			),
			policy.MustParsePolicy("UserAuthorityIsCAManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("DomainIsAllowed",
				policy.MustParsePolicy("DomainIsCAManager", "$env.args.domain == $env.authority.admin.ca.manager"),
				policy.MustParsePolicy("DomainIsDataplaneManager", "$env.args.domain == $env.authority.admin.dp.manager"),
				policy.MustParsePolicy("DomainIsL4LB", "$env.args.domain == $env.authority.system.dp.l4lb"),
				policy.MustParsePolicy("DomainIsPoPCache", "$env.args.domain == $env.authority.system.dp.popcache"),
				policy.MustParsePolicy("DomainIsMetrics", "$env.args.domain == $env.authority.system.metrics.prometheus"),
				policy.MustParsePolicy("DomainIsDNS", "$env.args.domain == $env.authority.system.dp.dns"),
				policy.MustParsePolicy("DomainIsRouter", "$env.args.domain == $env.authority.system.dp.router"),
				policy.MustParsePolicy("DomainIsWorkload", "$env.args.domain == $env.authority.system.dp.workload"),
			),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
				policy.NewAndPolicy("SystemBotIfNoBootstrapToken",
					policy.MustParsePolicy("IsSystemBot", "$user.roles list_contains `root_issuer_bot`"),
					policy.MustParsePolicy("InitialSystemSetup", "$env.ca.bootstrap_tokens.count == 0 and $env.ca.admins.count == 0"),
				),
			),
		),
	),
)

var PolicyCertificateManager = policy.NewAndPolicy("CertificateManager",
	policy.MustParsePolicy("ResourceIsCertificate", "$resource.name == `certificate`"),
	policy.NewOrPolicy("CertificateManagerActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
		policy.MustParsePolicy("ActionIsGarbageCollect", "$action.name == `garbage_collect`"),
	),
	policy.NewOrPolicy("CertificateManager",
		policy.NewAndPolicy("CanManageCertificates",
			policy.MustParsePolicy("UserAuthorityIsCAManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyConnectionViewer = policy.NewAndPolicy("ConnectionViewer",
	policy.MustParsePolicy("ResourceIsConnection", "$resource.name == `connection`"),
	policy.NewOrPolicy("ConnectionViewerActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("ConnectionViewer",
		policy.NewAndPolicy("CanViewConnections",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasManagerRole",
				policy.MustParsePolicy("AdminRole", "$user.roles list_contains `admin`"),
				policy.MustParsePolicy("ViewerRole", "$user.roles list_contains `viewer`"),
				policy.MustParsePolicy("MonitorRole", "$user.roles list_contains `monitor`"),
			),
		),
	),
)

var PolicyContainerManager = policy.NewAndPolicy("ContainerManager",
	policy.MustParsePolicy("ResourceIsContainer", "$resource.name == `container`"),
	policy.NewOrPolicy("ContainerManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
		policy.MustParsePolicy("ActionIsDiff", "$action.name == `diff`"),
	),
	policy.NewOrPolicy("ContainerManager",
		policy.NewAndPolicy("CanManageContainers",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasAdminRole", "$user.roles list_contains `admin`"),
		),
	),
)

var PolicyContainerMonitor = policy.NewAndPolicy("ContainerMonitor",
	policy.MustParsePolicy("ResourceIsContainer", "$resource.name == `container`"),
	policy.NewOrPolicy("ContainerMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDiff", "$action.name == `diff`"),
	),
	policy.NewOrPolicy("ContainerMonitor",
		policy.NewAndPolicy("CanContainerMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyCplaneFileManager = policy.NewAndPolicy("CplaneFileManager",
	policy.MustParsePolicy("ResourceIsCplaneFile", "$resource.name == `cplane_file`"),
	policy.NewOrPolicy("CplaneFileManagerActions",
		policy.MustParsePolicy("ActionIsUpload", "$action.name == `upload`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("CplaneFileManager",
		policy.NewAndPolicy("CanManageCplaneFiles",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyAllowCreateAuthority = policy.NewAndPolicy("AllowCreateAuthority",
	policy.MustParsePolicy("ResourceIsUserHierarchyAuthority", "$resource.name == `user_hierarchy_authority`"),
	policy.NewOrPolicy("AllowCreateAuthorityActions",
		policy.MustParsePolicy("ActionIsCreate", "$action.name == `create`"),
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
	),
	policy.NewOrPolicy("AllowCreateAuthority",
		policy.NewAndPolicy("CanCreateAuthority",
			policy.MustParsePolicy("UserAuthorityIsCAManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("AuthorityNameIsAllowed",
				policy.MustParsePolicy("CreatingCAManagerAuthority", "$env.args.authority_name suffix `.ca.admin`"),
				policy.MustParsePolicy("CreatingDataplaneManagerAuthority", "$env.args.authority_name suffix `.dp.admin`"),
				policy.MustParsePolicy("CreatingDataplaneAuthority", "$env.args.authority_name suffix `.dp.system`"),
				policy.MustParsePolicy("CreatingMetricsAuthority", "$env.args.authority_name suffix `.metrics.system`"),
			),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyDataplaneNodeManager = policy.NewAndPolicy("DataplaneNodeManager",
	policy.MustParsePolicy("ResourceIsDataplaneNode", "$resource.name == `dataplane_node`"),
	policy.NewOrPolicy("DataplaneNodeManagerActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsWatch", "$action.name == `watch`"),
		policy.MustParsePolicy("ActionIsStart", "$action.name == `start`"),
		policy.MustParsePolicy("ActionIsStop", "$action.name == `stop`"),
	),
	policy.NewOrPolicy("DataplaneNodeManager",
		policy.NewAndPolicy("CanManageDataplaneNodes",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyDataplaneNodeMonitor = policy.NewAndPolicy("DataplaneNodeMonitor",
	policy.MustParsePolicy("ResourceIsDataplaneNode", "$resource.name == `dataplane_node`"),
	policy.NewOrPolicy("DataplaneNodeMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("DataplaneNodeMonitor",
		policy.NewAndPolicy("CanDataplaneNodeMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyAllowDeleteAuthority = policy.NewAndPolicy("AllowDeleteAuthority",
	policy.MustParsePolicy("ResourceIsUserHierarchyAuthority", "$resource.name == `user_hierarchy_authority`"),
	policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	policy.NewOrPolicy("AllowDeleteAuthority",
		policy.NewAndPolicy("CanDeleteAuthority",
			policy.MustParsePolicy("UserAuthorityIsCAManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasRequiredRole", "$user.roles list_contains `admin`"),
		),
	),
)

var PolicyDenyControlPortOpen = policy.NewAndPolicy("DenyControlPortOpen",
	policy.MustParsePolicy("ResourceIsOpenPort", "$resource.name == `open_port`"),
	policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
	policy.NewOrPolicy("DenyControlPortOpen",
		policy.NewOrPolicy("ContainsControlPortOpen",
			policy.MustParsePolicy("Contains kscale control ports", "$env.args.ports list_contains_any [`udp:9443`,`tcp:9444`,`tcp:9091`]"),
			policy.MustParsePolicy("Contains TCP dataplane control ports", "$env.args.ports list_contains_any [`udp:8443`,`tcp:8080`]"),
			policy.MustParsePolicy("Contains UDP dataplane control ports", "$env.args.ports list_contains_any [`udp:10100`,`udp:10101`,`udp:10102`,`udp:10103`,`udp:10104`]"),
			policy.MustParsePolicy("Contains Golang pprof ports", "$env.args.ports list_contains_any [`tcp:6060`,`tcp:6061`,`tcp:6062`,`tcp:6063`,`tcp:6064`]"),
		),
	),
)

var PolicyDenySSHPortOpen = policy.NewAndPolicy("DenySSHPortOpen",
	policy.MustParsePolicy("ResourceIsOpenPort", "$resource.name == `open_port`"),
	policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
	policy.NewOrPolicy("DenySSHPortOpen",
		policy.NewOrPolicy("ContainsSSHPortOpen",
			policy.MustParsePolicy("Contains tcp:22, tcp:23", "$env.args.ports list_contains_any [`tcp:22`,`tcp:23`]"),
		),
	),
)

var PolicyDnsConfigManager = policy.NewAndPolicy("DnsConfigManager",
	policy.MustParsePolicy("ResourceIsDnsConfig", "$resource.name == `dns_config`"),
	policy.NewOrPolicy("DnsConfigManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("DnsConfigManager",
		policy.NewAndPolicy("CanManageDnsConfig",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyDnsConfigMonitor = policy.NewAndPolicy("DnsConfigMonitor",
	policy.MustParsePolicy("ResourceIsDnsConfig", "$resource.name == `dns_config`"),
	policy.NewOrPolicy("DnsConfigMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("DnsConfigMonitor",
		policy.NewAndPolicy("CanDnsConfigMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyDpFileManager = policy.NewAndPolicy("DpFileManager",
	policy.MustParsePolicy("ResourceIsDpFile", "$resource.name == `dp_file`"),
	policy.NewOrPolicy("DpFileManagerActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsSend", "$action.name == `send`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("DpFileManager",
		policy.NewAndPolicy("CanManageDpFiles",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyAllowRealtimeStatsAccess = policy.NewAndPolicy("AllowRealtimeStatsAccess",
	policy.MustParsePolicy("ResourceIsDpOperations", "$resource.name == `dp_operations`"),
	policy.MustParsePolicy("ActionIsRealtimeStats", "$action.name == `realtime_stats`"),
	policy.NewOrPolicy("AllowRealtimeStatsAccess",
		policy.NewAndPolicy("CanAccessRealtimeStats",
			policy.MustParsePolicy("UserAuthorityIsDataplane", "$user.authority.full_name suffix $env.authority.system.dp."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasStatsRole", "$user.roles list_contains_any [`l4lb`, `popcache`]"),
			),
		),
	),
)

var PolicyExpectedNodeManager = policy.NewAndPolicy("ExpectedNodeManager",
	policy.MustParsePolicy("ResourceIsExpectedNode", "$resource.name == `expected_node`"),
	policy.NewOrPolicy("ExpectedNodeManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("ExpectedNodeManager",
		policy.NewAndPolicy("CanManageExpectedNodes",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyExpectedNodeMonitor = policy.NewAndPolicy("ExpectedNodeMonitor",
	policy.MustParsePolicy("ResourceIsExpectedNode", "$resource.name == `expected_node`"),
	policy.NewOrPolicy("ExpectedNodeMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("ExpectedNodeMonitor",
		policy.NewAndPolicy("CanExpectedNodeMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyInterfaceManager = policy.NewAndPolicy("InterfaceManager",
	policy.MustParsePolicy("ResourceIsInterface", "$resource.name == `interface`"),
	policy.NewOrPolicy("InterfaceManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("InterfaceManager",
		policy.NewAndPolicy("CanManageInterfaces",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyInterfaceMonitor = policy.NewAndPolicy("InterfaceMonitor",
	policy.MustParsePolicy("ResourceIsInterface", "$resource.name == `interface`"),
	policy.NewOrPolicy("InterfaceMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("InterfaceMonitor",
		policy.NewAndPolicy("CanInterfaceMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyAllowL4LBFileDownload = policy.NewAndPolicy("AllowL4LBFileDownload",
	policy.MustParsePolicy("ResourceIsDpOperations", "$resource.name == `dp_operations`"),
	policy.MustParsePolicy("ActionIsDownloadFile", "$action.name == `download_file`"),
	policy.NewOrPolicy("AllowL4LBFileDownload",
		policy.NewAndPolicy("CanDownloadL4LBFile",
			policy.MustParsePolicy("UserAuthorityIsDataplane", "$user.authority.full_name suffix $env.authority.system.dp.l4lb."),
			policy.MustParsePolicy("ArgumentsHaveDesiredValues", "$env.args.file_name suffix `.o`"),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `l4lb`"),
			),
		),
	),
)

var PolicyL4LbObjectManager = policy.NewAndPolicy("L4lbObjectManager",
	policy.MustParsePolicy("ResourceIsL4LbObject", "$resource.name == `l4lb_object`"),
	policy.NewOrPolicy("L4lbObjectManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("L4lbObjectManager",
		policy.NewAndPolicy("CanManageL4lbObjects",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasAdminRole", "$user.roles list_contains `admin`"),
		),
	),
)

var PolicyAllowListAuthorities = policy.NewAndPolicy("AllowListAuthorities",
	policy.MustParsePolicy("ResourceIsUserHierarchyAuthority", "$resource.name == `user_hierarchy_authority`"),
	policy.NewOrPolicy("AllowListAuthoritiesActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsWatch", "$action.name == `watch`"),
	),
	policy.NewOrPolicy("AllowListAuthorities",
		policy.NewAndPolicy("CanListAuthorities",
			policy.MustParsePolicy("UserAuthorityIsCAManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyLogsLevelManager = policy.NewAndPolicy("LogsLevelManager",
	policy.MustParsePolicy("ResourceIsLogs", "$resource.name == `logs`"),
	policy.NewOrPolicy("LogsLevelManagerActions",
		policy.MustParsePolicy("ActionIsSetLevel", "$action.name == `set_level`"),
		policy.MustParsePolicy("ActionIsGetLevel", "$action.name == `get_level`"),
	),
	policy.NewOrPolicy("LogsLevelManager",
		policy.NewAndPolicy("CanManageLogLevel",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasAdminRole", "$user.roles list_contains `admin`"),
		),
	),
)

var PolicyLogsMonitor = policy.NewAndPolicy("LogsMonitor",
	policy.MustParsePolicy("ResourceIsLogs", "$resource.name == `logs`"),
	policy.MustParsePolicy("ActionIsTail", "$action.name == `tail`"),
	policy.NewOrPolicy("LogsMonitor",
		policy.NewAndPolicy("CanLogsMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyLogsViewer = policy.NewAndPolicy("LogsViewer",
	policy.MustParsePolicy("ResourceIsLogs", "$resource.name == `logs`"),
	policy.NewOrPolicy("LogsViewerActions",
		policy.MustParsePolicy("ActionIsStream", "$action.name == `stream`"),
		policy.MustParsePolicy("ActionIsTail", "$action.name == `tail`"),
	),
	policy.NewOrPolicy("LogsViewer",
		policy.NewAndPolicy("CanViewLogs",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyAllowConnectMetricsTarget = policy.NewAndPolicy("AllowConnectMetricsTarget",
	policy.MustParsePolicy("ResourceIsHttpProxy", "$resource.name == `http_proxy`"),
	policy.MustParsePolicy("ActionIsConnectToTarget", "$action.name == `connect_to_target`"),
	policy.NewOrPolicy("AllowConnectMetricsTarget",
		policy.NewAndPolicy("CanConnectToTarget",
			policy.MustParsePolicy("UserAuthorityIsCollectPrometheus", "$user.authority.full_name suffix $env.authority.system.metrics.prometheus."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("UserHasMetricsRole", "$user.roles list_contains `metrics`"),
			),
			policy.NewOrPolicy("TargetNameIsAllowed",
				policy.MustParsePolicy("TargetIsL4LB", "$env.args.target suffix $env.authority.system.dp.l4lb."),
				policy.MustParsePolicy("TargetIsPoPCache", "$env.args.target suffix $env.authority.system.dp.popcache."),
				policy.MustParsePolicy("TargetIsDNS", "$env.args.target suffix $env.authority.system.dp.dns."),
				policy.MustParsePolicy("TargetIsRouter", "$env.args.target suffix $env.authority.system.dp.router."),
			),
		),
	),
)

var PolicyAllowCollectMetrics = policy.NewAndPolicy("AllowCollectMetrics",
	policy.MustParsePolicy("ResourceIsHttpProxy", "$resource.name == `http_proxy`"),
	policy.MustParsePolicy("ActionIsRequestViaProxy", "$action.name == `request_via_proxy`"),
	policy.NewOrPolicy("AllowCollectMetrics",
		policy.NewAndPolicy("CanCollectMetrics",
			policy.MustParsePolicy("UserAuthorityIsCollectPrometheus", "$user.authority.full_name suffix $env.authority.system.metrics.prometheus."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("UserHasMetricsRole", "$user.roles list_contains `metrics`"),
			),
			policy.NewAndPolicy("RequestIsAllowed",
				policy.MustParsePolicy("MethodIsGET", "$env.args.method == `GET`"),
				policy.MustParsePolicy("PathIsMetrics", "$env.args.url == `/metrics`"),
			),
		),
	),
)

var PolicyMonitorChatAdmin = policy.NewAndPolicy("MonitorChatAdmin",
	policy.MustParsePolicy("ResourceIsMonitorChat", "$resource.name == `monitor_chat`"),
	policy.NewOrPolicy("MonitorChatAdminActions",
		policy.MustParsePolicy("ActionIsSend", "$action.name == `send`"),
		policy.MustParsePolicy("ActionIsResume", "$action.name == `resume`"),
	),
	policy.NewOrPolicy("MonitorChatAdmin",
		policy.NewAndPolicy("CanChatWithMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyMtuManager = policy.NewAndPolicy("MtuManager",
	policy.MustParsePolicy("ResourceIsMtu", "$resource.name == `mtu`"),
	policy.NewOrPolicy("MtuManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("MtuManager",
		policy.NewAndPolicy("CanManageMtu",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyMtuMonitor = policy.NewAndPolicy("MtuMonitor",
	policy.MustParsePolicy("ResourceIsMtu", "$resource.name == `mtu`"),
	policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
	policy.NewOrPolicy("MtuMonitor",
		policy.NewAndPolicy("CanMtuMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyNodeFileManager = policy.NewAndPolicy("NodeFileManager",
	policy.MustParsePolicy("ResourceIsNodeFile", "$resource.name == `node_file`"),
	policy.NewOrPolicy("NodeFileManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("NodeFileManager",
		policy.NewAndPolicy("CanManageNodeFiles",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasAdminRole", "$user.roles list_contains `admin`"),
		),
	),
)

var PolicyOpenPortMonitor = policy.NewAndPolicy("OpenPortMonitor",
	policy.MustParsePolicy("ResourceIsOpenPort", "$resource.name == `open_port`"),
	policy.NewOrPolicy("OpenPortMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDiff", "$action.name == `diff`"),
	),
	policy.NewOrPolicy("OpenPortMonitor",
		policy.NewAndPolicy("CanOpenPortMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyPopcacheConfigManager = policy.NewAndPolicy("PopcacheConfigManager",
	policy.MustParsePolicy("ResourceIsPopcacheConfig", "$resource.name == `popcache_config`"),
	policy.NewOrPolicy("PopcacheConfigManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("PopcacheConfigManager",
		policy.NewAndPolicy("CanManagePopcacheConfig",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyPopcacheConfigMonitor = policy.NewAndPolicy("PopcacheConfigMonitor",
	policy.MustParsePolicy("ResourceIsPopcacheConfig", "$resource.name == `popcache_config`"),
	policy.NewOrPolicy("PopcacheConfigMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("PopcacheConfigMonitor",
		policy.NewAndPolicy("CanPopcacheConfigMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyAllowPoPCacheFileDownload = policy.NewAndPolicy("AllowPoPCacheFileDownload",
	policy.MustParsePolicy("ResourceIsDpOperations", "$resource.name == `dp_operations`"),
	policy.MustParsePolicy("ActionIsDownloadFile", "$action.name == `download_file`"),
	policy.NewOrPolicy("AllowPoPCacheFileDownload",
		policy.NewAndPolicy("CanDownloadPoPCacheFile",
			policy.MustParsePolicy("UserAuthorityIsDataplane", "$user.authority.full_name suffix $env.authority.system.dp.popcache."),
			policy.MustParsePolicy("ArgumentsHaveDesiredValues", "$env.args.file_name suffix `.wasm` or $env.args.file_name suffix `.pem`"),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `popcache`"),
			),
		),
	),
)

var PolicyAllowRemoteShellCommandExecution = policy.NewAndPolicy("AllowRemoteShellCommandExecution",
	policy.MustParsePolicy("ResourceIsRemoteShell", "$resource.name == `remote_shell`"),
	policy.NewOrPolicy("AllowRemoteShellCommandExecutionActions",
		policy.MustParsePolicy("ActionIsDpExecuteCommand", "$action.name == `dp_execute_command`"),
		policy.MustParsePolicy("ActionIsCplaneExecuteCommand", "$action.name == `cplane_execute_command`"),
	),
	policy.NewAndPolicy("AllowRemoteShellCommandExecution",
		policy.MustParsePolicy("AdminManagerCanExecuteCommands", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
		policy.MustParsePolicy("FewSecondsAfterLogin", "$user.login_time.since duration_lt `10s`"),
	),
)

var PolicyAllowRevokeBootstrapToken = policy.NewAndPolicy("AllowRevokeBootstrapToken",
	policy.MustParsePolicy("ResourceIsBootstrapToken", "$resource.name == `bootstrap_token`"),
	policy.MustParsePolicy("ActionIsRevoke", "$action.name == `revoke`"),
	policy.NewOrPolicy("AllowRevokeBootstrapToken",
		policy.NewAndPolicy("CanRevokeBootstrapToken",
			policy.MustParsePolicy("UserAuthorityIsCAManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyRouterConfigManager = policy.NewAndPolicy("RouterConfigManager",
	policy.MustParsePolicy("ResourceIsRouterConfig", "$resource.name == `router_config`"),
	policy.NewOrPolicy("RouterConfigManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("RouterConfigManager",
		policy.NewAndPolicy("CanManageRouterConfig",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyRouterConfigMonitor = policy.NewAndPolicy("RouterConfigMonitor",
	policy.MustParsePolicy("ResourceIsRouterConfig", "$resource.name == `router_config`"),
	policy.NewOrPolicy("RouterConfigMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("RouterConfigMonitor",
		policy.NewAndPolicy("CanRouterConfigMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyRouterManager = policy.NewAndPolicy("RouterManager",
	policy.MustParsePolicy("ResourceIsOpenPort", "$resource.name == `open_port`"),
	policy.NewOrPolicy("RouterManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
		policy.MustParsePolicy("ActionIsDiff", "$action.name == `diff`"),
	),
	policy.NewOrPolicy("RouterManager",
		policy.NewAndPolicy("CanManageOpenPorts",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicySecretManager = policy.NewAndPolicy("SecretManager",
	policy.MustParsePolicy("ResourceIsSecret", "$resource.name == `secret`"),
	policy.NewOrPolicy("SecretManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("SecretManager",
		policy.NewAndPolicy("CanManageSecrets",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyAllowGetSelfInfo = policy.NewAndPolicy("AllowGetSelfInfo",
	policy.MustParsePolicy("ResourceIsSessionManagement", "$resource.name == `session_management`"),
	policy.MustParsePolicy("ActionIsSelfInfo", "$action.name == `self_info`"),
	policy.NewOrPolicy("AllowGetSelfInfo",
		policy.MustParsePolicy("EveryoneCanGetSelfInfo", "$user.authority.full_name suffix $env.authority."),
	),
)

var PolicyStatsManager = policy.NewAndPolicy("StatsManager",
	policy.MustParsePolicy("ResourceIsStats", "$resource.name == `stats`"),
	policy.NewOrPolicy("StatsManagerActions",
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsWatch", "$action.name == `watch`"),
		policy.MustParsePolicy("ActionIsTransferState", "$action.name == `transfer_state`"),
		policy.MustParsePolicy("ActionIsScrapeMetrics", "$action.name == `scrape_metrics`"),
	),
	policy.NewOrPolicy("StatsManager",
		policy.NewAndPolicy("CanReadStats",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyStatsMonitor = policy.NewAndPolicy("StatsMonitor",
	policy.MustParsePolicy("ResourceIsStats", "$resource.name == `stats`"),
	policy.NewOrPolicy("StatsMonitorActions",
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsScrapeMetrics", "$action.name == `scrape_metrics`"),
	),
	policy.NewOrPolicy("StatsMonitor",
		policy.NewAndPolicy("CanStatsMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyVipManager = policy.NewAndPolicy("VipManager",
	policy.MustParsePolicy("ResourceIsVip", "$resource.name == `vip`"),
	policy.NewOrPolicy("VipManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("VipManager",
		policy.NewAndPolicy("CanManageVips",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyVipMonitor = policy.NewAndPolicy("VipMonitor",
	policy.MustParsePolicy("ResourceIsVip", "$resource.name == `vip`"),
	policy.NewOrPolicy("VipMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
	),
	policy.NewOrPolicy("VipMonitor",
		policy.NewAndPolicy("CanVipMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

var PolicyWasmManager = policy.NewAndPolicy("WasmManager",
	policy.MustParsePolicy("ResourceIsWasmModule", "$resource.name == `wasm_module`"),
	policy.NewOrPolicy("WasmManagerActions",
		policy.MustParsePolicy("ActionIsApply", "$action.name == `apply`"),
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDelete", "$action.name == `delete`"),
	),
	policy.NewOrPolicy("WasmManager",
		policy.NewAndPolicy("CanManageWasmModules",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.NewOrPolicy("UserHasRequiredRole",
				policy.MustParsePolicy("HumanUserHasManagementRole", "$user.roles list_contains `admin`"),
			),
		),
	),
)

var PolicyWasmMonitor = policy.NewAndPolicy("WasmMonitor",
	policy.MustParsePolicy("ResourceIsWasmModule", "$resource.name == `wasm_module`"),
	policy.NewOrPolicy("WasmMonitorActions",
		policy.MustParsePolicy("ActionIsList", "$action.name == `list`"),
		policy.MustParsePolicy("ActionIsGet", "$action.name == `get`"),
		policy.MustParsePolicy("ActionIsDiff", "$action.name == `diff`"),
	),
	policy.NewOrPolicy("WasmMonitor",
		policy.NewAndPolicy("CanWasmMonitor",
			policy.MustParsePolicy("UserAuthorityIsManager", "$user.authority.full_name suffix $env.authority.admin.ca.manager."),
			policy.MustParsePolicy("UserHasMonitorRole", "$user.roles list_contains `monitor`"),
		),
	),
)

func AllowPolicies() []access.Policy {
	return []access.Policy{
		PolicyAcmeManager,
		PolicyAlertViewer,
		PolicyAllowIssueBootstrapToken,
		PolicyCertificateManager,
		PolicyConnectionViewer,
		PolicyContainerManager,
		PolicyContainerMonitor,
		PolicyCplaneFileManager,
		PolicyAllowCreateAuthority,
		PolicyDataplaneNodeManager,
		PolicyDataplaneNodeMonitor,
		PolicyAllowDeleteAuthority,
		PolicyDnsConfigManager,
		PolicyDnsConfigMonitor,
		PolicyDpFileManager,
		PolicyAllowRealtimeStatsAccess,
		PolicyExpectedNodeManager,
		PolicyExpectedNodeMonitor,
		PolicyInterfaceManager,
		PolicyInterfaceMonitor,
		PolicyAllowL4LBFileDownload,
		PolicyL4LbObjectManager,
		PolicyAllowListAuthorities,
		PolicyLogsLevelManager,
		PolicyLogsMonitor,
		PolicyLogsViewer,
		PolicyAllowConnectMetricsTarget,
		PolicyAllowCollectMetrics,
		PolicyMonitorChatAdmin,
		PolicyMtuManager,
		PolicyMtuMonitor,
		PolicyNodeFileManager,
		PolicyOpenPortMonitor,
		PolicyPopcacheConfigManager,
		PolicyPopcacheConfigMonitor,
		PolicyAllowPoPCacheFileDownload,
		PolicyAllowRemoteShellCommandExecution,
		PolicyAllowRevokeBootstrapToken,
		PolicyRouterConfigManager,
		PolicyRouterConfigMonitor,
		PolicyRouterManager,
		PolicySecretManager,
		PolicyAllowGetSelfInfo,
		PolicyStatsManager,
		PolicyStatsMonitor,
		PolicyVipManager,
		PolicyVipMonitor,
		PolicyWasmManager,
		PolicyWasmMonitor,
	}
}

func DenyPolicies() []access.Policy {
	return []access.Policy{
		PolicyDenyControlPortOpen,
		PolicyDenySSHPortOpen,
	}
}

var PolicyMap = map[string]map[string]*access.PolicyList{
	"acme": map[string]*access.PolicyList{
		"obtain": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAcmeManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAcmeManager,
			},
		},
		"get-cert": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAcmeManager,
			},
		},
		"delete-cert": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAcmeManager,
			},
		},
		"delete-account": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAcmeManager,
			},
		},
	},
	"alert": map[string]*access.PolicyList{
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAlertViewer,
			},
		},
	},
	"bootstrap_token": map[string]*access.PolicyList{
		"issue": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowIssueBootstrapToken,
			},
		},
		"revoke": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowRevokeBootstrapToken,
			},
		},
	},
	"certificate": map[string]*access.PolicyList{
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyCertificateManager,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyCertificateManager,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyCertificateManager,
			},
		},
		"garbage_collect": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyCertificateManager,
			},
		},
	},
	"connection": map[string]*access.PolicyList{
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyConnectionViewer,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyConnectionViewer,
			},
		},
	},
	"container": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyContainerManager,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyContainerManager,
				PolicyContainerMonitor,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyContainerManager,
				PolicyContainerMonitor,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyContainerManager,
			},
		},
		"diff": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyContainerManager,
				PolicyContainerMonitor,
			},
		},
	},
	"cplane_file": map[string]*access.PolicyList{
		"upload": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyCplaneFileManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyCplaneFileManager,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyCplaneFileManager,
			},
		},
	},
	"user_hierarchy_authority": map[string]*access.PolicyList{
		"create": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowCreateAuthority,
			},
		},
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowCreateAuthority,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowDeleteAuthority,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowListAuthorities,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowListAuthorities,
			},
		},
		"watch": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowListAuthorities,
			},
		},
	},
	"dataplane_node": map[string]*access.PolicyList{
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDataplaneNodeManager,
				PolicyDataplaneNodeMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDataplaneNodeManager,
				PolicyDataplaneNodeMonitor,
			},
		},
		"watch": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDataplaneNodeManager,
			},
		},
		"start": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDataplaneNodeManager,
			},
		},
		"stop": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDataplaneNodeManager,
			},
		},
	},
	"open_port": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{
				PolicyDenyControlPortOpen,
				PolicyDenySSHPortOpen,
			},
			Allow: []access.Policy{
				PolicyRouterManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyOpenPortMonitor,
				PolicyRouterManager,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyOpenPortMonitor,
				PolicyRouterManager,
			},
		},
		"diff": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyOpenPortMonitor,
				PolicyRouterManager,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyRouterManager,
			},
		},
	},
	"dns_config": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDnsConfigManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDnsConfigManager,
				PolicyDnsConfigMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDnsConfigManager,
				PolicyDnsConfigMonitor,
			},
		},
	},
	"dp_file": map[string]*access.PolicyList{
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDpFileManager,
			},
		},
		"send": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDpFileManager,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyDpFileManager,
			},
		},
	},
	"dp_operations": map[string]*access.PolicyList{
		"realtime_stats": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowRealtimeStatsAccess,
			},
		},
		"download_file": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowL4LBFileDownload,
				PolicyAllowPoPCacheFileDownload,
			},
		},
	},
	"expected_node": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyExpectedNodeManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyExpectedNodeManager,
				PolicyExpectedNodeMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyExpectedNodeManager,
				PolicyExpectedNodeMonitor,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyExpectedNodeManager,
			},
		},
	},
	"interface": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyInterfaceManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyInterfaceManager,
				PolicyInterfaceMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyInterfaceManager,
				PolicyInterfaceMonitor,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyInterfaceManager,
			},
		},
	},
	"l4lb_object": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyL4LbObjectManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyL4LbObjectManager,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyL4LbObjectManager,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyL4LbObjectManager,
			},
		},
	},
	"logs": map[string]*access.PolicyList{
		"set_level": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyLogsLevelManager,
			},
		},
		"get_level": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyLogsLevelManager,
			},
		},
		"tail": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyLogsMonitor,
				PolicyLogsViewer,
			},
		},
		"stream": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyLogsViewer,
			},
		},
	},
	"http_proxy": map[string]*access.PolicyList{
		"connect_to_target": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowConnectMetricsTarget,
			},
		},
		"request_via_proxy": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowCollectMetrics,
			},
		},
	},
	"monitor_chat": map[string]*access.PolicyList{
		"send": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyMonitorChatAdmin,
			},
		},
		"resume": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyMonitorChatAdmin,
			},
		},
	},
	"mtu": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyMtuManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyMtuManager,
				PolicyMtuMonitor,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyMtuManager,
			},
		},
	},
	"node_file": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyNodeFileManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyNodeFileManager,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyNodeFileManager,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyNodeFileManager,
			},
		},
	},
	"popcache_config": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyPopcacheConfigManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyPopcacheConfigManager,
				PolicyPopcacheConfigMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyPopcacheConfigManager,
				PolicyPopcacheConfigMonitor,
			},
		},
	},
	"remote_shell": map[string]*access.PolicyList{
		"dp_execute_command": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowRemoteShellCommandExecution,
			},
		},
		"cplane_execute_command": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowRemoteShellCommandExecution,
			},
		},
	},
	"router_config": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyRouterConfigManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyRouterConfigManager,
				PolicyRouterConfigMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyRouterConfigManager,
				PolicyRouterConfigMonitor,
			},
		},
	},
	"secret": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicySecretManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicySecretManager,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicySecretManager,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicySecretManager,
			},
		},
	},
	"session_management": map[string]*access.PolicyList{
		"self_info": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyAllowGetSelfInfo,
			},
		},
	},
	"stats": map[string]*access.PolicyList{
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyStatsManager,
				PolicyStatsMonitor,
			},
		},
		"watch": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyStatsManager,
			},
		},
		"transfer_state": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyStatsManager,
			},
		},
		"scrape_metrics": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyStatsManager,
				PolicyStatsMonitor,
			},
		},
	},
	"vip": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyVipManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyVipManager,
				PolicyVipMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyVipManager,
				PolicyVipMonitor,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyVipManager,
			},
		},
	},
	"wasm_module": map[string]*access.PolicyList{
		"apply": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyWasmManager,
			},
		},
		"list": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyWasmManager,
				PolicyWasmMonitor,
			},
		},
		"get": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyWasmManager,
				PolicyWasmMonitor,
			},
		},
		"delete": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyWasmManager,
			},
		},
		"diff": &access.PolicyList{
			Deny: []access.Policy{},
			Allow: []access.Policy{
				PolicyWasmMonitor,
			},
		},
	},
}
