// Code generated by script/internal_value.py. DO NOT EDIT.

package stat

import (
	"fmt"

	"github.com/on-keyday/kscale/l4lb/l4lbdrv"
	"github.com/prometheus/client_golang/prometheus"
)

type PromMetrics struct {
	DnsDnsPort                              uint16
	DnsRequestsTotal                        uint64
	DnsResponsesTotal                       uint64
	DnsErrorsTotal                          uint64
	DnsEnabled                              bool
	L4lbEbpfRxHookCallCount                 uint64
	L4lbEbpfRxByteTotal                     uint64
	L4lbEbpfRxPacketTotal                   uint64
	L4lbEbpfRxTotalSize                     uint64
	L4lbEbpfTooShortPacketTotal             uint64
	L4lbEbpfNonIpv4PacketTotal              uint64
	L4lbEbpfNonIpv6PacketTotal              uint64
	L4lbEbpfIpOptionPacketTotal             uint64
	L4lbEbpfNonSupportedProtoPacketTotal    uint64
	L4lbEbpfArpPacketTotal                  uint64
	L4lbEbpfNoVipMatchTotal                 uint64
	L4lbEbpfFailedAdjustHeadTotal           uint64
	L4lbEbpfFailedAdjustTailTotal           uint64
	L4lbEbpfTcpPacketTotal                  uint64
	L4lbEbpfMtuExceededTotal                uint64
	L4lbEbpfTcpNoDestEntryTotal             uint64
	L4lbEbpfTcpSynPacketTotal               uint64
	L4lbEbpfTcpSynackPacketTotal            uint64
	L4lbEbpfTcpRstPacketTotal               uint64
	L4lbEbpfTcpAckPacketTotal               uint64
	L4lbEbpfTcpFinPacketTotal               uint64
	L4lbEbpfTcpUrgPacketTotal               uint64
	L4lbEbpfTcpPshPacketTotal               uint64
	L4lbEbpfTcpEcePacketTotal               uint64
	L4lbEbpfTcpCwrPacketTotal               uint64
	L4lbEbpfTcpOtherFlagPacketTotal         uint64
	L4lbEbpfTcpNoFlagPacketTotal            uint64
	L4lbEbpfUdpPacketTotal                  uint64
	L4lbEbpfQuiclbNoDestPortMatchTotal      uint64
	L4lbEbpfQuiclbShortPacketTotal          uint64
	L4lbEbpfQuiclbLongPacketTotal           uint64
	L4lbEbpfQuiclbInitialRoutingPacketTotal uint64
	L4lbEbpfQuiclbTooShortLongPacketTotal   uint64
	L4lbEbpfQuiclbNoConnectionIdTotal       uint64
	L4lbEbpfQuiclbNoDestEntryTotal          uint64
	L4lbEbpfQuiclbInvalidCryptoContextTotal uint64
	L4lbEbpfQuiclbEncryptSuccessCallTotal   uint64
	L4lbEbpfQuiclbDecryptSuccessCallTotal   uint64
	L4lbEbpfQuiclbConnidCacheHitTotal       uint64
	L4lbEbpfQuiclbVersionNegotiationTotal   uint64
	L4lbEbpfQuiclbVersion1Total             uint64
	L4lbEbpfQuiclbVersion2Total             uint64
	L4lbEbpfQuiclbOtherVersionTotal         uint64
	L4lbEbpfQuiclbInitialPacketTotal        uint64
	L4lbEbpfQuiclbZeroRttPacketTotal        uint64
	L4lbEbpfQuiclbHandshakePacketTotal      uint64
	L4lbEbpfQuiclbRetryPacketTotal          uint64
	L4lbEbpfBuggyDestIpZeroTotal            uint64
	L4lbEbpfIcmpEchoReplyTotal              uint64
	L4lbEbpfIcmpDroppedTotal                uint64
	PacketSizeDistribution                  l4lbdrv.PacketSizeDist
	ISNLeastSignificantByteDistribution     l4lbdrv.ISNLeastSignificantByteMap
	SourceIPPacketCount                     l4lbdrv.SrcIPCounts
	L4lbEbpfEnabled                         bool
	PopcacheRequestsTotal                   uint64
	PopcacheRequestsEndTotal                uint64
	PopcacheConnectTotal                    uint64
	PopcacheCacheHitsTotal                  uint64
	PopcacheCacheMissesTotal                uint64
	PopcacheCloseTotal                      uint64
	PopcacheHijackedTotal                   uint64
	PopcachePerMethodTotal                  [10]uint64
	PopcachePerProtocolTotal                [8]uint64
	PopcacheHttpPort                        uint16
	PopcacheHttpsPort                       uint16
	PopcacheHttp3Port                       uint16
	PopcacheEnabled                         bool
	CpuUsages                               []float64
	MemoryUsage                             uint64
	DiskUsage                               uint64
	DiskSwap                                float64
	ServerUptime                            float64
	LoadAvg                                 [3]float64
	MemoryTotal                             uint64
	DiskTotal                               uint64
	CommonName                              string
	RTT                                     float64
	AppStatus                               float64
	TemperatureCelsius                      []float64
	TemperatureSensorKeys                   []string
	RxBytes                                 []uint64
	TxBytes                                 []uint64
	RxPackets                               []uint64
	TxPackets                               []uint64
	RxErrors                                []uint64
	TxErrors                                []uint64
	RxDrops                                 []uint64
	TxDrops                                 []uint64
	Interfaces                              []string
}

func (s *PromMetrics) UpdateDnsStat(stat *DnsStat) {
	s.DnsDnsPort = uint16(stat.DnsStats.DnsPort)
	s.DnsRequestsTotal = uint64(stat.DnsStats.RequestsTotal)
	s.DnsResponsesTotal = uint64(stat.DnsStats.ResponsesTotal)
	s.DnsErrorsTotal = uint64(stat.DnsStats.ErrorsTotal)
	/*set by user*/
}

func (s *PromMetrics) UpdateL4lbStat(stat *L4lbStat) {
	s.L4lbEbpfRxHookCallCount = stat.EbpfStats.RxHookCallCount
	s.L4lbEbpfRxByteTotal = stat.EbpfStats.RxByteTotal
	s.L4lbEbpfRxPacketTotal = stat.EbpfStats.RxPacketTotal
	s.L4lbEbpfRxTotalSize = stat.EbpfStats.RxTotalSize
	s.L4lbEbpfTooShortPacketTotal = stat.EbpfStats.TooShortPacketTotal
	s.L4lbEbpfNonIpv4PacketTotal = stat.EbpfStats.NonIpv4PacketTotal
	s.L4lbEbpfNonIpv6PacketTotal = stat.EbpfStats.NonIpv6PacketTotal
	s.L4lbEbpfIpOptionPacketTotal = stat.EbpfStats.IpOptionPacketTotal
	s.L4lbEbpfNonSupportedProtoPacketTotal = stat.EbpfStats.NonSupportedProtoPacketTotal
	s.L4lbEbpfArpPacketTotal = stat.EbpfStats.ArpPacketTotal
	s.L4lbEbpfNoVipMatchTotal = stat.EbpfStats.NoVipMatchTotal
	s.L4lbEbpfFailedAdjustHeadTotal = stat.EbpfStats.FailedAdjustHeadTotal
	s.L4lbEbpfFailedAdjustTailTotal = stat.EbpfStats.FailedAdjustTailTotal
	s.L4lbEbpfTcpPacketTotal = stat.EbpfStats.TcpPacketTotal
	s.L4lbEbpfMtuExceededTotal = stat.EbpfStats.MtuExceededTotal
	s.L4lbEbpfTcpNoDestEntryTotal = stat.EbpfStats.TcpNoDestEntryTotal
	s.L4lbEbpfTcpSynPacketTotal = stat.EbpfStats.TcpSynPacketTotal
	s.L4lbEbpfTcpSynackPacketTotal = stat.EbpfStats.TcpSynackPacketTotal
	s.L4lbEbpfTcpRstPacketTotal = stat.EbpfStats.TcpRstPacketTotal
	s.L4lbEbpfTcpAckPacketTotal = stat.EbpfStats.TcpAckPacketTotal
	s.L4lbEbpfTcpFinPacketTotal = stat.EbpfStats.TcpFinPacketTotal
	s.L4lbEbpfTcpUrgPacketTotal = stat.EbpfStats.TcpUrgPacketTotal
	s.L4lbEbpfTcpPshPacketTotal = stat.EbpfStats.TcpPshPacketTotal
	s.L4lbEbpfTcpEcePacketTotal = stat.EbpfStats.TcpEcePacketTotal
	s.L4lbEbpfTcpCwrPacketTotal = stat.EbpfStats.TcpCwrPacketTotal
	s.L4lbEbpfTcpOtherFlagPacketTotal = stat.EbpfStats.TcpOtherFlagPacketTotal
	s.L4lbEbpfTcpNoFlagPacketTotal = stat.EbpfStats.TcpNoFlagPacketTotal
	s.L4lbEbpfUdpPacketTotal = stat.EbpfStats.UdpPacketTotal
	s.L4lbEbpfQuiclbNoDestPortMatchTotal = stat.EbpfStats.QuiclbNoDestPortMatchTotal
	s.L4lbEbpfQuiclbShortPacketTotal = stat.EbpfStats.QuiclbShortPacketTotal
	s.L4lbEbpfQuiclbLongPacketTotal = stat.EbpfStats.QuiclbLongPacketTotal
	s.L4lbEbpfQuiclbInitialRoutingPacketTotal = stat.EbpfStats.QuiclbInitialRoutingPacketTotal
	s.L4lbEbpfQuiclbTooShortLongPacketTotal = stat.EbpfStats.QuiclbTooShortLongPacketTotal
	s.L4lbEbpfQuiclbNoConnectionIdTotal = stat.EbpfStats.QuiclbNoConnectionIdTotal
	s.L4lbEbpfQuiclbNoDestEntryTotal = stat.EbpfStats.QuiclbNoDestEntryTotal
	s.L4lbEbpfQuiclbInvalidCryptoContextTotal = stat.EbpfStats.QuiclbInvalidCryptoContextTotal
	s.L4lbEbpfQuiclbEncryptSuccessCallTotal = stat.EbpfStats.QuiclbEncryptSuccessCallTotal
	s.L4lbEbpfQuiclbDecryptSuccessCallTotal = stat.EbpfStats.QuiclbDecryptSuccessCallTotal
	s.L4lbEbpfQuiclbConnidCacheHitTotal = stat.EbpfStats.QuiclbConnidCacheHitTotal
	s.L4lbEbpfQuiclbVersionNegotiationTotal = stat.EbpfStats.QuiclbVersionNegotiationTotal
	s.L4lbEbpfQuiclbVersion1Total = stat.EbpfStats.QuiclbVersion1Total
	s.L4lbEbpfQuiclbVersion2Total = stat.EbpfStats.QuiclbVersion2Total
	s.L4lbEbpfQuiclbOtherVersionTotal = stat.EbpfStats.QuiclbOtherVersionTotal
	s.L4lbEbpfQuiclbInitialPacketTotal = stat.EbpfStats.QuiclbInitialPacketTotal
	s.L4lbEbpfQuiclbZeroRttPacketTotal = stat.EbpfStats.QuiclbZeroRttPacketTotal
	s.L4lbEbpfQuiclbHandshakePacketTotal = stat.EbpfStats.QuiclbHandshakePacketTotal
	s.L4lbEbpfQuiclbRetryPacketTotal = stat.EbpfStats.QuiclbRetryPacketTotal
	s.L4lbEbpfBuggyDestIpZeroTotal = stat.EbpfStats.BuggyDestIpZeroTotal
	s.L4lbEbpfIcmpEchoReplyTotal = stat.EbpfStats.IcmpEchoReplyTotal
	s.L4lbEbpfIcmpDroppedTotal = stat.EbpfStats.IcmpDroppedTotal
	s.PacketSizeDistribution = stat.PacketSizeDistribution
	s.ISNLeastSignificantByteDistribution = stat.ISNLeastSignificantByteDistribution
	s.SourceIPPacketCount = stat.SourceIPPacketCount
	/*set by user*/
}

func (s *PromMetrics) UpdatePopcacheStat(stat *PopcacheStat) {
	s.PopcacheRequestsTotal = uint64(stat.PopcacheStats.RequestsTotal)
	s.PopcacheRequestsEndTotal = uint64(stat.PopcacheStats.RequestsEndTotal)
	s.PopcacheConnectTotal = uint64(stat.PopcacheStats.ConnectTotal)
	s.PopcacheCacheHitsTotal = uint64(stat.PopcacheStats.CacheHitsTotal)
	s.PopcacheCacheMissesTotal = uint64(stat.PopcacheStats.CacheMissesTotal)
	s.PopcacheCloseTotal = uint64(stat.PopcacheStats.CloseTotal)
	s.PopcacheHijackedTotal = uint64(stat.PopcacheStats.HijackedTotal)
	s.PopcachePerMethodTotal = [10]uint64{uint64(stat.PopcacheStats.PerMethodTotalGet), uint64(stat.PopcacheStats.PerMethodTotalHead), uint64(stat.PopcacheStats.PerMethodTotalPost), uint64(stat.PopcacheStats.PerMethodTotalPut), uint64(stat.PopcacheStats.PerMethodTotalDelete), uint64(stat.PopcacheStats.PerMethodTotalPatch), uint64(stat.PopcacheStats.PerMethodTotalOptions), uint64(stat.PopcacheStats.PerMethodTotalTrace), uint64(stat.PopcacheStats.PerMethodTotalConnect), uint64(stat.PopcacheStats.PerMethodTotalOther)}
	s.PopcachePerProtocolTotal = [8]uint64{uint64(stat.PopcacheStats.PerProtocolTotalHttp10Plain), uint64(stat.PopcacheStats.PerProtocolTotalHttp10), uint64(stat.PopcacheStats.PerProtocolTotalHttp11Plain), uint64(stat.PopcacheStats.PerProtocolTotalHttp11), uint64(stat.PopcacheStats.PerProtocolTotalHttp2), uint64(stat.PopcacheStats.PerProtocolTotalHttp3), uint64(stat.PopcacheStats.PerProtocolTotalOtherPlain), uint64(stat.PopcacheStats.PerProtocolTotalOther)}
	s.PopcacheHttpPort = uint16(stat.PopcacheStats.HttpPort)
	s.PopcacheHttpsPort = uint16(stat.PopcacheStats.HttpsPort)
	s.PopcacheHttp3Port = uint16(stat.PopcacheStats.Http3Port)
	/*set by user*/
}

func (s *PromMetrics) UpdateHostRealtimeStat(stat *HostRealtimeStat) {
	s.CpuUsages = stat.CpuUsages
	s.MemoryUsage = stat.MemoryUsage
	s.DiskUsage = stat.DiskUsage
	s.DiskSwap = stat.DiskSwap
	s.ServerUptime = stat.ServerUptime.Seconds()
	s.LoadAvg = stat.LoadAvg
}

func (s *PromMetrics) UpdateHostSpecStat(stat *HostSpecStat) {
	s.MemoryTotal = stat.MemoryTotal
	s.DiskTotal = stat.DiskTotal
}

func (s *PromMetrics) UpdateCdnAppSpecStat(stat *CdnAppSpecStat) {
	s.CommonName = stat.CommonName
}

func (s *PromMetrics) UpdateConnectionStat(stat *ConnectionStat) {
	s.RTT = float64(stat.RTT.Microseconds())
}

func (s *PromMetrics) UpdateCdnAppRealtimeStat(stat *CdnAppRealtimeStat) {
	s.AppStatus = float64(stat.AppStatus)
}

func (s *PromMetrics) UpdateHostPhysicalStat(stat *HostPhysicalStat) {
	s.TemperatureCelsius = stat.TemperatureCelsius
	s.TemperatureSensorKeys = stat.TemperatureSensorKeys
}

func (s *PromMetrics) UpdateNetworkRealtimeStat(stat *NetworkRealtimeStat) {
	s.RxBytes = stat.RxBytes
	s.TxBytes = stat.TxBytes
	s.RxPackets = stat.RxPackets
	s.TxPackets = stat.TxPackets
	s.RxErrors = stat.RxErrors
	s.TxErrors = stat.TxErrors
	s.RxDrops = stat.RxDrops
	s.TxDrops = stat.TxDrops
}

func (s *PromMetrics) UpdateNetworkSpecStat(stat *NetworkSpecStat) {
	s.Interfaces = func() []string {
		r := make([]string, len(stat.Interfaces))
		for i := range stat.Interfaces {
			r[i] = stat.Interfaces[i].Name
		}
		return r
	}()
}

func (s *PromMetrics) Collect(ch chan<- prometheus.Metric) {
	if s.DnsEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_dns_dns_port", "Dns metric dns_port", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.DnsDnsPort), s.CommonName)
	}
	if s.DnsEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_dns_requests_total", "Dns metric requests_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.DnsRequestsTotal), s.CommonName)
	}
	if s.DnsEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_dns_responses_total", "Dns metric responses_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.DnsResponsesTotal), s.CommonName)
	}
	if s.DnsEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_dns_errors_total", "Dns metric errors_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.DnsErrorsTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_rx_hook_call_count", "Number of times the XDP hook is called.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfRxHookCallCount), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_rx_byte_total", "Total number of bytes received. (including not handled)", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfRxByteTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_rx_packet_total", "Number of packets received against known VIPs.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfRxPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_rx_total_size", "Total size of packets received against known VIPs.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfRxTotalSize), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_too_short_packet_total", "Number of packets dropped due to being too short.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTooShortPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_non_ipv4_packet_total", "Number of packets dropped due to their IP protocol version not v4.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfNonIpv4PacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_non_ipv6_packet_total", "Number of packets dropped due to their IP protocol version not v6.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfNonIpv6PacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_ip_option_packet_total", "Number of packets dropped due to their IP header having options. (currently not supported)", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfIpOptionPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_non_supported_proto_packet_total", "Number of packets dropped due to their protocol not being TCP.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfNonSupportedProtoPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_arp_packet_total", "Number of ARP packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfArpPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_no_vip_match_total", "Number of packets dropped due to their dest IP address not matching any known VIP.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfNoVipMatchTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_failed_adjust_head_total", "Number of xdp_adjust_head failures.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfFailedAdjustHeadTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_failed_adjust_tail_total", "Number of xdp_adjust_tail failures.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfFailedAdjustTailTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_packet_total", "Number of TCP packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_mtu_exceeded_total", "Number of packets dropped due to MTU exceeded.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfMtuExceededTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_no_dest_entry_total", "Number of packets dropped due to no backend available.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpNoDestEntryTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_syn_packet_total", "Number of TCP SYN packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpSynPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_synack_packet_total", "Number of TCP SYN-ACK packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpSynackPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_rst_packet_total", "Number of TCP RST packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpRstPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_ack_packet_total", "Number of TCP ACK packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpAckPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_fin_packet_total", "Number of TCP FIN packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpFinPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_urg_packet_total", "Number of TCP URG packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpUrgPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_psh_packet_total", "Number of TCP PSH packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpPshPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_ece_packet_total", "Number of TCP ECE packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpEcePacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_cwr_packet_total", "Number of TCP CWR packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpCwrPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_other_flag_packet_total", "Number of TCP packets received with other flags.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpOtherFlagPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_tcp_no_flag_packet_total", "Number of TCP packets received without any flags.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfTcpNoFlagPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_udp_packet_total", "Number of UDP packets received.  ", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfUdpPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_no_dest_port_match_total", "Number of QUIC-LB packets received without matching destination port.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbNoDestPortMatchTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_short_packet_total", "Number of QUIC-LB short packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbShortPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_long_packet_total", "Number of QUIC-LB long packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbLongPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_initial_routing_packet_total", "Number of QUIC-LB initial routing packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbInitialRoutingPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_too_short_long_packet_total", "Number of QUIC-LB short-long packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbTooShortLongPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_no_connection_id_total", "Number of QUIC-LB packets received without connection ID.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbNoConnectionIdTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_no_dest_entry_total", "Number of QUIC-LB packets received without destination entry.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbNoDestEntryTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_invalid_crypto_context_total", "Number of QUIC-LB packets received with invalid crypto context.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbInvalidCryptoContextTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_encrypt_success_call_total", "Number of QUIC-LB packets that called bpf_crypto_encrypt.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbEncryptSuccessCallTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_decrypt_success_call_total", "Number of QUIC-LB packets that called bpf_crypto_decrypt.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbDecryptSuccessCallTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_connid_cache_hit_total", "Number of QUIC-LB connection ID cache hits.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbConnidCacheHitTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_version_negotiation_total", "Number of QUIC-LB version negotiation packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbVersionNegotiationTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_version_1_total", "Number of QUIC-LB version 1 packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbVersion1Total), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_version_2_total", "Number of QUIC-LB version 2 packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbVersion2Total), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_other_version_total", "Number of QUIC-LB packets received with other versions.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbOtherVersionTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_initial_packet_total", "Number of QUIC-LB initial packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbInitialPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_zero_rtt_packet_total", "Number of QUIC-LB 0-RTT packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbZeroRttPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_handshake_packet_total", "Number of QUIC-LB handshake packets received.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbHandshakePacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_quiclb_retry_packet_total", "Number of QUIC-LB retry packets received. (this may bug or attack)", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfQuiclbRetryPacketTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_buggy_dest_ip_zero_total", "Number of times a destination entry with IP address 0 is encountered (indicating a bug).", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfBuggyDestIpZeroTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_icmp_echo_reply_total", "Number of ICMPv4 echo replies sent for VIP-destined echo requests.", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfIcmpEchoReplyTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_icmp_dropped_total", "Number of VIP-destined ICMPv4 packets dropped (echo requests when reply mode is off, plus every non-echo ICMP to the VIP).", []string{"instance"}, nil), prometheus.CounterValue, float64(s.L4lbEbpfIcmpDroppedTotal), s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstHistogram(prometheus.NewDesc("ksdk_l4lb_ebpf_packet_size_histogram", "L4LB eBPF Packet Size Histogram", []string{"instance"}, nil), uint64(s.PacketSizeDistribution.Count), float64(s.PacketSizeDistribution.Sum), s.PacketSizeDistribution.Histogram, s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		ch <- prometheus.MustNewConstHistogram(prometheus.NewDesc("ksdk_l4lb_ebpf_isn_least_significant_byte_histogram", "L4LB eBPF ISN Least Significant Byte Histogram", []string{"instance"}, nil), uint64(s.ISNLeastSignificantByteDistribution.Count), float64(s.ISNLeastSignificantByteDistribution.Sum), s.ISNLeastSignificantByteDistribution.Histogram, s.CommonName)
	}
	if s.L4lbEbpfEnabled {
		for ip, protoMap := range s.SourceIPPacketCount.Map {
			for proto, ports := range protoMap {
				for port, count := range ports {
					ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_l4lb_ebpf_src_ip_map", "L4LB eBPF Packet per Source IP and Protocol", []string{"instance", "src_ip", "protocol", "port"}, nil), prometheus.CounterValue, float64(count), s.CommonName, ip.String(), proto.String(), fmt.Sprintf("%d", port))
				}
			}
		}

	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_requests_total", "Popcache metric requests_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.PopcacheRequestsTotal), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_requests_end_total", "Popcache metric requests_end_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.PopcacheRequestsEndTotal), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_connect_total", "Popcache metric connect_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.PopcacheConnectTotal), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_cache_hits_total", "Popcache metric cache_hits_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.PopcacheCacheHitsTotal), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_cache_misses_total", "Popcache metric cache_misses_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.PopcacheCacheMissesTotal), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_close_total", "Popcache metric close_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.PopcacheCloseTotal), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_hijacked_total", "Popcache metric hijacked_total", []string{"instance"}, nil), prometheus.CounterValue, float64(s.PopcacheHijackedTotal), s.CommonName)
	}
	if s.PopcacheEnabled {
		for i, v := range s.PopcachePerMethodTotal {
			ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_per_method_total", "Popcache metric per_method_total", []string{"instance", "method"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
				switch i {
				case 0:
					return "GET"
				case 1:
					return "HEAD"
				case 2:
					return "POST"
				case 3:
					return "PUT"
				case 4:
					return "DELETE"
				case 5:
					return "PATCH"
				case 6:
					return "OPTIONS"
				case 7:
					return "TRACE"
				case 8:
					return "CONNECT"
				case 9:
					return "OTHER"
				default:
					return "unknown"
				}
			}())
		}
	}
	if s.PopcacheEnabled {
		for i, v := range s.PopcachePerProtocolTotal {
			ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_per_protocol_total", "Popcache metric per_protocol_total", []string{"instance", "protocol"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
				switch i {
				case 0:
					return "HTTP1.0(plain)"
				case 1:
					return "HTTP1.0"
				case 2:
					return "HTTP1.1(plain)"
				case 3:
					return "HTTP1.1"
				case 4:
					return "HTTP2"
				case 5:
					return "HTTP3"
				case 6:
					return "OTHER(plain)"
				case 7:
					return "OTHER"
				default:
					return "unknown"
				}
			}())
		}
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_http_port", "Popcache metric http_port", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.PopcacheHttpPort), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_https_port", "Popcache metric https_port", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.PopcacheHttpsPort), s.CommonName)
	}
	if s.PopcacheEnabled {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_popcache_http3_port", "Popcache metric http3_port", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.PopcacheHttp3Port), s.CommonName)
	}
	for i, v := range s.CpuUsages {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_cpu_usage_percentage", "CPU usage percentage", []string{"instance", "core"}, nil), prometheus.GaugeValue, v, s.CommonName, fmt.Sprintf("cpu%d", i))
	}
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_memory_usage_bytes", "Memory usage in bytes", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.MemoryUsage), s.CommonName)
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_disk_usage_bytes", "Disk usage in bytes", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.DiskUsage), s.CommonName)
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_disk_swap_percentage", "Disk swap usage percentage", []string{"instance"}, nil), prometheus.GaugeValue, s.DiskSwap, s.CommonName)
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_server_uptime_seconds", "Server uptime in seconds", []string{"instance"}, nil), prometheus.GaugeValue, s.ServerUptime, s.CommonName)
	for i, v := range s.LoadAvg {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_load_average", "Load average over 1, 5, and 15 minutes", []string{"instance", "interval"}, nil), prometheus.GaugeValue, v, s.CommonName, func() string {
			switch i {
			case 0:
				return "1min"
			case 1:
				return "5min"
			case 2:
				return "15min"
			default:
				return "unknown"
			}
		}())
	}
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_memory_total_bytes", "Total memory in bytes", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.MemoryTotal), s.CommonName)
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_disk_total_bytes", "Total disk size in bytes", []string{"instance"}, nil), prometheus.GaugeValue, float64(s.DiskTotal), s.CommonName)
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_rtt_to_control_plane_microseconds", "Round-trip time to control plane in microseconds", []string{"instance"}, nil), prometheus.GaugeValue, s.RTT, s.CommonName)
	ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_app_status", "Application status", []string{"instance"}, nil), prometheus.GaugeValue, s.AppStatus, s.CommonName)
	for i, v := range s.TemperatureCelsius {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_tempature_celsius", "Temperature in Celsius", []string{"instance", "sensor_key"}, nil), prometheus.GaugeValue, v, s.CommonName, func() string {
			if s.TemperatureSensorKeys != nil && i < len(s.TemperatureSensorKeys) {
				return s.TemperatureSensorKeys[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.RxBytes {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_rx_bytes_total", "Total received bytes on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.TxBytes {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_tx_bytes_total", "Total transmitted bytes on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.RxPackets {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_rx_packets_total", "Total received packets on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.TxPackets {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_tx_packets_total", "Total transmitted packets on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.RxErrors {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_rx_errors_total", "Total receive errors on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.TxErrors {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_tx_errors_total", "Total transmit errors on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.RxDrops {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_rx_drops_total", "Total received drops on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
	for i, v := range s.TxDrops {
		ch <- prometheus.MustNewConstMetric(prometheus.NewDesc("ksdk_network_interface_tx_drops_total", "Total transmitted drops on network interfaces", []string{"instance", "interface"}, nil), prometheus.CounterValue, float64(v), s.CommonName, func() string {
			if i < len(s.Interfaces) {
				return s.Interfaces[i]
			} else {
				return "unknown"
			}
		}())
	}
}
