// Code generated by script/metrics.py. DO NOT EDIT.

package stat

import (
	"bytes"
	"encoding/binary"
	"net"
	"net/netip"
	"time"
	"unsafe"

	"github.com/on-keyday/kscale/consts"
	"github.com/on-keyday/kscale/dns/dnsmetrics"
	"github.com/on-keyday/kscale/l4lb/l4lbdrv"
	"github.com/on-keyday/kscale/popcache/popmetrics"
	pbstat "github.com/on-keyday/kscale/protobuf/proto/stat"
	"github.com/on-keyday/objtrsf/objproto"
)

var _ = bytes.NewReader
var _ = binary.LittleEndian
var _ = net.HardwareAddr(nil)
var _ = netip.Addr{}
var _ = time.Duration(0)
var _ = unsafe.Sizeof(byte(0))
var _ = consts.AppStatus(0)
var _ = dnsmetrics.DNSMetrics{}
var _ = l4lbdrv.StatCounters{}
var _ = popmetrics.PoPMetrics{}
var _ = objproto.ConnectionID{}

func (s *L4lbStat) ToProto() *pbstat.L4LbStat {
	out := &pbstat.L4LbStat{}
	out.SrcIps = l4lbdrv.SrcIPCountToBytes(s.SourceIPPacketCount.Map)
	out.PacketSizes = l4lbdrv.PacketSizeDistToBytes(s.PacketSizeDistribution.Map)
	out.IsnLeastSignificantBytes = l4lbdrv.ISNLeastSignificantByteMapToBytes(s.ISNLeastSignificantByteDistribution.Map)
	{
		var w [unsafe.Sizeof(l4lbdrv.StatCounters{})]byte
		binary.Encode(w[:], binary.LittleEndian, s.EbpfStats)
		out.EbpfStats = w[:]
	}
	return out
}

func (s *L4lbStat) FromProto(in *pbstat.L4LbStat) {
	if in == nil {
		return
	}
	if v, err := l4lbdrv.SrcIPCountFromBytes(in.SrcIps); err == nil && v != nil {
		s.SourceIPPacketCount = *v
	}
	if v, err := l4lbdrv.PacketSizeDistFromBytes(in.PacketSizes); err == nil && v != nil {
		s.PacketSizeDistribution = *v
	}
	if v, err := l4lbdrv.ISNLeastSignificantByteMapFromBytes(in.IsnLeastSignificantBytes); err == nil && v != nil {
		s.ISNLeastSignificantByteDistribution = *v
	}
	{
		var res l4lbdrv.StatCounters
		binary.Read(bytes.NewReader(in.EbpfStats), binary.LittleEndian, &res)
		s.EbpfStats = res
	}
}

func (s *ConnectionStat) ToProto() *pbstat.ConnectionStat {
	out := &pbstat.ConnectionStat{}
	out.ConnId = s.ConnID.String()
	out.Rtt = int64(s.RTT)
	return out
}

func (s *ConnectionStat) FromProto(in *pbstat.ConnectionStat) {
	if in == nil {
		return
	}
	if v, err := objproto.ParseConnectionID(in.ConnId, 0); err == nil {
		s.ConnID = v
	}
	s.RTT = time.Duration(in.Rtt)
}

func (s *HostSpecStat) ToProto() *pbstat.HostSpecStat {
	out := &pbstat.HostSpecStat{}
	out.CpuCount = s.CpuCount
	out.MemoryTotal = s.MemoryTotal
	out.DiskTotal = s.DiskTotal
	out.KernelVersion = s.KernelVersion
	out.Os = s.Os
	out.Platform = s.Platform
	out.PlatformVer = s.PlatformVer
	out.Arch = s.Arch
	return out
}

func (s *HostSpecStat) FromProto(in *pbstat.HostSpecStat) {
	if in == nil {
		return
	}
	s.CpuCount = in.CpuCount
	s.MemoryTotal = in.MemoryTotal
	s.DiskTotal = in.DiskTotal
	s.KernelVersion = in.KernelVersion
	s.Os = in.Os
	s.Platform = in.Platform
	s.PlatformVer = in.PlatformVer
	s.Arch = in.Arch
}

func (s *HostRealtimeStat) ToProto() *pbstat.HostRealtimeStat {
	out := &pbstat.HostRealtimeStat{}
	out.CpuUsages = append([]float64(nil), s.CpuUsages...)
	out.MemoryUsage = s.MemoryUsage
	out.DiskSwap = s.DiskSwap
	out.DiskUsage = s.DiskUsage
	out.HostUptime = s.HostUptime
	out.ServerUptime = int64(s.ServerUptime)
	out.LoadAvg = append([]float64(nil), s.LoadAvg[:]...)
	return out
}

func (s *HostRealtimeStat) FromProto(in *pbstat.HostRealtimeStat) {
	if in == nil {
		return
	}
	s.CpuUsages = append([]float64(nil), in.CpuUsages...)
	s.MemoryUsage = in.MemoryUsage
	s.DiskSwap = in.DiskSwap
	s.DiskUsage = in.DiskUsage
	s.HostUptime = in.HostUptime
	s.ServerUptime = time.Duration(in.ServerUptime)
	{
		var arr [3]float64
		copy(arr[:], in.LoadAvg)
		s.LoadAvg = arr
	}
}

func (s *NetworkSpecStat) ToProto() *pbstat.NetworkSpecStat {
	out := &pbstat.NetworkSpecStat{}
	{
		tmp := make([]*pbstat.InterfaceSpecStat, len(s.Interfaces))
		for i := range s.Interfaces {
			tmp[i] = s.Interfaces[i].ToProto()
		}
		out.Interfaces = tmp
	}
	return out
}

func (s *NetworkSpecStat) FromProto(in *pbstat.NetworkSpecStat) {
	if in == nil {
		return
	}
	{
		tmp := make([]InterfaceSpecStat, len(in.Interfaces))
		for i := range in.Interfaces {
			if in.Interfaces[i] != nil {
				tmp[i].FromProto(in.Interfaces[i])
			}
		}
		s.Interfaces = tmp
	}
}

func (s *InterfaceSpecStat) ToProto() *pbstat.InterfaceSpecStat {
	out := &pbstat.InterfaceSpecStat{}
	out.Name = s.Name
	out.Mtu = s.MTU
	out.Mac = s.Mac.String()
	out.Flags = uint32(s.Flags)
	{
		tmp := make([]string, len(s.IPs))
		for i, v := range s.IPs {
			tmp[i] = v.String()
		}
		out.Ips = tmp
	}
	return out
}

func (s *InterfaceSpecStat) FromProto(in *pbstat.InterfaceSpecStat) {
	if in == nil {
		return
	}
	s.Name = in.Name
	s.MTU = in.Mtu
	s.Mac, _ = net.ParseMAC(in.Mac)
	s.Flags = net.Flags(in.Flags)
	{
		tmp := make([]netip.Prefix, len(in.Ips))
		for i, v := range in.Ips {
			tmp[i], _ = netip.ParsePrefix(v)
		}
		s.IPs = tmp
	}
}

func (s *NetworkRealtimeStat) ToProto() *pbstat.NetworkRealtimeStat {
	out := &pbstat.NetworkRealtimeStat{}
	out.RxBytes = append([]uint64(nil), s.RxBytes...)
	out.TxBytes = append([]uint64(nil), s.TxBytes...)
	out.RxPackets = append([]uint64(nil), s.RxPackets...)
	out.TxPackets = append([]uint64(nil), s.TxPackets...)
	out.RxErrors = append([]uint64(nil), s.RxErrors...)
	out.TxErrors = append([]uint64(nil), s.TxErrors...)
	out.RxDrops = append([]uint64(nil), s.RxDrops...)
	out.TxDrops = append([]uint64(nil), s.TxDrops...)
	return out
}

func (s *NetworkRealtimeStat) FromProto(in *pbstat.NetworkRealtimeStat) {
	if in == nil {
		return
	}
	s.RxBytes = append([]uint64(nil), in.RxBytes...)
	s.TxBytes = append([]uint64(nil), in.TxBytes...)
	s.RxPackets = append([]uint64(nil), in.RxPackets...)
	s.TxPackets = append([]uint64(nil), in.TxPackets...)
	s.RxErrors = append([]uint64(nil), in.RxErrors...)
	s.TxErrors = append([]uint64(nil), in.TxErrors...)
	s.RxDrops = append([]uint64(nil), in.RxDrops...)
	s.TxDrops = append([]uint64(nil), in.TxDrops...)
}

func (s *CdnAppRealtimeStat) ToProto() *pbstat.CdnAppRealtimeStat {
	out := &pbstat.CdnAppRealtimeStat{}
	{
		items := make([]string, len(s.Vip))
		for i, v := range s.Vip {
			items[i] = v.String()
		}
		out.Vip = &pbstat.StringList{Items: items}
	}
	out.BoundIfaces = &pbstat.StringList{Items: append([]string(nil), s.BoundInterfaces...)}
	{
		tmp := uint32(s.AppStatus)
		out.Appstat = &tmp
	}
	{
		tmp := s.LoadBalancerID
		out.LbId = &tmp
	}
	return out
}

func (s *CdnAppRealtimeStat) FromProto(in *pbstat.CdnAppRealtimeStat) {
	if in == nil {
		return
	}
	if in.Vip != nil {
		tmp := make([]netip.Addr, len(in.Vip.Items))
		for i, v := range in.Vip.Items {
			tmp[i], _ = netip.ParseAddr(v)
		}
		s.Vip = tmp
	}
	if in.BoundIfaces != nil {
		s.BoundInterfaces = append([]string(nil), in.BoundIfaces.Items...)
	}
	if in.Appstat != nil {
		s.AppStatus = consts.AppStatus(*in.Appstat)
	}
	if in.LbId != nil {
		s.LoadBalancerID = *in.LbId
	}
}

func (s *PopcacheStat) ToProto() *pbstat.PopcacheStat {
	out := &pbstat.PopcacheStat{}
	out.RequestsTotal = s.PopcacheStats.RequestsTotal
	out.RequestsEndTotal = s.PopcacheStats.RequestsEndTotal
	out.ConnectTotal = s.PopcacheStats.ConnectTotal
	out.CacheHitsTotal = s.PopcacheStats.CacheHitsTotal
	out.CacheMissesTotal = s.PopcacheStats.CacheMissesTotal
	out.CloseTotal = s.PopcacheStats.CloseTotal
	out.HijackedTotal = s.PopcacheStats.HijackedTotal
	out.PerMethodTotalGet = s.PopcacheStats.PerMethodTotalGet
	out.PerMethodTotalHead = s.PopcacheStats.PerMethodTotalHead
	out.PerMethodTotalPost = s.PopcacheStats.PerMethodTotalPost
	out.PerMethodTotalPut = s.PopcacheStats.PerMethodTotalPut
	out.PerMethodTotalDelete = s.PopcacheStats.PerMethodTotalDelete
	out.PerMethodTotalPatch = s.PopcacheStats.PerMethodTotalPatch
	out.PerMethodTotalOptions = s.PopcacheStats.PerMethodTotalOptions
	out.PerMethodTotalTrace = s.PopcacheStats.PerMethodTotalTrace
	out.PerMethodTotalConnect = s.PopcacheStats.PerMethodTotalConnect
	out.PerMethodTotalOther = s.PopcacheStats.PerMethodTotalOther
	out.PerProtocolTotalHttp10Plain = s.PopcacheStats.PerProtocolTotalHttp10Plain
	out.PerProtocolTotalHttp10 = s.PopcacheStats.PerProtocolTotalHttp10
	out.PerProtocolTotalHttp11Plain = s.PopcacheStats.PerProtocolTotalHttp11Plain
	out.PerProtocolTotalHttp11 = s.PopcacheStats.PerProtocolTotalHttp11
	out.PerProtocolTotalHttp2 = s.PopcacheStats.PerProtocolTotalHttp2
	out.PerProtocolTotalHttp3 = s.PopcacheStats.PerProtocolTotalHttp3
	out.PerProtocolTotalOtherPlain = s.PopcacheStats.PerProtocolTotalOtherPlain
	out.PerProtocolTotalOther = s.PopcacheStats.PerProtocolTotalOther
	out.HttpPort = s.PopcacheStats.HttpPort
	out.HttpsPort = s.PopcacheStats.HttpsPort
	out.Http3Port = s.PopcacheStats.Http3Port
	return out
}

func (s *PopcacheStat) FromProto(in *pbstat.PopcacheStat) {
	if in == nil {
		return
	}
	s.PopcacheStats.RequestsTotal = in.RequestsTotal
	s.PopcacheStats.RequestsEndTotal = in.RequestsEndTotal
	s.PopcacheStats.ConnectTotal = in.ConnectTotal
	s.PopcacheStats.CacheHitsTotal = in.CacheHitsTotal
	s.PopcacheStats.CacheMissesTotal = in.CacheMissesTotal
	s.PopcacheStats.CloseTotal = in.CloseTotal
	s.PopcacheStats.HijackedTotal = in.HijackedTotal
	s.PopcacheStats.PerMethodTotalGet = in.PerMethodTotalGet
	s.PopcacheStats.PerMethodTotalHead = in.PerMethodTotalHead
	s.PopcacheStats.PerMethodTotalPost = in.PerMethodTotalPost
	s.PopcacheStats.PerMethodTotalPut = in.PerMethodTotalPut
	s.PopcacheStats.PerMethodTotalDelete = in.PerMethodTotalDelete
	s.PopcacheStats.PerMethodTotalPatch = in.PerMethodTotalPatch
	s.PopcacheStats.PerMethodTotalOptions = in.PerMethodTotalOptions
	s.PopcacheStats.PerMethodTotalTrace = in.PerMethodTotalTrace
	s.PopcacheStats.PerMethodTotalConnect = in.PerMethodTotalConnect
	s.PopcacheStats.PerMethodTotalOther = in.PerMethodTotalOther
	s.PopcacheStats.PerProtocolTotalHttp10Plain = in.PerProtocolTotalHttp10Plain
	s.PopcacheStats.PerProtocolTotalHttp10 = in.PerProtocolTotalHttp10
	s.PopcacheStats.PerProtocolTotalHttp11Plain = in.PerProtocolTotalHttp11Plain
	s.PopcacheStats.PerProtocolTotalHttp11 = in.PerProtocolTotalHttp11
	s.PopcacheStats.PerProtocolTotalHttp2 = in.PerProtocolTotalHttp2
	s.PopcacheStats.PerProtocolTotalHttp3 = in.PerProtocolTotalHttp3
	s.PopcacheStats.PerProtocolTotalOtherPlain = in.PerProtocolTotalOtherPlain
	s.PopcacheStats.PerProtocolTotalOther = in.PerProtocolTotalOther
	s.PopcacheStats.HttpPort = in.HttpPort
	s.PopcacheStats.HttpsPort = in.HttpsPort
	s.PopcacheStats.Http3Port = in.Http3Port
}

func (s *DnsStat) ToProto() *pbstat.DnsStat {
	out := &pbstat.DnsStat{}
	out.DnsPort = s.DnsStats.DnsPort
	out.RequestsTotal = s.DnsStats.RequestsTotal
	out.ResponsesTotal = s.DnsStats.ResponsesTotal
	out.ErrorsTotal = s.DnsStats.ErrorsTotal
	return out
}

func (s *DnsStat) FromProto(in *pbstat.DnsStat) {
	if in == nil {
		return
	}
	s.DnsStats.DnsPort = in.DnsPort
	s.DnsStats.RequestsTotal = in.RequestsTotal
	s.DnsStats.ResponsesTotal = in.ResponsesTotal
	s.DnsStats.ErrorsTotal = in.ErrorsTotal
}

func (s *CdnAppSpecStat) ToProto() *pbstat.CdnAppSpecStat {
	out := &pbstat.CdnAppSpecStat{}
	out.CommonName = s.CommonName
	return out
}

func (s *CdnAppSpecStat) FromProto(in *pbstat.CdnAppSpecStat) {
	if in == nil {
		return
	}
	s.CommonName = in.CommonName
}

func (s *HostPhysicalStat) ToProto() *pbstat.HostPhysicalStat {
	out := &pbstat.HostPhysicalStat{}
	out.TemperatureCelsius = append([]float64(nil), s.TemperatureCelsius...)
	out.TemperatureSensorKeys = append([]string(nil), s.TemperatureSensorKeys...)
	out.TemperatureCelsiusCritical = append([]float64(nil), s.TemperatureCelsiusCritical...)
	out.TemperatureCelsiusHigh = append([]float64(nil), s.TemperatureCelsiusHigh...)
	return out
}

func (s *HostPhysicalStat) FromProto(in *pbstat.HostPhysicalStat) {
	if in == nil {
		return
	}
	s.TemperatureCelsius = append([]float64(nil), in.TemperatureCelsius...)
	s.TemperatureSensorKeys = append([]string(nil), in.TemperatureSensorKeys...)
	s.TemperatureCelsiusCritical = append([]float64(nil), in.TemperatureCelsiusCritical...)
	s.TemperatureCelsiusHigh = append([]float64(nil), in.TemperatureCelsiusHigh...)
}

func (s *PopcacheSpecStat) ToProto() *pbstat.PopcacheSpecStat {
	out := &pbstat.PopcacheSpecStat{}
	out.OriginServerAddress = s.OriginServerAddress
	return out
}

func (s *PopcacheSpecStat) FromProto(in *pbstat.PopcacheSpecStat) {
	if in == nil {
		return
	}
	s.OriginServerAddress = in.OriginServerAddress
}

func (s *DnsSpecStat) ToProto() *pbstat.DnsSpecStat {
	out := &pbstat.DnsSpecStat{}
	out.ManagedDnsZones = append([]string(nil), s.ManagedDNSZones...)
	return out
}

func (s *DnsSpecStat) FromProto(in *pbstat.DnsSpecStat) {
	if in == nil {
		return
	}
	s.ManagedDNSZones = append([]string(nil), in.ManagedDnsZones...)
}
