// Code generated by kscale/access/generator. DO NOT EDIT.
package service

import (
	"context"
	"fmt"

	"github.com/on-keyday/kscale/access"
	"github.com/on-keyday/kscale/access/audit"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// CplaneFileGated is the generated ABAC gate for CplaneFileService. It implements the full
// pb.CplaneFileServiceServer surface as a decorator over Inner (the hand-written
// business): every method authorizes the caller against the resource policy
// (caller from the peer, $env.args from the request, $env.authority from the
// root) and then delegates to Inner. Registering this — never Inner directly —
// is what keeps the gate on every action.
type CplaneFileGated struct {
	Inner      pb.CplaneFileServiceServer
	Controller access.AccessController
	Resource   access.Resource
	Root       access.RootAuthority // supplies $env.authority
	Audit      audit.Audit
}

var _ pb.CplaneFileServiceServer = (*CplaneFileGated)(nil)

// authorize runs the ABAC gate for action using the caller carried by the
// peer and args exposed as $env.args.
func (s *CplaneFileGated) authorize(ctx context.Context, action string, args []access.Attribute) error {
	p := peer.GetPeer(ctx)
	if p == nil || p.Policy() == nil || p.Policy().User == nil {
		return fmt.Errorf("permission denied: unauthenticated caller")
	}
	envAttrs := []access.Attribute{access.NewAuthorityAttributeMapper(s.Root)}
	if len(args) > 0 {
		envAttrs = append(envAttrs, access.NewAttributeManager("args", args))
	}
	policyCtx := p.Policy().
		CollectResource(s.Resource).
		CollectEnvironment(access.NewEnvironment(envAttrs)).
		CollectAction(access.NewAction(action, nil)).
		Build(ctx, s.Audit)
	if err := s.Controller.CanAccess(policyCtx); err != nil {
		return fmt.Errorf("permission denied: %w", err)
	}
	return nil
}

func (s *CplaneFileGated) Upload(ctx context.Context, req *pbaccess.ResourceCplaneFileActionUploadArgsDTO) (*pbaccess.ResourceCplaneFileActionUploadResponseDTO, error) {
	if err := s.authorize(ctx, "upload", []access.Attribute{access.NewAttribute("file_name", req.FileName)}); err != nil {
		return nil, err
	}
	return s.Inner.Upload(ctx, req)
}

func (s *CplaneFileGated) List(ctx context.Context, req *pbaccess.ResourceCplaneFileActionListArgsDTO) (*pbaccess.ResourceCplaneFileActionListResponseDTO, error) {
	if err := s.authorize(ctx, "list", nil); err != nil {
		return nil, err
	}
	return s.Inner.List(ctx, req)
}

func (s *CplaneFileGated) Delete(ctx context.Context, req *pbaccess.ResourceCplaneFileActionDeleteArgsDTO) (*pbaccess.ResourceCplaneFileActionDeleteResponseDTO, error) {
	if err := s.authorize(ctx, "delete", []access.Attribute{access.NewAttribute("file_name", req.FileName)}); err != nil {
		return nil, err
	}
	return s.Inner.Delete(ctx, req)
}
