// Code generated by kscale/access/generator. DO NOT EDIT.
package service

import (
	"context"
	"fmt"

	"github.com/on-keyday/kscale/access"
	"github.com/on-keyday/kscale/access/audit"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// NodeFileGated is the generated ABAC gate for NodeFileService. It implements the full
// pb.NodeFileServiceServer surface as a decorator over Inner (the hand-written
// business): every method authorizes the caller against the resource policy
// (caller from the peer, $env.args from the request, $env.authority from the
// root) and then delegates to Inner. Registering this — never Inner directly —
// is what keeps the gate on every action.
type NodeFileGated struct {
	Inner      pb.NodeFileServiceServer
	Controller access.AccessController
	Resource   access.Resource
	Root       access.RootAuthority // supplies $env.authority
	Audit      audit.Audit
}

var _ pb.NodeFileServiceServer = (*NodeFileGated)(nil)

// authorize runs the ABAC gate for action using the caller carried by the
// peer and args exposed as $env.args.
func (s *NodeFileGated) authorize(ctx context.Context, action string, args []access.Attribute) error {
	p := peer.GetPeer(ctx)
	if p == nil || p.Policy() == nil || p.Policy().User == nil {
		return fmt.Errorf("permission denied: unauthenticated caller")
	}
	envAttrs := []access.Attribute{access.NewAuthorityAttributeMapper(s.Root)}
	if len(args) > 0 {
		envAttrs = append(envAttrs, access.NewAttributeManager("args", args))
	}
	policyCtx := p.Policy().
		CollectResource(s.Resource).
		CollectEnvironment(access.NewEnvironment(envAttrs)).
		CollectAction(access.NewAction(action, nil)).
		Build(ctx, s.Audit)
	if err := s.Controller.CanAccess(policyCtx); err != nil {
		return fmt.Errorf("permission denied: %w", err)
	}
	return nil
}

func (s *NodeFileGated) Apply(ctx context.Context, req *pbaccess.ResourceNodeFileActionApplyArgsDTO) (*pbaccess.ResourceNodeFileActionApplyResponseDTO, error) {
	if err := s.authorize(ctx, "apply", []access.Attribute{access.NewAttribute("name", req.Name), access.NewAttribute("node", req.Node), access.NewAttribute("save_as", req.SaveAs), access.NewAttribute("cplane_file", req.CplaneFile)}); err != nil {
		return nil, err
	}
	return s.Inner.Apply(ctx, req)
}

func (s *NodeFileGated) List(ctx context.Context, req *pbaccess.ResourceNodeFileActionListArgsDTO) (*pbaccess.ResourceNodeFileActionListResponseDTO, error) {
	if err := s.authorize(ctx, "list", nil); err != nil {
		return nil, err
	}
	return s.Inner.List(ctx, req)
}

func (s *NodeFileGated) Delete(ctx context.Context, req *pbaccess.ResourceNodeFileActionDeleteArgsDTO) (*pbaccess.ResourceNodeFileActionDeleteResponseDTO, error) {
	if err := s.authorize(ctx, "delete", []access.Attribute{access.NewAttribute("name", req.Name)}); err != nil {
		return nil, err
	}
	return s.Inner.Delete(ctx, req)
}

func (s *NodeFileGated) Get(ctx context.Context, req *pbaccess.ResourceNodeFileActionGetArgsDTO) (*pbaccess.ResourceNodeFileActionGetResponseDTO, error) {
	if err := s.authorize(ctx, "get", []access.Attribute{access.NewAttribute("name", req.Name)}); err != nil {
		return nil, err
	}
	return s.Inner.Get(ctx, req)
}
