// Code generated by kscale/access/generator. DO NOT EDIT.
package service

import (
	"context"
	"fmt"

	"github.com/on-keyday/kscale/access"
	"github.com/on-keyday/kscale/access/audit"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// PopcacheConfigGated is the generated ABAC gate for PopcacheConfigService. It implements the full
// pb.PopcacheConfigServiceServer surface as a decorator over Inner (the hand-written
// business): every method authorizes the caller against the resource policy
// (caller from the peer, $env.args from the request, $env.authority from the
// root) and then delegates to Inner. Registering this — never Inner directly —
// is what keeps the gate on every action.
type PopcacheConfigGated struct {
	Inner      pb.PopcacheConfigServiceServer
	Controller access.AccessController
	Resource   access.Resource
	Root       access.RootAuthority // supplies $env.authority
	Audit      audit.Audit
}

var _ pb.PopcacheConfigServiceServer = (*PopcacheConfigGated)(nil)

// authorize runs the ABAC gate for action using the caller carried by the
// peer and args exposed as $env.args.
func (s *PopcacheConfigGated) authorize(ctx context.Context, action string, args []access.Attribute) error {
	p := peer.GetPeer(ctx)
	if p == nil || p.Policy() == nil || p.Policy().User == nil {
		return fmt.Errorf("permission denied: unauthenticated caller")
	}
	envAttrs := []access.Attribute{access.NewAuthorityAttributeMapper(s.Root)}
	if len(args) > 0 {
		envAttrs = append(envAttrs, access.NewAttributeManager("args", args))
	}
	policyCtx := p.Policy().
		CollectResource(s.Resource).
		CollectEnvironment(access.NewEnvironment(envAttrs)).
		CollectAction(access.NewAction(action, nil)).
		Build(ctx, s.Audit)
	if err := s.Controller.CanAccess(policyCtx); err != nil {
		return fmt.Errorf("permission denied: %w", err)
	}
	return nil
}

func (s *PopcacheConfigGated) Apply(ctx context.Context, req *pbaccess.ResourcePopcacheConfigActionApplyArgsDTO) (*pbaccess.ResourcePopcacheConfigActionApplyResponseDTO, error) {
	if err := s.authorize(ctx, "apply", []access.Attribute{access.NewAttribute("name", req.Name), access.NewAttribute("origin", req.Origin), access.NewAttribute("http_port", int64(req.HttpPort)), access.NewAttribute("https_port", int64(req.HttpsPort)), access.NewAttribute("http3_port", int64(req.Http3Port)), access.NewAttribute("wasm_compute_default_ms", int64(req.WasmComputeDefaultMs)), access.NewAttribute("wasm_compute_max_ms", int64(req.WasmComputeMaxMs)), access.NewAttribute("cert_path", req.CertPath), access.NewAttribute("key_path", req.KeyPath)}); err != nil {
		return nil, err
	}
	return s.Inner.Apply(ctx, req)
}

func (s *PopcacheConfigGated) Get(ctx context.Context, req *pbaccess.ResourcePopcacheConfigActionGetArgsDTO) (*pbaccess.ResourcePopcacheConfigActionGetResponseDTO, error) {
	if err := s.authorize(ctx, "get", []access.Attribute{access.NewAttribute("name", req.Name)}); err != nil {
		return nil, err
	}
	return s.Inner.Get(ctx, req)
}

func (s *PopcacheConfigGated) List(ctx context.Context, req *pbaccess.ResourcePopcacheConfigActionListArgsDTO) (*pbaccess.ResourcePopcacheConfigActionListResponseDTO, error) {
	if err := s.authorize(ctx, "list", nil); err != nil {
		return nil, err
	}
	return s.Inner.List(ctx, req)
}
