// Code generated by kscale/access/generator. DO NOT EDIT.
package service

import (
	"github.com/on-keyday/kscale/access"
	"github.com/on-keyday/kscale/access/audit"
	"github.com/on-keyday/kscale/access/predefined"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	"github.com/on-keyday/kscale/rpc"
)

// GateDeps bundles the control-plane singletons shared by every gated
// service adapter, so a resource's registration is Register<R>(mgr, gd, inner).
type GateDeps struct {
	Controller access.AccessController
	Root       access.RootAuthority
	Audit      audit.Audit
	Resources  map[string]access.ResourceTemplate // predefined.ResourceMap()
}

// RegisterUserHierarchyAuthority wraps inner in UserHierarchyAuthorityGated (authz + audit) and registers it.
func RegisterUserHierarchyAuthority(mgr *rpc.RPCManager, gd GateDeps, inner pb.UserHierarchyAuthorityServiceServer) {
	pb.RegisterUserHierarchyAuthorityServiceServer(mgr, &UserHierarchyAuthorityGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceUserHierarchyAuthority],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterCertificate wraps inner in CertificateGated (authz + audit) and registers it.
func RegisterCertificate(mgr *rpc.RPCManager, gd GateDeps, inner pb.CertificateServiceServer) {
	pb.RegisterCertificateServiceServer(mgr, &CertificateGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceCertificate],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterLogs wraps inner in LogsGated (authz + audit) and registers it.
func RegisterLogs(mgr *rpc.RPCManager, gd GateDeps, inner pb.LogsServiceServer) {
	pb.RegisterLogsServiceServer(mgr, &LogsGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceLogs],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterMonitorChat wraps inner in MonitorChatGated (authz + audit) and registers it.
func RegisterMonitorChat(mgr *rpc.RPCManager, gd GateDeps, inner pb.MonitorChatServiceServer) {
	pb.RegisterMonitorChatServiceServer(mgr, &MonitorChatGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceMonitorChat],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterAcme wraps inner in AcmeGated (authz + audit) and registers it.
func RegisterAcme(mgr *rpc.RPCManager, gd GateDeps, inner pb.AcmeServiceServer) {
	pb.RegisterAcmeServiceServer(mgr, &AcmeGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceAcme],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterWasmModule wraps inner in WasmModuleGated (authz + audit) and registers it.
func RegisterWasmModule(mgr *rpc.RPCManager, gd GateDeps, inner pb.WasmModuleServiceServer) {
	pb.RegisterWasmModuleServiceServer(mgr, &WasmModuleGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceWasmModule],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterPopcacheConfig wraps inner in PopcacheConfigGated (authz + audit) and registers it.
func RegisterPopcacheConfig(mgr *rpc.RPCManager, gd GateDeps, inner pb.PopcacheConfigServiceServer) {
	pb.RegisterPopcacheConfigServiceServer(mgr, &PopcacheConfigGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourcePopcacheConfig],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterOpenPort wraps inner in OpenPortGated (authz + audit) and registers it.
func RegisterOpenPort(mgr *rpc.RPCManager, gd GateDeps, inner pb.OpenPortServiceServer) {
	pb.RegisterOpenPortServiceServer(mgr, &OpenPortGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceOpenPort],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterNodeFile wraps inner in NodeFileGated (authz + audit) and registers it.
func RegisterNodeFile(mgr *rpc.RPCManager, gd GateDeps, inner pb.NodeFileServiceServer) {
	pb.RegisterNodeFileServiceServer(mgr, &NodeFileGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceNodeFile],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterContainer wraps inner in ContainerGated (authz + audit) and registers it.
func RegisterContainer(mgr *rpc.RPCManager, gd GateDeps, inner pb.ContainerServiceServer) {
	pb.RegisterContainerServiceServer(mgr, &ContainerGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceContainer],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterL4LbObject wraps inner in L4LbObjectGated (authz + audit) and registers it.
func RegisterL4LbObject(mgr *rpc.RPCManager, gd GateDeps, inner pb.L4LbObjectServiceServer) {
	pb.RegisterL4LbObjectServiceServer(mgr, &L4LbObjectGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceL4LbObject],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterBootstrapToken wraps inner in BootstrapTokenGated (authz + audit) and registers it.
func RegisterBootstrapToken(mgr *rpc.RPCManager, gd GateDeps, inner pb.BootstrapTokenServiceServer) {
	pb.RegisterBootstrapTokenServiceServer(mgr, &BootstrapTokenGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceBootstrapToken],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterExpectedNode wraps inner in ExpectedNodeGated (authz + audit) and registers it.
func RegisterExpectedNode(mgr *rpc.RPCManager, gd GateDeps, inner pb.ExpectedNodeServiceServer) {
	pb.RegisterExpectedNodeServiceServer(mgr, &ExpectedNodeGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceExpectedNode],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterVip wraps inner in VipGated (authz + audit) and registers it.
func RegisterVip(mgr *rpc.RPCManager, gd GateDeps, inner pb.VipServiceServer) {
	pb.RegisterVipServiceServer(mgr, &VipGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceVip],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterInterface wraps inner in InterfaceGated (authz + audit) and registers it.
func RegisterInterface(mgr *rpc.RPCManager, gd GateDeps, inner pb.InterfaceServiceServer) {
	pb.RegisterInterfaceServiceServer(mgr, &InterfaceGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceInterface],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterRouterConfig wraps inner in RouterConfigGated (authz + audit) and registers it.
func RegisterRouterConfig(mgr *rpc.RPCManager, gd GateDeps, inner pb.RouterConfigServiceServer) {
	pb.RegisterRouterConfigServiceServer(mgr, &RouterConfigGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceRouterConfig],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterDnsConfig wraps inner in DnsConfigGated (authz + audit) and registers it.
func RegisterDnsConfig(mgr *rpc.RPCManager, gd GateDeps, inner pb.DnsConfigServiceServer) {
	pb.RegisterDnsConfigServiceServer(mgr, &DnsConfigGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceDnsConfig],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterMtu wraps inner in MtuGated (authz + audit) and registers it.
func RegisterMtu(mgr *rpc.RPCManager, gd GateDeps, inner pb.MtuServiceServer) {
	pb.RegisterMtuServiceServer(mgr, &MtuGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceMtu],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterSecret wraps inner in SecretGated (authz + audit) and registers it.
func RegisterSecret(mgr *rpc.RPCManager, gd GateDeps, inner pb.SecretServiceServer) {
	pb.RegisterSecretServiceServer(mgr, &SecretGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceSecret],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterDataplaneNode wraps inner in DataplaneNodeGated (authz + audit) and registers it.
func RegisterDataplaneNode(mgr *rpc.RPCManager, gd GateDeps, inner pb.DataplaneNodeServiceServer) {
	pb.RegisterDataplaneNodeServiceServer(mgr, &DataplaneNodeGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceDataplaneNode],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterConnection wraps inner in ConnectionGated (authz + audit) and registers it.
func RegisterConnection(mgr *rpc.RPCManager, gd GateDeps, inner pb.ConnectionServiceServer) {
	pb.RegisterConnectionServiceServer(mgr, &ConnectionGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceConnection],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterAlert wraps inner in AlertGated (authz + audit) and registers it.
func RegisterAlert(mgr *rpc.RPCManager, gd GateDeps, inner pb.AlertServiceServer) {
	pb.RegisterAlertServiceServer(mgr, &AlertGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceAlert],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterCplaneFile wraps inner in CplaneFileGated (authz + audit) and registers it.
func RegisterCplaneFile(mgr *rpc.RPCManager, gd GateDeps, inner pb.CplaneFileServiceServer) {
	pb.RegisterCplaneFileServiceServer(mgr, &CplaneFileGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceCplaneFile],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterDpFile wraps inner in DpFileGated (authz + audit) and registers it.
func RegisterDpFile(mgr *rpc.RPCManager, gd GateDeps, inner pb.DpFileServiceServer) {
	pb.RegisterDpFileServiceServer(mgr, &DpFileGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceDpFile],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}

// RegisterStats wraps inner in StatsGated (authz + audit) and registers it.
func RegisterStats(mgr *rpc.RPCManager, gd GateDeps, inner pb.StatsServiceServer) {
	pb.RegisterStatsServiceServer(mgr, &StatsGated{
		Inner:      inner,
		Controller: gd.Controller,
		Resource:   gd.Resources[predefined.ResourceStats],
		Root:       gd.Root,
		Audit:      gd.Audit,
	})
}
