// Code generated by ksdk/script/access_compare.py. DO NOT EDIT.
package policy_test

import (
	"testing"

	"github.com/on-keyday/kscale/access/policy"
)

func TestJSONUnmarshalRejectsMissingFields(t *testing.T) {
	var nilGC *policy.GenericCondition = nil
	err := nilGC.UnmarshalJSON([]byte(`{"op":"StringEquals","condition":{"value":"test"}}`))
	if err == nil {
		t.Errorf("expected error for nil GenericCondition, got none")
	}
	gc := &policy.GenericCondition{}
	err = gc.UnmarshalJSON([]byte(`invalid json`))
	if err == nil {
		t.Errorf("expected error for invalid json, got none")
	}
	err = gc.UnmarshalJSON([]byte(`{"op":"UnknownOp","condition":{}}`))
	if err == nil {
		t.Errorf("expected error for unknown operation, got none")
	}
	type TestCase struct {
		Op       string
		TestJSON string
		Success  bool
	}
	var testCases = []TestCase{
		{
			Op:       policy.OpStringEquals,
			TestJSON: `{"op":"StringEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringEquals,
			TestJSON: `{"op":"StringEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringEquals,
			TestJSON: `{"op":"StringEquals", "condition": {"value": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringNotEquals,
			TestJSON: `{"op":"StringNotEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringNotEquals,
			TestJSON: `{"op":"StringNotEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringNotEquals,
			TestJSON: `{"op":"StringNotEquals", "condition": {"value": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringPrefix,
			TestJSON: `{"op":"StringPrefix"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringPrefix,
			TestJSON: `{"op":"StringPrefix","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringPrefix,
			TestJSON: `{"op":"StringPrefix", "condition": {"prefix": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringSuffix,
			TestJSON: `{"op":"StringSuffix"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringSuffix,
			TestJSON: `{"op":"StringSuffix","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringSuffix,
			TestJSON: `{"op":"StringSuffix", "condition": {"suffix": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringContains,
			TestJSON: `{"op":"StringContains"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringContains,
			TestJSON: `{"op":"StringContains","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringContains,
			TestJSON: `{"op":"StringContains", "condition": {"substr": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringGlob,
			TestJSON: `{"op":"StringGlob"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringGlob,
			TestJSON: `{"op":"StringGlob","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringGlob,
			TestJSON: `{"op":"StringGlob", "condition": {"pattern": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringRegex,
			TestJSON: `{"op":"StringRegex"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringRegex,
			TestJSON: `{"op":"StringRegex","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringRegex,
			TestJSON: `{"op":"StringRegex", "condition": {"pattern": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNumericEquals,
			TestJSON: `{"op":"NumericEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericEquals,
			TestJSON: `{"op":"NumericEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericEquals,
			TestJSON: `{"op":"NumericEquals", "condition": {"value": 123.45} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNumericNotEquals,
			TestJSON: `{"op":"NumericNotEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericNotEquals,
			TestJSON: `{"op":"NumericNotEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericNotEquals,
			TestJSON: `{"op":"NumericNotEquals", "condition": {"value": 123.45} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNumericGreaterThan,
			TestJSON: `{"op":"NumericGreaterThan"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericGreaterThan,
			TestJSON: `{"op":"NumericGreaterThan","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericGreaterThan,
			TestJSON: `{"op":"NumericGreaterThan", "condition": {"threshold": 123.45} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNumericGreaterThanOrEqual,
			TestJSON: `{"op":"NumericGreaterThanOrEqual"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericGreaterThanOrEqual,
			TestJSON: `{"op":"NumericGreaterThanOrEqual","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericGreaterThanOrEqual,
			TestJSON: `{"op":"NumericGreaterThanOrEqual", "condition": {"threshold": 123.45} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNumericLessThan,
			TestJSON: `{"op":"NumericLessThan"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericLessThan,
			TestJSON: `{"op":"NumericLessThan","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericLessThan,
			TestJSON: `{"op":"NumericLessThan", "condition": {"threshold": 123.45} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNumericLessThanOrEqual,
			TestJSON: `{"op":"NumericLessThanOrEqual"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericLessThanOrEqual,
			TestJSON: `{"op":"NumericLessThanOrEqual","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericLessThanOrEqual,
			TestJSON: `{"op":"NumericLessThanOrEqual", "condition": {"threshold": 123.45} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNumericBetween,
			TestJSON: `{"op":"NumericBetween"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericBetween,
			TestJSON: `{"op":"NumericBetween","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericBetween,
			TestJSON: `{"op":"NumericBetween", "condition": {"min": 123.45} }`,
			Success:  false,
		},
		{
			Op:       policy.OpNumericBetween,
			TestJSON: `{"op":"NumericBetween", "condition": {"min": 123.45, "max": 123.45} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIntegerEquals,
			TestJSON: `{"op":"IntegerEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerEquals,
			TestJSON: `{"op":"IntegerEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerEquals,
			TestJSON: `{"op":"IntegerEquals", "condition": {"value": 123} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIntegerNotEquals,
			TestJSON: `{"op":"IntegerNotEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerNotEquals,
			TestJSON: `{"op":"IntegerNotEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerNotEquals,
			TestJSON: `{"op":"IntegerNotEquals", "condition": {"value": 123} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIntegerGreaterThan,
			TestJSON: `{"op":"IntegerGreaterThan"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerGreaterThan,
			TestJSON: `{"op":"IntegerGreaterThan","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerGreaterThan,
			TestJSON: `{"op":"IntegerGreaterThan", "condition": {"threshold": 123} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIntegerGreaterThanOrEqual,
			TestJSON: `{"op":"IntegerGreaterThanOrEqual"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerGreaterThanOrEqual,
			TestJSON: `{"op":"IntegerGreaterThanOrEqual","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerGreaterThanOrEqual,
			TestJSON: `{"op":"IntegerGreaterThanOrEqual", "condition": {"threshold": 123} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIntegerLessThan,
			TestJSON: `{"op":"IntegerLessThan"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerLessThan,
			TestJSON: `{"op":"IntegerLessThan","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerLessThan,
			TestJSON: `{"op":"IntegerLessThan", "condition": {"threshold": 123} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIntegerLessThanOrEqual,
			TestJSON: `{"op":"IntegerLessThanOrEqual"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerLessThanOrEqual,
			TestJSON: `{"op":"IntegerLessThanOrEqual","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerLessThanOrEqual,
			TestJSON: `{"op":"IntegerLessThanOrEqual", "condition": {"threshold": 123} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIntegerBetween,
			TestJSON: `{"op":"IntegerBetween"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerBetween,
			TestJSON: `{"op":"IntegerBetween","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerBetween,
			TestJSON: `{"op":"IntegerBetween", "condition": {"min": 123} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIntegerBetween,
			TestJSON: `{"op":"IntegerBetween", "condition": {"min": 123, "max": 123} }`,
			Success:  true,
		},
		{
			Op:       policy.OpDurationEquals,
			TestJSON: `{"op":"DurationEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationEquals,
			TestJSON: `{"op":"DurationEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationEquals,
			TestJSON: `{"op":"DurationEquals", "condition": {"duration": "1h30m"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpDurationNotEquals,
			TestJSON: `{"op":"DurationNotEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationNotEquals,
			TestJSON: `{"op":"DurationNotEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationNotEquals,
			TestJSON: `{"op":"DurationNotEquals", "condition": {"duration": "1h30m"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpDurationLessThan,
			TestJSON: `{"op":"DurationLessThan"}`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationLessThan,
			TestJSON: `{"op":"DurationLessThan","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationLessThan,
			TestJSON: `{"op":"DurationLessThan", "condition": {"duration": "1h30m"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpDurationLessThanOrEqual,
			TestJSON: `{"op":"DurationLessThanOrEqual"}`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationLessThanOrEqual,
			TestJSON: `{"op":"DurationLessThanOrEqual","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationLessThanOrEqual,
			TestJSON: `{"op":"DurationLessThanOrEqual", "condition": {"duration": "1h30m"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpDurationGreaterThan,
			TestJSON: `{"op":"DurationGreaterThan"}`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationGreaterThan,
			TestJSON: `{"op":"DurationGreaterThan","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationGreaterThan,
			TestJSON: `{"op":"DurationGreaterThan", "condition": {"duration": "1h30m"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpDurationGreaterThanOrEqual,
			TestJSON: `{"op":"DurationGreaterThanOrEqual"}`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationGreaterThanOrEqual,
			TestJSON: `{"op":"DurationGreaterThanOrEqual","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationGreaterThanOrEqual,
			TestJSON: `{"op":"DurationGreaterThanOrEqual", "condition": {"duration": "1h30m"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpDurationBetween,
			TestJSON: `{"op":"DurationBetween"}`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationBetween,
			TestJSON: `{"op":"DurationBetween","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationBetween,
			TestJSON: `{"op":"DurationBetween", "condition": {"min": "1h30m"} }`,
			Success:  false,
		},
		{
			Op:       policy.OpDurationBetween,
			TestJSON: `{"op":"DurationBetween", "condition": {"min": "1h30m", "max": "1h30m"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpTimeEquals,
			TestJSON: `{"op":"TimeEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeEquals,
			TestJSON: `{"op":"TimeEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeEquals,
			TestJSON: `{"op":"TimeEquals", "condition": {"time": "2024-01-01T12:00:00Z"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpTimeNotEquals,
			TestJSON: `{"op":"TimeNotEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeNotEquals,
			TestJSON: `{"op":"TimeNotEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeNotEquals,
			TestJSON: `{"op":"TimeNotEquals", "condition": {"time": "2024-01-01T12:00:00Z"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpTimeBefore,
			TestJSON: `{"op":"TimeBefore"}`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeBefore,
			TestJSON: `{"op":"TimeBefore","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeBefore,
			TestJSON: `{"op":"TimeBefore", "condition": {"time": "2024-01-01T12:00:00Z"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpTimeAfter,
			TestJSON: `{"op":"TimeAfter"}`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeAfter,
			TestJSON: `{"op":"TimeAfter","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeAfter,
			TestJSON: `{"op":"TimeAfter", "condition": {"time": "2024-01-01T12:00:00Z"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpTimeBetween,
			TestJSON: `{"op":"TimeBetween"}`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeBetween,
			TestJSON: `{"op":"TimeBetween","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeBetween,
			TestJSON: `{"op":"TimeBetween", "condition": {"start": "2024-01-01T12:00:00Z"} }`,
			Success:  false,
		},
		{
			Op:       policy.OpTimeBetween,
			TestJSON: `{"op":"TimeBetween", "condition": {"start": "2024-01-01T12:00:00Z", "end": "2024-01-01T12:00:00Z"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringListContains,
			TestJSON: `{"op":"StringListContains"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringListContains,
			TestJSON: `{"op":"StringListContains","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringListContains,
			TestJSON: `{"op":"StringListContains", "condition": {"item": "testvalue"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringInList,
			TestJSON: `{"op":"StringInList"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringInList,
			TestJSON: `{"op":"StringInList","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringInList,
			TestJSON: `{"op":"StringInList", "condition": {"allowedList": ["value1", "value2"]} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringListContainsAny,
			TestJSON: `{"op":"StringListContainsAny"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringListContainsAny,
			TestJSON: `{"op":"StringListContainsAny","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringListContainsAny,
			TestJSON: `{"op":"StringListContainsAny", "condition": {"candidates": ["value1", "value2"]} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringListContainsAll,
			TestJSON: `{"op":"StringListContainsAll"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringListContainsAll,
			TestJSON: `{"op":"StringListContainsAll","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpStringListContainsAll,
			TestJSON: `{"op":"StringListContainsAll", "condition": {"requiredItems": ["value1", "value2"]} }`,
			Success:  true,
		},
		{
			Op:       policy.OpStringListIsEmpty,
			TestJSON: `{"op":"StringListIsEmpty"}`,
			Success:  false,
		},
		{
			Op:       policy.OpStringListIsEmpty,
			TestJSON: `{"op":"StringListIsEmpty","condition": {} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIPEquals,
			TestJSON: `{"op":"IPEquals"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIPEquals,
			TestJSON: `{"op":"IPEquals","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIPEquals,
			TestJSON: `{"op":"IPEquals", "condition": {"ip": "192.168.1.1"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpIPInCIDR,
			TestJSON: `{"op":"IPInCIDR"}`,
			Success:  false,
		},
		{
			Op:       policy.OpIPInCIDR,
			TestJSON: `{"op":"IPInCIDR","condition": {} }`,
			Success:  false,
		},
		{
			Op:       policy.OpIPInCIDR,
			TestJSON: `{"op":"IPInCIDR", "condition": {"cidr": "192.168.1.0/24"} }`,
			Success:  true,
		},
		{
			Op:       policy.OpExists,
			TestJSON: `{"op":"Exists"}`,
			Success:  false,
		},
		{
			Op:       policy.OpExists,
			TestJSON: `{"op":"Exists","condition": {} }`,
			Success:  true,
		},
		{
			Op:       policy.OpNotExists,
			TestJSON: `{"op":"NotExists"}`,
			Success:  false,
		},
		{
			Op:       policy.OpNotExists,
			TestJSON: `{"op":"NotExists","condition": {} }`,
			Success:  true,
		},
	}

	for _, tc := range testCases {
		gc := &policy.GenericCondition{}
		err := gc.UnmarshalJSON([]byte(tc.TestJSON))
		if tc.Success {
			if err != nil {
				t.Errorf("expected success for operation %s, got error: %v", tc.Op, err)
			}
			// for unmarshaltest
			err = gc.Condition.UnmarshalJSON([]byte("invalid data"))
			if err == nil {
				t.Errorf("expected error for invalid data in operation %s, got none", tc.Op)
			}
		} else {
			if err == nil {
				t.Errorf("expected error for operation %s, got none", tc.Op)
			}
		}
	}
}
