// Code generated by script/internal_value.py. DO NOT EDIT.

package popmetrics

import (
    "fmt"
    "strings"
    "sync/atomic"
    "sync"
)

type PoPMetrics struct {
    RequestsTotal uint64
    RequestsEndTotal uint64
    ConnectTotal uint64
    CacheHitsTotal uint64
    CacheMissesTotal uint64
    CloseTotal uint64
    HijackedTotal uint64
    PerMethodTotalGet uint64
    PerMethodTotalHead uint64
    PerMethodTotalPost uint64
    PerMethodTotalPut uint64
    PerMethodTotalDelete uint64
    PerMethodTotalPatch uint64
    PerMethodTotalOptions uint64
    PerMethodTotalTrace uint64
    PerMethodTotalConnect uint64
    PerMethodTotalOther uint64
    PerProtocolTotalHttp10Plain uint64
    PerProtocolTotalHttp10 uint64
    PerProtocolTotalHttp11Plain uint64
    PerProtocolTotalHttp11 uint64
    PerProtocolTotalHttp2 uint64
    PerProtocolTotalHttp3 uint64
    PerProtocolTotalOtherPlain uint64
    PerProtocolTotalOther uint64
    HttpPort uint32
    HttpsPort uint32
    Http3Port uint32
}

type PoPMetricsWithLock struct {
    metricsLock sync.RWMutex
    metrics     PoPMetrics
}

func (p *PoPMetrics) AddRequestsTotal(v uint64) {
    atomic.AddUint64(&p.RequestsTotal, uint64(v))
}

func (p *PoPMetrics) IncrementRequestsTotal() {
    p.AddRequestsTotal(1)
}

func (p *PoPMetricsWithLock) AddRequestsTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddRequestsTotal(v)
}

func (p *PoPMetricsWithLock) IncrementRequestsTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementRequestsTotal()
}

func (p *PoPMetrics) AddRequestsEndTotal(v uint64) {
    atomic.AddUint64(&p.RequestsEndTotal, uint64(v))
}

func (p *PoPMetrics) IncrementRequestsEndTotal() {
    p.AddRequestsEndTotal(1)
}

func (p *PoPMetricsWithLock) AddRequestsEndTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddRequestsEndTotal(v)
}

func (p *PoPMetricsWithLock) IncrementRequestsEndTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementRequestsEndTotal()
}

func (p *PoPMetrics) AddConnectTotal(v uint64) {
    atomic.AddUint64(&p.ConnectTotal, uint64(v))
}

func (p *PoPMetrics) IncrementConnectTotal() {
    p.AddConnectTotal(1)
}

func (p *PoPMetricsWithLock) AddConnectTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddConnectTotal(v)
}

func (p *PoPMetricsWithLock) IncrementConnectTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementConnectTotal()
}

func (p *PoPMetrics) AddCacheHitsTotal(v uint64) {
    atomic.AddUint64(&p.CacheHitsTotal, uint64(v))
}

func (p *PoPMetrics) IncrementCacheHitsTotal() {
    p.AddCacheHitsTotal(1)
}

func (p *PoPMetricsWithLock) AddCacheHitsTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddCacheHitsTotal(v)
}

func (p *PoPMetricsWithLock) IncrementCacheHitsTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementCacheHitsTotal()
}

func (p *PoPMetrics) AddCacheMissesTotal(v uint64) {
    atomic.AddUint64(&p.CacheMissesTotal, uint64(v))
}

func (p *PoPMetrics) IncrementCacheMissesTotal() {
    p.AddCacheMissesTotal(1)
}

func (p *PoPMetricsWithLock) AddCacheMissesTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddCacheMissesTotal(v)
}

func (p *PoPMetricsWithLock) IncrementCacheMissesTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementCacheMissesTotal()
}

func (p *PoPMetrics) AddCloseTotal(v uint64) {
    atomic.AddUint64(&p.CloseTotal, uint64(v))
}

func (p *PoPMetrics) IncrementCloseTotal() {
    p.AddCloseTotal(1)
}

func (p *PoPMetricsWithLock) AddCloseTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddCloseTotal(v)
}

func (p *PoPMetricsWithLock) IncrementCloseTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementCloseTotal()
}

func (p *PoPMetrics) AddHijackedTotal(v uint64) {
    atomic.AddUint64(&p.HijackedTotal, uint64(v))
}

func (p *PoPMetrics) IncrementHijackedTotal() {
    p.AddHijackedTotal(1)
}

func (p *PoPMetricsWithLock) AddHijackedTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddHijackedTotal(v)
}

func (p *PoPMetricsWithLock) IncrementHijackedTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementHijackedTotal()
}

func (p *PoPMetrics) AddPerMethodTotalGet(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalGet, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalGet() {
    p.AddPerMethodTotalGet(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalGet(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalGet(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalGet() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalGet()
}

func (p *PoPMetrics) AddPerMethodTotalHead(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalHead, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalHead() {
    p.AddPerMethodTotalHead(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalHead(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalHead(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalHead() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalHead()
}

func (p *PoPMetrics) AddPerMethodTotalPost(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalPost, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalPost() {
    p.AddPerMethodTotalPost(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalPost(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalPost(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalPost() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalPost()
}

func (p *PoPMetrics) AddPerMethodTotalPut(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalPut, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalPut() {
    p.AddPerMethodTotalPut(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalPut(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalPut(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalPut() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalPut()
}

func (p *PoPMetrics) AddPerMethodTotalDelete(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalDelete, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalDelete() {
    p.AddPerMethodTotalDelete(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalDelete(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalDelete(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalDelete() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalDelete()
}

func (p *PoPMetrics) AddPerMethodTotalPatch(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalPatch, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalPatch() {
    p.AddPerMethodTotalPatch(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalPatch(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalPatch(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalPatch() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalPatch()
}

func (p *PoPMetrics) AddPerMethodTotalOptions(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalOptions, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalOptions() {
    p.AddPerMethodTotalOptions(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalOptions(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalOptions(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalOptions() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalOptions()
}

func (p *PoPMetrics) AddPerMethodTotalTrace(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalTrace, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalTrace() {
    p.AddPerMethodTotalTrace(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalTrace(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalTrace(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalTrace() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalTrace()
}

func (p *PoPMetrics) AddPerMethodTotalConnect(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalConnect, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalConnect() {
    p.AddPerMethodTotalConnect(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalConnect(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalConnect(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalConnect() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalConnect()
}

func (p *PoPMetrics) AddPerMethodTotalOther(v uint64) {
    atomic.AddUint64(&p.PerMethodTotalOther, uint64(v))
}

func (p *PoPMetrics) IncrementPerMethodTotalOther() {
    p.AddPerMethodTotalOther(1)
}

func (p *PoPMetricsWithLock) AddPerMethodTotalOther(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerMethodTotalOther(v)
}

func (p *PoPMetricsWithLock) IncrementPerMethodTotalOther() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerMethodTotalOther()
}

func (p *PoPMetrics) AddPerProtocolTotalHttp10Plain(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalHttp10Plain, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalHttp10Plain() {
    p.AddPerProtocolTotalHttp10Plain(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalHttp10Plain(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalHttp10Plain(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalHttp10Plain() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalHttp10Plain()
}

func (p *PoPMetrics) AddPerProtocolTotalHttp10(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalHttp10, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalHttp10() {
    p.AddPerProtocolTotalHttp10(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalHttp10(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalHttp10(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalHttp10() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalHttp10()
}

func (p *PoPMetrics) AddPerProtocolTotalHttp11Plain(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalHttp11Plain, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalHttp11Plain() {
    p.AddPerProtocolTotalHttp11Plain(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalHttp11Plain(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalHttp11Plain(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalHttp11Plain() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalHttp11Plain()
}

func (p *PoPMetrics) AddPerProtocolTotalHttp11(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalHttp11, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalHttp11() {
    p.AddPerProtocolTotalHttp11(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalHttp11(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalHttp11(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalHttp11() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalHttp11()
}

func (p *PoPMetrics) AddPerProtocolTotalHttp2(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalHttp2, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalHttp2() {
    p.AddPerProtocolTotalHttp2(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalHttp2(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalHttp2(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalHttp2() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalHttp2()
}

func (p *PoPMetrics) AddPerProtocolTotalHttp3(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalHttp3, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalHttp3() {
    p.AddPerProtocolTotalHttp3(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalHttp3(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalHttp3(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalHttp3() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalHttp3()
}

func (p *PoPMetrics) AddPerProtocolTotalOtherPlain(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalOtherPlain, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalOtherPlain() {
    p.AddPerProtocolTotalOtherPlain(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalOtherPlain(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalOtherPlain(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalOtherPlain() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalOtherPlain()
}

func (p *PoPMetrics) AddPerProtocolTotalOther(v uint64) {
    atomic.AddUint64(&p.PerProtocolTotalOther, uint64(v))
}

func (p *PoPMetrics) IncrementPerProtocolTotalOther() {
    p.AddPerProtocolTotalOther(1)
}

func (p *PoPMetricsWithLock) AddPerProtocolTotalOther(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddPerProtocolTotalOther(v)
}

func (p *PoPMetricsWithLock) IncrementPerProtocolTotalOther() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementPerProtocolTotalOther()
}

func (p *PoPMetrics) SetHttpPort(v uint16) {
    atomic.StoreUint32(&p.HttpPort, uint32(v))
}

func (p *PoPMetricsWithLock) SetHttpPort(v uint16) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.SetHttpPort(v)
}

func (p *PoPMetrics) SetHttpsPort(v uint16) {
    atomic.StoreUint32(&p.HttpsPort, uint32(v))
}

func (p *PoPMetricsWithLock) SetHttpsPort(v uint16) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.SetHttpsPort(v)
}

func (p *PoPMetrics) SetHttp3Port(v uint16) {
    atomic.StoreUint32(&p.Http3Port, uint32(v))
}

func (p *PoPMetricsWithLock) SetHttp3Port(v uint16) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.SetHttp3Port(v)
}

type PoPMetricsMetricsInterface interface {
    AddRequestsTotal(v uint64)
    IncrementRequestsTotal()
    AddRequestsEndTotal(v uint64)
    IncrementRequestsEndTotal()
    AddConnectTotal(v uint64)
    IncrementConnectTotal()
    AddCacheHitsTotal(v uint64)
    IncrementCacheHitsTotal()
    AddCacheMissesTotal(v uint64)
    IncrementCacheMissesTotal()
    AddCloseTotal(v uint64)
    IncrementCloseTotal()
    AddHijackedTotal(v uint64)
    IncrementHijackedTotal()
    AddPerMethodTotalGet(v uint64)
    IncrementPerMethodTotalGet()
    AddPerMethodTotalHead(v uint64)
    IncrementPerMethodTotalHead()
    AddPerMethodTotalPost(v uint64)
    IncrementPerMethodTotalPost()
    AddPerMethodTotalPut(v uint64)
    IncrementPerMethodTotalPut()
    AddPerMethodTotalDelete(v uint64)
    IncrementPerMethodTotalDelete()
    AddPerMethodTotalPatch(v uint64)
    IncrementPerMethodTotalPatch()
    AddPerMethodTotalOptions(v uint64)
    IncrementPerMethodTotalOptions()
    AddPerMethodTotalTrace(v uint64)
    IncrementPerMethodTotalTrace()
    AddPerMethodTotalConnect(v uint64)
    IncrementPerMethodTotalConnect()
    AddPerMethodTotalOther(v uint64)
    IncrementPerMethodTotalOther()
    AddPerProtocolTotalHttp10Plain(v uint64)
    IncrementPerProtocolTotalHttp10Plain()
    AddPerProtocolTotalHttp10(v uint64)
    IncrementPerProtocolTotalHttp10()
    AddPerProtocolTotalHttp11Plain(v uint64)
    IncrementPerProtocolTotalHttp11Plain()
    AddPerProtocolTotalHttp11(v uint64)
    IncrementPerProtocolTotalHttp11()
    AddPerProtocolTotalHttp2(v uint64)
    IncrementPerProtocolTotalHttp2()
    AddPerProtocolTotalHttp3(v uint64)
    IncrementPerProtocolTotalHttp3()
    AddPerProtocolTotalOtherPlain(v uint64)
    IncrementPerProtocolTotalOtherPlain()
    AddPerProtocolTotalOther(v uint64)
    IncrementPerProtocolTotalOther()
    SetHttpPort(v uint16)
    SetHttpsPort(v uint16)
    SetHttp3Port(v uint16)
}

func (p *PoPMetrics) String() string {
    var buf strings.Builder
    buf.WriteString("PoPMetrics{")
 if p.RequestsTotal != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("RequestsTotal: %v", p.RequestsTotal))
 }
 if p.RequestsEndTotal != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("RequestsEndTotal: %v", p.RequestsEndTotal))
 }
 if p.ConnectTotal != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("ConnectTotal: %v", p.ConnectTotal))
 }
 if p.CacheHitsTotal != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("CacheHitsTotal: %v", p.CacheHitsTotal))
 }
 if p.CacheMissesTotal != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("CacheMissesTotal: %v", p.CacheMissesTotal))
 }
 if p.CloseTotal != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("CloseTotal: %v", p.CloseTotal))
 }
 if p.HijackedTotal != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("HijackedTotal: %v", p.HijackedTotal))
 }
 if p.PerMethodTotalGet != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalGet: %v", p.PerMethodTotalGet))
 }
 if p.PerMethodTotalHead != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalHead: %v", p.PerMethodTotalHead))
 }
 if p.PerMethodTotalPost != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalPost: %v", p.PerMethodTotalPost))
 }
 if p.PerMethodTotalPut != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalPut: %v", p.PerMethodTotalPut))
 }
 if p.PerMethodTotalDelete != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalDelete: %v", p.PerMethodTotalDelete))
 }
 if p.PerMethodTotalPatch != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalPatch: %v", p.PerMethodTotalPatch))
 }
 if p.PerMethodTotalOptions != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalOptions: %v", p.PerMethodTotalOptions))
 }
 if p.PerMethodTotalTrace != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalTrace: %v", p.PerMethodTotalTrace))
 }
 if p.PerMethodTotalConnect != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalConnect: %v", p.PerMethodTotalConnect))
 }
 if p.PerMethodTotalOther != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerMethodTotalOther: %v", p.PerMethodTotalOther))
 }
 if p.PerProtocolTotalHttp10Plain != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalHttp10Plain: %v", p.PerProtocolTotalHttp10Plain))
 }
 if p.PerProtocolTotalHttp10 != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalHttp10: %v", p.PerProtocolTotalHttp10))
 }
 if p.PerProtocolTotalHttp11Plain != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalHttp11Plain: %v", p.PerProtocolTotalHttp11Plain))
 }
 if p.PerProtocolTotalHttp11 != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalHttp11: %v", p.PerProtocolTotalHttp11))
 }
 if p.PerProtocolTotalHttp2 != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalHttp2: %v", p.PerProtocolTotalHttp2))
 }
 if p.PerProtocolTotalHttp3 != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalHttp3: %v", p.PerProtocolTotalHttp3))
 }
 if p.PerProtocolTotalOtherPlain != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalOtherPlain: %v", p.PerProtocolTotalOtherPlain))
 }
 if p.PerProtocolTotalOther != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("PerProtocolTotalOther: %v", p.PerProtocolTotalOther))
 }
 if p.HttpPort != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("HttpPort: %v", p.HttpPort))
 }
 if p.HttpsPort != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("HttpsPort: %v", p.HttpsPort))
 }
 if p.Http3Port != 0 {
    if buf.Len() > len("PoPMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("Http3Port: %v", p.Http3Port))
 }
    buf.WriteString("}")
    return buf.String()
}

func (p *PoPMetricsWithLock) GetMetrics() PoPMetrics {
    p.metricsLock.Lock()
    defer p.metricsLock.Unlock()
    return p.metrics
}

func (p *PoPMetricsWithLock) WithLock(cb func(m *PoPMetrics)) {
    p.metricsLock.Lock()
    defer p.metricsLock.Unlock()
    cb(&p.metrics)
}

