// Code generated by kscale/access/generator. DO NOT EDIT.
package dnsconfig

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
)

// Handlers is the generated dns_config desired-state store.
type Handlers struct {
	pb.UnimplementedDnsConfigServiceServer
	mu       sync.Mutex
	store    map[string]*pbaccess.ResourceDnsConfigActionGetResponseDTO
	onChange []func()
	// ConfirmPush, set by the control plane, returns the resource's current per-node
	// reconcile push error (nil if all good); called right after notify() so apply
	// reports a failed push synchronously instead of a silent OK. Optional.
	ConfirmPush func() error
}

var _ pb.DnsConfigServiceServer = (*Handlers)(nil)

// New returns an empty dns_config store.
func New() *Handlers {
	return &Handlers{store: map[string]*pbaccess.ResourceDnsConfigActionGetResponseDTO{}}
}

// redacted returns a copy with sensitive fields blanked — what northbound callers
// see. The sensitive values are write-only: pushed to the node by reconcile (which
// reads the full Desired()), never returned.
func redacted(c *pbaccess.ResourceDnsConfigActionGetResponseDTO) *pbaccess.ResourceDnsConfigActionGetResponseDTO {
	if c == nil {
		return nil
	}
	return &pbaccess.ResourceDnsConfigActionGetResponseDTO{
		Name:      c.Name,
		Port:      c.Port,
		Domain:    c.Domain,
		Mail:      c.Mail,
		ApiZoneId: c.ApiZoneId,
	}
}

// Apply idempotently upserts one dns_config by Name.
func (h *Handlers) Apply(ctx context.Context, req *pbaccess.ResourceDnsConfigActionApplyArgsDTO) (*pbaccess.ResourceDnsConfigActionApplyResponseDTO, error) {
	h.mu.Lock()
	obj := &pbaccess.ResourceDnsConfigActionGetResponseDTO{
		Name:      req.Name,
		Port:      req.Port,
		Domain:    req.Domain,
		Mail:      req.Mail,
		ApiToken:  req.ApiToken,
		ApiZoneId: req.ApiZoneId,
	}
	h.store[req.Name] = obj
	resp := &pbaccess.ResourceDnsConfigActionApplyResponseDTO{
		Name:      req.Name,
		Port:      req.Port,
		Domain:    req.Domain,
		Mail:      req.Mail,
		ApiZoneId: req.ApiZoneId,
	}
	h.mu.Unlock()
	h.notify()
	if h.ConfirmPush != nil {
		return resp, h.ConfirmPush()
	}
	return resp, nil
}

// Get returns one dns_config by Name.
func (h *Handlers) Get(ctx context.Context, req *pbaccess.ResourceDnsConfigActionGetArgsDTO) (*pbaccess.ResourceDnsConfigActionGetResponseDTO, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	obj, ok := h.store[req.Name]
	if !ok {
		return nil, fmt.Errorf("dns_config %q not found", req.Name)
	}
	return redacted(obj), nil
}

// List returns every dns_config (sorted by key for determinism).
func (h *Handlers) List(ctx context.Context, _ *pbaccess.ResourceDnsConfigActionListArgsDTO) (*pbaccess.ResourceDnsConfigActionListResponseDTO, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	keys := make([]string, 0, len(h.store))
	for k := range h.store {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	items := make([]*pbaccess.ResourceDnsConfigActionGetResponseDTO, 0, len(keys))
	for _, k := range keys {
		items = append(items, redacted(h.store[k]))
	}
	return &pbaccess.ResourceDnsConfigActionListResponseDTO{Items: items}, nil
}

// OnChange registers a callback fired on every desired-state mutation — the
// reconcile loop subscribes to re-push to the dataplane.
func (h *Handlers) OnChange(f func()) {
	h.mu.Lock()
	h.onChange = append(h.onChange, f)
	h.mu.Unlock()
}

func (h *Handlers) notify() {
	h.mu.Lock()
	cbs := append([]func(){}, h.onChange...)
	h.mu.Unlock()
	for _, f := range cbs {
		f()
	}
}

// Desired returns the full desired set (WITH sensitive fields) for the reconcile
// loop to push to the dataplane.
func (h *Handlers) Desired() []*pbaccess.ResourceDnsConfigActionGetResponseDTO {
	h.mu.Lock()
	defer h.mu.Unlock()
	out := make([]*pbaccess.ResourceDnsConfigActionGetResponseDTO, 0, len(h.store))
	for _, c := range h.store {
		out = append(out, c)
	}
	return out
}

// Snapshot/Restore persist the desired state (desiredstate.Store). The full map
// (including sensitive fields) is serialized; the desiredstate file is encrypted.
func (h *Handlers) Snapshot() (json.RawMessage, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	return json.Marshal(h.store)
}

func (h *Handlers) Restore(raw json.RawMessage) error {
	var m map[string]*pbaccess.ResourceDnsConfigActionGetResponseDTO
	if err := json.Unmarshal(raw, &m); err != nil {
		return err
	}
	if m == nil {
		m = map[string]*pbaccess.ResourceDnsConfigActionGetResponseDTO{}
	}
	h.mu.Lock()
	defer h.mu.Unlock()
	h.store = m
	return nil
}
