// Code generated by json2go. DO NOT EDIT.
package index

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"reflect"
)

const IndexFileHeaderSize = ((12 + 8) + 16)
const RecordHeaderSize = 39

type IndexKind uint8

const (
	IndexKind_Cert    IndexKind = 0
	IndexKind_Priv    IndexKind = 1
	IndexKind_Keypair IndexKind = 2
	IndexKind_Blob    IndexKind = 3
)

func (t IndexKind) String() string {
	switch t {
	case IndexKind_Cert:
		return "Cert"
	case IndexKind_Priv:
		return "Priv"
	case IndexKind_Keypair:
		return "Keypair"
	case IndexKind_Blob:
		return "Blob"
	}
	return fmt.Sprintf("IndexKind(%d)", t)
}

type ManagerID struct {
	Id [16]uint8
}
type VisitorNVCEN interface {
	Visit(v VisitorNVCEN, name string, field any)
}
type VisitorNVCENFunc func(v VisitorNVCEN, name string, field any)

func (f VisitorNVCENFunc) Visit(v VisitorNVCEN, name string, field any) {
	f(v, name, field)
}

type VisitorNVCENVisitable interface {
	Visit(v VisitorNVCEN)
}

func VisitorNVCENToMap(v any) interface{} {
	if v == nil {
		return nil
	}
	if inter, ok := v.(VisitorNVCENVisitable); ok {
		if p := reflect.ValueOf(inter); p.Kind() == reflect.Pointer && p.IsNil() {
			return nil
		}
		m := map[string]interface{}{}
		inter.Visit(VisitorNVCENFunc(func(v VisitorNVCEN, name string, field any) {
			m[name] = VisitorNVCENToMap(field)
		}))
		return m
	}
	if tf := reflect.TypeOf(v); (tf.Kind() == reflect.Slice || tf.Kind() == reflect.Array) && !(func() bool { k := tf.Elem().Kind().String(); return k[:3] == "int" || k[:3] == "uin" || k[:3] == "flo" })() {
		m := []interface{}{}
		vf := reflect.ValueOf(v)
		for i := 0; i < vf.Len(); i++ {
			index := vf.Index(i)
			if index.Kind() == reflect.Struct && index.CanAddr() {
				index = index.Addr()
			}
			m = append(m, VisitorNVCENToMap(index.Interface()))
		}
		return m
	}
	if tf := reflect.TypeOf(v); tf.Kind() == reflect.Pointer {
		val := reflect.ValueOf(v)
		if val.IsNil() {
			return nil
		}
		return VisitorNVCENToMap(val.Elem().Interface())
	}
	return v
}

type Secret struct {
	Len    uint16
	Secret []uint8
}
type KeyHash struct {
	Hash [64]uint8
}
type IndexNonce struct {
	Nonce [12]uint8
}
type OpaquePointer struct {
	Pointer uint64
}
type Time struct {
	Seconds uint64
}
type SerialNumber struct {
	Serial [20]uint8
}
type Name struct {
	Len  uint8
	Name []uint8
}
type IssuedCert struct {
	Len         uint16
	Certificate []uint8
}
type IndexFileHeader struct {
	Nonce         IndexNonce
	RecordCounter uint64
	AeadTag       [16]uint8
}
type RecordHeader struct {
	IndexLen      uint16
	RecordVersion uint8
	ManagerID     ManagerID
	KeyMaterial   uint64
}
type RecordHeaderWithNonce struct {
	Header RecordHeader
	Nonce  IndexNonce
}
type AeadprotectTarget struct {
	Header     RecordHeaderWithNonce
	FileOffset uint64
}
type Record struct {
	Header RecordHeaderWithNonce
	Index  []uint8
}
type IndexCommonInfo struct {
	flags9    uint8
	NotBefore Time
	NotAfter  Time
	UpdatedAt Time
}
type CertIndex struct {
	Pointer         OpaquePointer
	SerialNumber    SerialNumber
	CertLen         uint16
	Common          IndexCommonInfo
	CertificateHash KeyHash
	Name            Name
}
type KeyPairIndex struct {
	PrivLen uint16
	Cert    CertIndex
}
type KeyPair struct {
	PrivLen    uint16
	PrivateKey []uint8
	Cert       IssuedCert
}
type CAState struct {
	SavedTime     uint64
	CurrentSerial [20]uint8
	Ca            KeyPairIndex
	ManagerID     ManagerID
	RecordCounter uint64
}
type IndexFile struct {
	Header  IndexFileHeader
	Records []Record
}
type union19_BootInfo interface {
	isunion18_()
}
type union_20_t struct {
	CaCert IssuedCert
}
type BootInfo struct {
	SelfCert KeyPair
	PeerCert IssuedCert
	flags17  uint8
	union18_ union19_BootInfo
}
type PrivateKeyIndex struct {
	Pointer        OpaquePointer
	PrivLen        uint16
	Common         IndexCommonInfo
	PrivateKeyHash KeyHash
	Name           Name
}
type BlobIndex struct {
	Pointer  OpaquePointer
	BlobLen  uint64
	Common   IndexCommonInfo
	BlobHash KeyHash
	Name     Name
}
type union24_Index interface {
	isunion23_()
}
type union_25_t struct {
	Cert CertIndex
}
type union_26_t struct {
	Priv PrivateKeyIndex
}
type union_27_t struct {
	KeyPair KeyPairIndex
}
type union_28_t struct {
	Blob BlobIndex
}
type Index struct {
	RecordCounter uint64
	Kind          IndexKind
	union23_      union24_Index
}

func (t *ManagerID) Visit(v VisitorNVCEN) {
	v.Visit(v, "Id", &t.Id)
}
func (t *ManagerID) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *ManagerID) Write(w io.Writer) (err error) {
	if n, err := w.Write(t.Id[:]); err != nil || n != len(t.Id) {
		return fmt.Errorf("encode Id: %w", err)
	}
	return nil
}
func (t *ManagerID) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 16))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *ManagerID) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *ManagerID) Read(r io.Reader) (err error) {
	n_Id, err := io.ReadFull(r, t.Id[:])
	if err != nil {
		return fmt.Errorf("read Id: expect %d bytes but read %d bytes: %w", 16, n_Id, err)
	}
	return nil
}

func (t *ManagerID) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *ManagerID) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode ManagerID: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Secret) SetSecret(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.Len = uint16(len(v))
	t.Secret = v
	return true
}
func (t *Secret) Visit(v VisitorNVCEN) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Secret", &t.Secret)
}
func (t *Secret) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *Secret) Write(w io.Writer) (err error) {
	tmp1 := [2]byte{}
	binary.BigEndian.PutUint16(tmp1[:], uint16(t.Len))
	if n, err := w.Write(tmp1[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Secret := int(t.Len)
	if len(t.Secret) != len_Secret {
		return fmt.Errorf("encode Secret: expect %d bytes but got %d bytes", len_Secret, len(t.Secret))
	}
	if n, err := w.Write(t.Secret); err != nil || n != len(t.Secret) {
		return fmt.Errorf("encode Secret: %w", err)
	}
	return nil
}
func (t *Secret) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 2))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Secret) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Secret) Read(r io.Reader) (err error) {
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.BigEndian.Uint16(tmpLen[:]))
	len_Secret := int(t.Len)
	if len_Secret != 0 {
		// to prevent from allocation attack, allocate empty slice first
		tmpSecret := bytes.NewBuffer([]byte{})
		n_Secret, err := io.CopyN(tmpSecret, r, int64(len_Secret))
		if err != nil {
			return fmt.Errorf("read Secret: expect %d bytes but read %d bytes: %w", len_Secret, n_Secret, err)
		}
		t.Secret = tmpSecret.Bytes()
	} else {
		t.Secret = nil
	}
	return nil
}

func (t *Secret) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Secret) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Secret: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *KeyHash) Visit(v VisitorNVCEN) {
	v.Visit(v, "Hash", &t.Hash)
}
func (t *KeyHash) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *KeyHash) Write(w io.Writer) (err error) {
	if n, err := w.Write(t.Hash[:]); err != nil || n != len(t.Hash) {
		return fmt.Errorf("encode Hash: %w", err)
	}
	return nil
}
func (t *KeyHash) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 64))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *KeyHash) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *KeyHash) Read(r io.Reader) (err error) {
	n_Hash, err := io.ReadFull(r, t.Hash[:])
	if err != nil {
		return fmt.Errorf("read Hash: expect %d bytes but read %d bytes: %w", 64, n_Hash, err)
	}
	return nil
}

func (t *KeyHash) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *KeyHash) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode KeyHash: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *IndexNonce) Visit(v VisitorNVCEN) {
	v.Visit(v, "Nonce", &t.Nonce)
}
func (t *IndexNonce) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *IndexNonce) Write(w io.Writer) (err error) {
	if n, err := w.Write(t.Nonce[:]); err != nil || n != len(t.Nonce) {
		return fmt.Errorf("encode Nonce: %w", err)
	}
	return nil
}
func (t *IndexNonce) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 12))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *IndexNonce) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *IndexNonce) Read(r io.Reader) (err error) {
	n_Nonce, err := io.ReadFull(r, t.Nonce[:])
	if err != nil {
		return fmt.Errorf("read Nonce: expect %d bytes but read %d bytes: %w", 12, n_Nonce, err)
	}
	return nil
}

func (t *IndexNonce) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *IndexNonce) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode IndexNonce: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *OpaquePointer) Visit(v VisitorNVCEN) {
	v.Visit(v, "Pointer", &t.Pointer)
}
func (t *OpaquePointer) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *OpaquePointer) Write(w io.Writer) (err error) {
	tmp2 := [8]byte{}
	binary.BigEndian.PutUint64(tmp2[:], uint64(t.Pointer))
	if n, err := w.Write(tmp2[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.Pointer: %w", err)
	}
	return nil
}
func (t *OpaquePointer) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 8))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *OpaquePointer) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *OpaquePointer) Read(r io.Reader) (err error) {
	tmpPointer := [8]byte{}
	n_Pointer, err := io.ReadFull(r, tmpPointer[:])
	if err != nil {
		return fmt.Errorf("read Pointer: expect 8 bytes but read %d bytes: %w", n_Pointer, err)
	}
	t.Pointer = uint64(binary.BigEndian.Uint64(tmpPointer[:]))
	return nil
}

func (t *OpaquePointer) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *OpaquePointer) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode OpaquePointer: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Time) Visit(v VisitorNVCEN) {
	v.Visit(v, "Seconds", &t.Seconds)
}
func (t *Time) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *Time) Write(w io.Writer) (err error) {
	tmp3 := [8]byte{}
	binary.BigEndian.PutUint64(tmp3[:], uint64(t.Seconds))
	if n, err := w.Write(tmp3[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.Seconds: %w", err)
	}
	return nil
}
func (t *Time) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 8))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Time) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Time) Read(r io.Reader) (err error) {
	tmpSeconds := [8]byte{}
	n_Seconds, err := io.ReadFull(r, tmpSeconds[:])
	if err != nil {
		return fmt.Errorf("read Seconds: expect 8 bytes but read %d bytes: %w", n_Seconds, err)
	}
	t.Seconds = uint64(binary.BigEndian.Uint64(tmpSeconds[:]))
	return nil
}

func (t *Time) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Time) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Time: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *SerialNumber) Visit(v VisitorNVCEN) {
	v.Visit(v, "Serial", &t.Serial)
}
func (t *SerialNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *SerialNumber) Write(w io.Writer) (err error) {
	if n, err := w.Write(t.Serial[:]); err != nil || n != len(t.Serial) {
		return fmt.Errorf("encode Serial: %w", err)
	}
	return nil
}
func (t *SerialNumber) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 20))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *SerialNumber) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *SerialNumber) Read(r io.Reader) (err error) {
	n_Serial, err := io.ReadFull(r, t.Serial[:])
	if err != nil {
		return fmt.Errorf("read Serial: expect %d bytes but read %d bytes: %w", 20, n_Serial, err)
	}
	return nil
}

func (t *SerialNumber) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *SerialNumber) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode SerialNumber: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Name) SetName(v []uint8) bool {
	if len(v) > int(^uint8(0)) {
		return false
	}
	t.Len = uint8(len(v))
	t.Name = v
	return true
}
func (t *Name) Visit(v VisitorNVCEN) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Name", &t.Name)
}
func (t *Name) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *Name) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.Len)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Name := int(t.Len)
	if len(t.Name) != len_Name {
		return fmt.Errorf("encode Name: expect %d bytes but got %d bytes", len_Name, len(t.Name))
	}
	if n, err := w.Write(t.Name); err != nil || n != len(t.Name) {
		return fmt.Errorf("encode Name: %w", err)
	}
	return nil
}
func (t *Name) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 1))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Name) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Name) Read(r io.Reader) (err error) {
	tmpLen := [1]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 1 byte but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint8(tmpLen[0])
	len_Name := int(t.Len)
	if len_Name != 0 {
		// to prevent from allocation attack, allocate empty slice first
		tmpName := bytes.NewBuffer([]byte{})
		n_Name, err := io.CopyN(tmpName, r, int64(len_Name))
		if err != nil {
			return fmt.Errorf("read Name: expect %d bytes but read %d bytes: %w", len_Name, n_Name, err)
		}
		t.Name = tmpName.Bytes()
	} else {
		t.Name = nil
	}
	return nil
}

func (t *Name) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Name) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Name: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *IssuedCert) SetCertificate(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.Len = uint16(len(v))
	t.Certificate = v
	return true
}
func (t *IssuedCert) Visit(v VisitorNVCEN) {
	v.Visit(v, "Len", &t.Len)
	v.Visit(v, "Certificate", &t.Certificate)
}
func (t *IssuedCert) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *IssuedCert) Write(w io.Writer) (err error) {
	tmp4 := [2]byte{}
	binary.BigEndian.PutUint16(tmp4[:], uint16(t.Len))
	if n, err := w.Write(tmp4[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.Len: %w", err)
	}
	len_Certificate := int(t.Len)
	if len(t.Certificate) != len_Certificate {
		return fmt.Errorf("encode Certificate: expect %d bytes but got %d bytes", len_Certificate, len(t.Certificate))
	}
	if n, err := w.Write(t.Certificate); err != nil || n != len(t.Certificate) {
		return fmt.Errorf("encode Certificate: %w", err)
	}
	return nil
}
func (t *IssuedCert) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 2))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *IssuedCert) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *IssuedCert) Read(r io.Reader) (err error) {
	tmpLen := [2]byte{}
	n_Len, err := io.ReadFull(r, tmpLen[:])
	if err != nil {
		return fmt.Errorf("read Len: expect 2 bytes but read %d bytes: %w", n_Len, err)
	}
	t.Len = uint16(binary.BigEndian.Uint16(tmpLen[:]))
	len_Certificate := int(t.Len)
	if len_Certificate != 0 {
		// to prevent from allocation attack, allocate empty slice first
		tmpCertificate := bytes.NewBuffer([]byte{})
		n_Certificate, err := io.CopyN(tmpCertificate, r, int64(len_Certificate))
		if err != nil {
			return fmt.Errorf("read Certificate: expect %d bytes but read %d bytes: %w", len_Certificate, n_Certificate, err)
		}
		t.Certificate = tmpCertificate.Bytes()
	} else {
		t.Certificate = nil
	}
	return nil
}

func (t *IssuedCert) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *IssuedCert) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode IssuedCert: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *IndexFileHeader) Visit(v VisitorNVCEN) {
	v.Visit(v, "Nonce", &t.Nonce)
	v.Visit(v, "RecordCounter", &t.RecordCounter)
	v.Visit(v, "AeadTag", &t.AeadTag)
}
func (t *IndexFileHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *IndexFileHeader) Write(w io.Writer) (err error) {
	if err := t.Nonce.Write(w); err != nil {
		return fmt.Errorf("encode Nonce: %w", err)
	}
	tmp5 := [8]byte{}
	binary.BigEndian.PutUint64(tmp5[:], uint64(t.RecordCounter))
	if n, err := w.Write(tmp5[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.RecordCounter: %w", err)
	}
	if n, err := w.Write(t.AeadTag[:]); err != nil || n != len(t.AeadTag) {
		return fmt.Errorf("encode AeadTag: %w", err)
	}
	return nil
}
func (t *IndexFileHeader) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 36))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *IndexFileHeader) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *IndexFileHeader) Read(r io.Reader) (err error) {
	if err := t.Nonce.Read(r); err != nil {
		return fmt.Errorf("read Nonce: %w", err)
	}
	tmpRecordCounter := [8]byte{}
	n_RecordCounter, err := io.ReadFull(r, tmpRecordCounter[:])
	if err != nil {
		return fmt.Errorf("read RecordCounter: expect 8 bytes but read %d bytes: %w", n_RecordCounter, err)
	}
	t.RecordCounter = uint64(binary.BigEndian.Uint64(tmpRecordCounter[:]))
	n_AeadTag, err := io.ReadFull(r, t.AeadTag[:])
	if err != nil {
		return fmt.Errorf("read AeadTag: expect %d bytes but read %d bytes: %w", 16, n_AeadTag, err)
	}
	return nil
}

func (t *IndexFileHeader) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *IndexFileHeader) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode IndexFileHeader: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *RecordHeader) Visit(v VisitorNVCEN) {
	v.Visit(v, "IndexLen", &t.IndexLen)
	v.Visit(v, "RecordVersion", &t.RecordVersion)
	v.Visit(v, "ManagerID", &t.ManagerID)
	v.Visit(v, "KeyMaterial", &t.KeyMaterial)
}
func (t *RecordHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *RecordHeader) Write(w io.Writer) (err error) {
	tmp6 := [2]byte{}
	binary.BigEndian.PutUint16(tmp6[:], uint16(t.IndexLen))
	if n, err := w.Write(tmp6[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.IndexLen: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.RecordVersion)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.RecordVersion: %w", err)
	}
	if err := t.ManagerID.Write(w); err != nil {
		return fmt.Errorf("encode ManagerID: %w", err)
	}
	tmp7 := [8]byte{}
	binary.BigEndian.PutUint64(tmp7[:], uint64(t.KeyMaterial))
	if n, err := w.Write(tmp7[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.KeyMaterial: %w", err)
	}
	return nil
}
func (t *RecordHeader) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 27))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *RecordHeader) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *RecordHeader) Read(r io.Reader) (err error) {
	tmpIndexLen := [2]byte{}
	n_IndexLen, err := io.ReadFull(r, tmpIndexLen[:])
	if err != nil {
		return fmt.Errorf("read IndexLen: expect 2 bytes but read %d bytes: %w", n_IndexLen, err)
	}
	t.IndexLen = uint16(binary.BigEndian.Uint16(tmpIndexLen[:]))
	tmpRecordVersion := [1]byte{}
	n_RecordVersion, err := io.ReadFull(r, tmpRecordVersion[:])
	if err != nil {
		return fmt.Errorf("read RecordVersion: expect 1 byte but read %d bytes: %w", n_RecordVersion, err)
	}
	t.RecordVersion = uint8(tmpRecordVersion[0])
	if err := t.ManagerID.Read(r); err != nil {
		return fmt.Errorf("read ManagerID: %w", err)
	}
	tmpKeyMaterial := [8]byte{}
	n_KeyMaterial, err := io.ReadFull(r, tmpKeyMaterial[:])
	if err != nil {
		return fmt.Errorf("read KeyMaterial: expect 8 bytes but read %d bytes: %w", n_KeyMaterial, err)
	}
	t.KeyMaterial = uint64(binary.BigEndian.Uint64(tmpKeyMaterial[:]))
	return nil
}

func (t *RecordHeader) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *RecordHeader) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode RecordHeader: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *RecordHeaderWithNonce) Visit(v VisitorNVCEN) {
	v.Visit(v, "Header", &t.Header)
	v.Visit(v, "Nonce", &t.Nonce)
}
func (t *RecordHeaderWithNonce) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *RecordHeaderWithNonce) Write(w io.Writer) (err error) {
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	if err := t.Nonce.Write(w); err != nil {
		return fmt.Errorf("encode Nonce: %w", err)
	}
	return nil
}
func (t *RecordHeaderWithNonce) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 39))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *RecordHeaderWithNonce) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *RecordHeaderWithNonce) Read(r io.Reader) (err error) {
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	if err := t.Nonce.Read(r); err != nil {
		return fmt.Errorf("read Nonce: %w", err)
	}
	return nil
}

func (t *RecordHeaderWithNonce) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *RecordHeaderWithNonce) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode RecordHeaderWithNonce: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *AeadprotectTarget) Visit(v VisitorNVCEN) {
	v.Visit(v, "Header", &t.Header)
	v.Visit(v, "FileOffset", &t.FileOffset)
}
func (t *AeadprotectTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *AeadprotectTarget) Write(w io.Writer) (err error) {
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	tmp8 := [8]byte{}
	binary.BigEndian.PutUint64(tmp8[:], uint64(t.FileOffset))
	if n, err := w.Write(tmp8[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.FileOffset: %w", err)
	}
	return nil
}
func (t *AeadprotectTarget) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 47))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *AeadprotectTarget) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *AeadprotectTarget) Read(r io.Reader) (err error) {
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	tmpFileOffset := [8]byte{}
	n_FileOffset, err := io.ReadFull(r, tmpFileOffset[:])
	if err != nil {
		return fmt.Errorf("read FileOffset: expect 8 bytes but read %d bytes: %w", n_FileOffset, err)
	}
	t.FileOffset = uint64(binary.BigEndian.Uint64(tmpFileOffset[:]))
	return nil
}

func (t *AeadprotectTarget) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *AeadprotectTarget) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode AeadprotectTarget: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *Record) SetIndex(v []uint8) bool {
	t.Index = v
	return true
}
func (t *Record) Visit(v VisitorNVCEN) {
	v.Visit(v, "Header", &t.Header)
	v.Visit(v, "Index", &t.Index)
}
func (t *Record) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *Record) Write(w io.Writer) (err error) {
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	len_Index := int(t.Header.Header.IndexLen)
	if len(t.Index) != len_Index {
		return fmt.Errorf("encode Index: expect %d bytes but got %d bytes", len_Index, len(t.Index))
	}
	if n, err := w.Write(t.Index); err != nil || n != len(t.Index) {
		return fmt.Errorf("encode Index: %w", err)
	}
	return nil
}
func (t *Record) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 39))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Record) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Record) Read(r io.Reader) (err error) {
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	len_Index := int(t.Header.Header.IndexLen)
	if len_Index != 0 {
		// to prevent from allocation attack, allocate empty slice first
		tmpIndex := bytes.NewBuffer([]byte{})
		n_Index, err := io.CopyN(tmpIndex, r, int64(len_Index))
		if err != nil {
			return fmt.Errorf("read Index: expect %d bytes but read %d bytes: %w", len_Index, n_Index, err)
		}
		t.Index = tmpIndex.Bytes()
	} else {
		t.Index = nil
	}
	return nil
}

func (t *Record) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Record) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Record: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *IndexCommonInfo) Revoked() bool {
	return ((t.flags9 & 0x80) >> 7) == 1
}
func (t *IndexCommonInfo) SetRevoked(v bool) {
	if v {
		t.flags9 |= uint8(0x80)
	} else {
		t.flags9 &= ^uint8(0x80)
	}
}
func (t *IndexCommonInfo) Reserved() uint8 {
	return ((t.flags9 & 0x7f) >> 0)
}
func (t *IndexCommonInfo) SetReserved(v uint8) bool {
	if v > 127 {
		return false
	}
	t.flags9 = (t.flags9 & ^uint8(0x7f)) | ((v & 0x7f) << 0)
	return true
}
func (t *IndexCommonInfo) Visit(v VisitorNVCEN) {
	v.Visit(v, "Revoked", (func() uint8 {
		if t.Revoked() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Reserved", t.Reserved())
	v.Visit(v, "NotBefore", &t.NotBefore)
	v.Visit(v, "NotAfter", &t.NotAfter)
	v.Visit(v, "UpdatedAt", &t.UpdatedAt)
}
func (t *IndexCommonInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *IndexCommonInfo) Write(w io.Writer) (err error) {
	if n, err := w.Write([]byte{byte(t.flags9)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.flags9: %w", err)
	}
	if err := t.NotBefore.Write(w); err != nil {
		return fmt.Errorf("encode NotBefore: %w", err)
	}
	if err := t.NotAfter.Write(w); err != nil {
		return fmt.Errorf("encode NotAfter: %w", err)
	}
	if err := t.UpdatedAt.Write(w); err != nil {
		return fmt.Errorf("encode UpdatedAt: %w", err)
	}
	return nil
}
func (t *IndexCommonInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 25))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *IndexCommonInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *IndexCommonInfo) Read(r io.Reader) (err error) {
	tmpflags9 := [1]byte{}
	n_flags9, err := io.ReadFull(r, tmpflags9[:])
	if err != nil {
		return fmt.Errorf("read flags9: expect 1 byte but read %d bytes: %w", n_flags9, err)
	}
	t.flags9 = uint8(tmpflags9[0])
	if err := t.NotBefore.Read(r); err != nil {
		return fmt.Errorf("read NotBefore: %w", err)
	}
	if err := t.NotAfter.Read(r); err != nil {
		return fmt.Errorf("read NotAfter: %w", err)
	}
	if err := t.UpdatedAt.Read(r); err != nil {
		return fmt.Errorf("read UpdatedAt: %w", err)
	}
	return nil
}

func (t *IndexCommonInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *IndexCommonInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode IndexCommonInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *CertIndex) Visit(v VisitorNVCEN) {
	v.Visit(v, "Pointer", &t.Pointer)
	v.Visit(v, "SerialNumber", &t.SerialNumber)
	v.Visit(v, "CertLen", &t.CertLen)
	v.Visit(v, "Common", &t.Common)
	v.Visit(v, "CertificateHash", &t.CertificateHash)
	v.Visit(v, "Name", &t.Name)
}
func (t *CertIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *CertIndex) Write(w io.Writer) (err error) {
	if err := t.Pointer.Write(w); err != nil {
		return fmt.Errorf("encode Pointer: %w", err)
	}
	if err := t.SerialNumber.Write(w); err != nil {
		return fmt.Errorf("encode SerialNumber: %w", err)
	}
	tmp10 := [2]byte{}
	binary.BigEndian.PutUint16(tmp10[:], uint16(t.CertLen))
	if n, err := w.Write(tmp10[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.CertLen: %w", err)
	}
	if err := t.Common.Write(w); err != nil {
		return fmt.Errorf("encode Common: %w", err)
	}
	if err := t.CertificateHash.Write(w); err != nil {
		return fmt.Errorf("encode CertificateHash: %w", err)
	}
	if err := t.Name.Write(w); err != nil {
		return fmt.Errorf("encode Name: %w", err)
	}
	return nil
}
func (t *CertIndex) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 119))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *CertIndex) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *CertIndex) Read(r io.Reader) (err error) {
	if err := t.Pointer.Read(r); err != nil {
		return fmt.Errorf("read Pointer: %w", err)
	}
	if err := t.SerialNumber.Read(r); err != nil {
		return fmt.Errorf("read SerialNumber: %w", err)
	}
	tmpCertLen := [2]byte{}
	n_CertLen, err := io.ReadFull(r, tmpCertLen[:])
	if err != nil {
		return fmt.Errorf("read CertLen: expect 2 bytes but read %d bytes: %w", n_CertLen, err)
	}
	t.CertLen = uint16(binary.BigEndian.Uint16(tmpCertLen[:]))
	if err := t.Common.Read(r); err != nil {
		return fmt.Errorf("read Common: %w", err)
	}
	if err := t.CertificateHash.Read(r); err != nil {
		return fmt.Errorf("read CertificateHash: %w", err)
	}
	if err := t.Name.Read(r); err != nil {
		return fmt.Errorf("read Name: %w", err)
	}
	return nil
}

func (t *CertIndex) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *CertIndex) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode CertIndex: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *KeyPairIndex) Visit(v VisitorNVCEN) {
	v.Visit(v, "PrivLen", &t.PrivLen)
	v.Visit(v, "Cert", &t.Cert)
}
func (t *KeyPairIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *KeyPairIndex) Write(w io.Writer) (err error) {
	tmp11 := [2]byte{}
	binary.BigEndian.PutUint16(tmp11[:], uint16(t.PrivLen))
	if n, err := w.Write(tmp11[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.PrivLen: %w", err)
	}
	if err := t.Cert.Write(w); err != nil {
		return fmt.Errorf("encode Cert: %w", err)
	}
	return nil
}
func (t *KeyPairIndex) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 2))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *KeyPairIndex) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *KeyPairIndex) Read(r io.Reader) (err error) {
	tmpPrivLen := [2]byte{}
	n_PrivLen, err := io.ReadFull(r, tmpPrivLen[:])
	if err != nil {
		return fmt.Errorf("read PrivLen: expect 2 bytes but read %d bytes: %w", n_PrivLen, err)
	}
	t.PrivLen = uint16(binary.BigEndian.Uint16(tmpPrivLen[:]))
	if err := t.Cert.Read(r); err != nil {
		return fmt.Errorf("read Cert: %w", err)
	}
	return nil
}

func (t *KeyPairIndex) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *KeyPairIndex) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode KeyPairIndex: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *KeyPair) SetPrivateKey(v []uint8) bool {
	if len(v) > int(^uint16(0)) {
		return false
	}
	t.PrivLen = uint16(len(v))
	t.PrivateKey = v
	return true
}
func (t *KeyPair) Visit(v VisitorNVCEN) {
	v.Visit(v, "PrivLen", &t.PrivLen)
	v.Visit(v, "PrivateKey", &t.PrivateKey)
	v.Visit(v, "Cert", &t.Cert)
}
func (t *KeyPair) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *KeyPair) Write(w io.Writer) (err error) {
	tmp12 := [2]byte{}
	binary.BigEndian.PutUint16(tmp12[:], uint16(t.PrivLen))
	if n, err := w.Write(tmp12[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.PrivLen: %w", err)
	}
	len_PrivateKey := int(t.PrivLen)
	if len(t.PrivateKey) != len_PrivateKey {
		return fmt.Errorf("encode PrivateKey: expect %d bytes but got %d bytes", len_PrivateKey, len(t.PrivateKey))
	}
	if n, err := w.Write(t.PrivateKey); err != nil || n != len(t.PrivateKey) {
		return fmt.Errorf("encode PrivateKey: %w", err)
	}
	if err := t.Cert.Write(w); err != nil {
		return fmt.Errorf("encode Cert: %w", err)
	}
	return nil
}
func (t *KeyPair) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 2))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *KeyPair) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *KeyPair) Read(r io.Reader) (err error) {
	tmpPrivLen := [2]byte{}
	n_PrivLen, err := io.ReadFull(r, tmpPrivLen[:])
	if err != nil {
		return fmt.Errorf("read PrivLen: expect 2 bytes but read %d bytes: %w", n_PrivLen, err)
	}
	t.PrivLen = uint16(binary.BigEndian.Uint16(tmpPrivLen[:]))
	len_PrivateKey := int(t.PrivLen)
	if len_PrivateKey != 0 {
		// to prevent from allocation attack, allocate empty slice first
		tmpPrivateKey := bytes.NewBuffer([]byte{})
		n_PrivateKey, err := io.CopyN(tmpPrivateKey, r, int64(len_PrivateKey))
		if err != nil {
			return fmt.Errorf("read PrivateKey: expect %d bytes but read %d bytes: %w", len_PrivateKey, n_PrivateKey, err)
		}
		t.PrivateKey = tmpPrivateKey.Bytes()
	} else {
		t.PrivateKey = nil
	}
	if err := t.Cert.Read(r); err != nil {
		return fmt.Errorf("read Cert: %w", err)
	}
	return nil
}

func (t *KeyPair) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *KeyPair) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode KeyPair: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *CAState) Visit(v VisitorNVCEN) {
	v.Visit(v, "SavedTime", &t.SavedTime)
	v.Visit(v, "CurrentSerial", &t.CurrentSerial)
	v.Visit(v, "Ca", &t.Ca)
	v.Visit(v, "ManagerID", &t.ManagerID)
	v.Visit(v, "RecordCounter", &t.RecordCounter)
}
func (t *CAState) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *CAState) Write(w io.Writer) (err error) {
	tmp13 := [8]byte{}
	binary.BigEndian.PutUint64(tmp13[:], uint64(t.SavedTime))
	if n, err := w.Write(tmp13[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.SavedTime: %w", err)
	}
	if n, err := w.Write(t.CurrentSerial[:]); err != nil || n != len(t.CurrentSerial) {
		return fmt.Errorf("encode CurrentSerial: %w", err)
	}
	if err := t.Ca.Write(w); err != nil {
		return fmt.Errorf("encode Ca: %w", err)
	}
	if err := t.ManagerID.Write(w); err != nil {
		return fmt.Errorf("encode ManagerID: %w", err)
	}
	tmp14 := [8]byte{}
	binary.BigEndian.PutUint64(tmp14[:], uint64(t.RecordCounter))
	if n, err := w.Write(tmp14[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.RecordCounter: %w", err)
	}
	return nil
}
func (t *CAState) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 28))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *CAState) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *CAState) Read(r io.Reader) (err error) {
	tmpSavedTime := [8]byte{}
	n_SavedTime, err := io.ReadFull(r, tmpSavedTime[:])
	if err != nil {
		return fmt.Errorf("read SavedTime: expect 8 bytes but read %d bytes: %w", n_SavedTime, err)
	}
	t.SavedTime = uint64(binary.BigEndian.Uint64(tmpSavedTime[:]))
	n_CurrentSerial, err := io.ReadFull(r, t.CurrentSerial[:])
	if err != nil {
		return fmt.Errorf("read CurrentSerial: expect %d bytes but read %d bytes: %w", 20, n_CurrentSerial, err)
	}
	if err := t.Ca.Read(r); err != nil {
		return fmt.Errorf("read Ca: %w", err)
	}
	if err := t.ManagerID.Read(r); err != nil {
		return fmt.Errorf("read ManagerID: %w", err)
	}
	tmpRecordCounter := [8]byte{}
	n_RecordCounter, err := io.ReadFull(r, tmpRecordCounter[:])
	if err != nil {
		return fmt.Errorf("read RecordCounter: expect 8 bytes but read %d bytes: %w", n_RecordCounter, err)
	}
	t.RecordCounter = uint64(binary.BigEndian.Uint64(tmpRecordCounter[:]))
	return nil
}

func (t *CAState) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *CAState) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode CAState: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *IndexFile) Visit(v VisitorNVCEN) {
	v.Visit(v, "Header", &t.Header)
	v.Visit(v, "Records", &t.Records)
}
func (t *IndexFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *IndexFile) Write(w io.Writer) (err error) {
	if err := t.Header.Write(w); err != nil {
		return fmt.Errorf("encode Header: %w", err)
	}
	for _, v := range t.Records {
		if err := v.Write(w); err != nil {
			return fmt.Errorf("encode Records: %w", err)
		}
	}
	return nil
}
func (t *IndexFile) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 36))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *IndexFile) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *IndexFile) Read(r io.Reader) (err error) {
	if err := t.Header.Read(r); err != nil {
		return fmt.Errorf("read Header: %w", err)
	}
	tmp_byte_scanner15_ := bufio.NewReaderSize(r, 1)
	old_r_Records := r
	r = tmp_byte_scanner15_
	for {
		_, err := tmp_byte_scanner15_.ReadByte()
		if err != nil {
			if err != io.EOF {
				return fmt.Errorf("read Records: %w", err)
			}
			break
		}
		if err := tmp_byte_scanner15_.UnreadByte(); err != nil {
			return fmt.Errorf("read Records: unexpected unread error: %w", err)
		}
		var tmp16_ Record
		if err := tmp16_.Read(r); err != nil {
			return fmt.Errorf("read Records: %w", err)
		}
		t.Records = append(t.Records, tmp16_)
	}
	r = old_r_Records
	return nil
}

func (t *IndexFile) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *IndexFile) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode IndexFile: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *BootInfo) PeerIsSelfSigned() bool {
	return ((t.flags17 & 0x80) >> 7) == 1
}
func (t *BootInfo) SetPeerIsSelfSigned(v bool) {
	if v {
		t.flags17 |= uint8(0x80)
	} else {
		t.flags17 &= ^uint8(0x80)
	}
}
func (t *BootInfo) Reserved() uint8 {
	return ((t.flags17 & 0x7f) >> 0)
}
func (t *BootInfo) SetReserved(v uint8) bool {
	if v > 127 {
		return false
	}
	t.flags17 = (t.flags17 & ^uint8(0x7f)) | ((v & 0x7f) << 0)
	return true
}
func (t *union_20_t) isunion18_() {}
func (t *BootInfo) CaCert() *IssuedCert {
	if true == ((func() uint8 {
		if t.PeerIsSelfSigned() {
			return 1
		} else {
			return 0
		}
	}()) == 0) {
		if _, ok := t.union18_.(*union_20_t); !ok {
			return nil // not set
		}
		tmp := IssuedCert(t.union18_.(*union_20_t).CaCert)
		return &tmp
	}
	return nil
}
func (t *BootInfo) SetCaCert(v IssuedCert) bool {
	if true == ((func() uint8 {
		if t.PeerIsSelfSigned() {
			return 1
		} else {
			return 0
		}
	}()) == 0) {
		if _, ok := t.union18_.(*union_20_t); !ok {
			t.union18_ = &union_20_t{}
		}
		t.union18_.(*union_20_t).CaCert = IssuedCert(v)
		return true
	}
	return false
}
func (t *BootInfo) Visit(v VisitorNVCEN) {
	v.Visit(v, "SelfCert", &t.SelfCert)
	v.Visit(v, "PeerCert", &t.PeerCert)
	v.Visit(v, "PeerIsSelfSigned", (func() uint8 {
		if t.PeerIsSelfSigned() {
			return 1
		} else {
			return 0
		}
	}()))
	v.Visit(v, "Reserved", t.Reserved())
	v.Visit(v, "CaCert", (t.CaCert()))
}
func (t *BootInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *BootInfo) Write(w io.Writer) (err error) {
	if err := t.SelfCert.Write(w); err != nil {
		return fmt.Errorf("encode SelfCert: %w", err)
	}
	if err := t.PeerCert.Write(w); err != nil {
		return fmt.Errorf("encode PeerCert: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.flags17)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.flags17: %w", err)
	}
	if (func() uint8 {
		if t.PeerIsSelfSigned() {
			return 1
		} else {
			return 0
		}
	}()) == 0 {
		if _, ok := t.union18_.(*union_20_t); !ok {
			return fmt.Errorf("encode t.union18_: union is not set to union_20_t")
		}
		if err := t.union18_.(*union_20_t).CaCert.Write(w); err != nil {
			return fmt.Errorf("encode CaCert: %w", err)
		}
	}
	return nil
}
func (t *BootInfo) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 0))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *BootInfo) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *BootInfo) Read(r io.Reader) (err error) {
	if err := t.SelfCert.Read(r); err != nil {
		return fmt.Errorf("read SelfCert: %w", err)
	}
	if err := t.PeerCert.Read(r); err != nil {
		return fmt.Errorf("read PeerCert: %w", err)
	}
	tmpflags17 := [1]byte{}
	n_flags17, err := io.ReadFull(r, tmpflags17[:])
	if err != nil {
		return fmt.Errorf("read flags17: expect 1 byte but read %d bytes: %w", n_flags17, err)
	}
	t.flags17 = uint8(tmpflags17[0])
	if (func() uint8 {
		if t.PeerIsSelfSigned() {
			return 1
		} else {
			return 0
		}
	}()) == 0 {
		t.union18_ = &union_20_t{}
		if err := t.union18_.(*union_20_t).CaCert.Read(r); err != nil {
			return fmt.Errorf("read CaCert: %w", err)
		}
	}
	return nil
}

func (t *BootInfo) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *BootInfo) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode BootInfo: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *PrivateKeyIndex) Visit(v VisitorNVCEN) {
	v.Visit(v, "Pointer", &t.Pointer)
	v.Visit(v, "PrivLen", &t.PrivLen)
	v.Visit(v, "Common", &t.Common)
	v.Visit(v, "PrivateKeyHash", &t.PrivateKeyHash)
	v.Visit(v, "Name", &t.Name)
}
func (t *PrivateKeyIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *PrivateKeyIndex) Write(w io.Writer) (err error) {
	if err := t.Pointer.Write(w); err != nil {
		return fmt.Errorf("encode Pointer: %w", err)
	}
	tmp21 := [2]byte{}
	binary.BigEndian.PutUint16(tmp21[:], uint16(t.PrivLen))
	if n, err := w.Write(tmp21[:]); err != nil || n != 2 {
		return fmt.Errorf("encode t.PrivLen: %w", err)
	}
	if err := t.Common.Write(w); err != nil {
		return fmt.Errorf("encode Common: %w", err)
	}
	if err := t.PrivateKeyHash.Write(w); err != nil {
		return fmt.Errorf("encode PrivateKeyHash: %w", err)
	}
	if err := t.Name.Write(w); err != nil {
		return fmt.Errorf("encode Name: %w", err)
	}
	return nil
}
func (t *PrivateKeyIndex) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 99))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *PrivateKeyIndex) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *PrivateKeyIndex) Read(r io.Reader) (err error) {
	if err := t.Pointer.Read(r); err != nil {
		return fmt.Errorf("read Pointer: %w", err)
	}
	tmpPrivLen := [2]byte{}
	n_PrivLen, err := io.ReadFull(r, tmpPrivLen[:])
	if err != nil {
		return fmt.Errorf("read PrivLen: expect 2 bytes but read %d bytes: %w", n_PrivLen, err)
	}
	t.PrivLen = uint16(binary.BigEndian.Uint16(tmpPrivLen[:]))
	if err := t.Common.Read(r); err != nil {
		return fmt.Errorf("read Common: %w", err)
	}
	if err := t.PrivateKeyHash.Read(r); err != nil {
		return fmt.Errorf("read PrivateKeyHash: %w", err)
	}
	if err := t.Name.Read(r); err != nil {
		return fmt.Errorf("read Name: %w", err)
	}
	return nil
}

func (t *PrivateKeyIndex) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *PrivateKeyIndex) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode PrivateKeyIndex: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *BlobIndex) Visit(v VisitorNVCEN) {
	v.Visit(v, "Pointer", &t.Pointer)
	v.Visit(v, "BlobLen", &t.BlobLen)
	v.Visit(v, "Common", &t.Common)
	v.Visit(v, "BlobHash", &t.BlobHash)
	v.Visit(v, "Name", &t.Name)
}
func (t *BlobIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *BlobIndex) Write(w io.Writer) (err error) {
	if err := t.Pointer.Write(w); err != nil {
		return fmt.Errorf("encode Pointer: %w", err)
	}
	tmp22 := [8]byte{}
	binary.BigEndian.PutUint64(tmp22[:], uint64(t.BlobLen))
	if n, err := w.Write(tmp22[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.BlobLen: %w", err)
	}
	if err := t.Common.Write(w); err != nil {
		return fmt.Errorf("encode Common: %w", err)
	}
	if err := t.BlobHash.Write(w); err != nil {
		return fmt.Errorf("encode BlobHash: %w", err)
	}
	if err := t.Name.Write(w); err != nil {
		return fmt.Errorf("encode Name: %w", err)
	}
	return nil
}
func (t *BlobIndex) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 105))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *BlobIndex) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *BlobIndex) Read(r io.Reader) (err error) {
	if err := t.Pointer.Read(r); err != nil {
		return fmt.Errorf("read Pointer: %w", err)
	}
	tmpBlobLen := [8]byte{}
	n_BlobLen, err := io.ReadFull(r, tmpBlobLen[:])
	if err != nil {
		return fmt.Errorf("read BlobLen: expect 8 bytes but read %d bytes: %w", n_BlobLen, err)
	}
	t.BlobLen = uint64(binary.BigEndian.Uint64(tmpBlobLen[:]))
	if err := t.Common.Read(r); err != nil {
		return fmt.Errorf("read Common: %w", err)
	}
	if err := t.BlobHash.Read(r); err != nil {
		return fmt.Errorf("read BlobHash: %w", err)
	}
	if err := t.Name.Read(r); err != nil {
		return fmt.Errorf("read Name: %w", err)
	}
	return nil
}

func (t *BlobIndex) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *BlobIndex) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode BlobIndex: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
func (t *union_25_t) isunion23_() {}
func (t *union_26_t) isunion23_() {}
func (t *union_27_t) isunion23_() {}
func (t *union_28_t) isunion23_() {}
func (t *Index) Blob() *BlobIndex {
	if t.Kind == IndexKind_Cert {
		return nil
	} else if t.Kind == IndexKind_Priv {
		return nil
	} else if t.Kind == IndexKind_Keypair {
		return nil
	} else if t.Kind == IndexKind_Blob {
		if _, ok := t.union23_.(*union_28_t); !ok {
			return nil // not set
		}
		tmp := BlobIndex(t.union23_.(*union_28_t).Blob)
		return &tmp
	}
	return nil
}
func (t *Index) SetBlob(v BlobIndex) bool {
	if t.Kind == IndexKind_Cert {
		return false
	} else if t.Kind == IndexKind_Priv {
		return false
	} else if t.Kind == IndexKind_Keypair {
		return false
	} else if t.Kind == IndexKind_Blob {
		if _, ok := t.union23_.(*union_28_t); !ok {
			t.union23_ = &union_28_t{}
		}
		t.union23_.(*union_28_t).Blob = BlobIndex(v)
		return true
	}
	return false
}
func (t *Index) Cert() *CertIndex {
	if t.Kind == IndexKind_Cert {
		if _, ok := t.union23_.(*union_25_t); !ok {
			return nil // not set
		}
		tmp := CertIndex(t.union23_.(*union_25_t).Cert)
		return &tmp
	}
	return nil
}
func (t *Index) SetCert(v CertIndex) bool {
	if t.Kind == IndexKind_Cert {
		if _, ok := t.union23_.(*union_25_t); !ok {
			t.union23_ = &union_25_t{}
		}
		t.union23_.(*union_25_t).Cert = CertIndex(v)
		return true
	}
	return false
}
func (t *Index) KeyPair() *KeyPairIndex {
	if t.Kind == IndexKind_Cert {
		return nil
	} else if t.Kind == IndexKind_Priv {
		return nil
	} else if t.Kind == IndexKind_Keypair {
		if _, ok := t.union23_.(*union_27_t); !ok {
			return nil // not set
		}
		tmp := KeyPairIndex(t.union23_.(*union_27_t).KeyPair)
		return &tmp
	}
	return nil
}
func (t *Index) SetKeyPair(v KeyPairIndex) bool {
	if t.Kind == IndexKind_Cert {
		return false
	} else if t.Kind == IndexKind_Priv {
		return false
	} else if t.Kind == IndexKind_Keypair {
		if _, ok := t.union23_.(*union_27_t); !ok {
			t.union23_ = &union_27_t{}
		}
		t.union23_.(*union_27_t).KeyPair = KeyPairIndex(v)
		return true
	}
	return false
}
func (t *Index) Priv() *PrivateKeyIndex {
	if t.Kind == IndexKind_Cert {
		return nil
	} else if t.Kind == IndexKind_Priv {
		if _, ok := t.union23_.(*union_26_t); !ok {
			return nil // not set
		}
		tmp := PrivateKeyIndex(t.union23_.(*union_26_t).Priv)
		return &tmp
	}
	return nil
}
func (t *Index) SetPriv(v PrivateKeyIndex) bool {
	if t.Kind == IndexKind_Cert {
		return false
	} else if t.Kind == IndexKind_Priv {
		if _, ok := t.union23_.(*union_26_t); !ok {
			t.union23_ = &union_26_t{}
		}
		t.union23_.(*union_26_t).Priv = PrivateKeyIndex(v)
		return true
	}
	return false
}
func (t *Index) Visit(v VisitorNVCEN) {
	v.Visit(v, "RecordCounter", &t.RecordCounter)
	v.Visit(v, "Kind", &t.Kind)
	v.Visit(v, "Blob", (t.Blob()))
	v.Visit(v, "Cert", (t.Cert()))
	v.Visit(v, "KeyPair", (t.KeyPair()))
	v.Visit(v, "Priv", (t.Priv()))
}
func (t *Index) MarshalJSON() ([]byte, error) {
	return json.Marshal(VisitorNVCENToMap(t))
}
func (t *Index) Write(w io.Writer) (err error) {
	tmp29 := [8]byte{}
	binary.BigEndian.PutUint64(tmp29[:], uint64(t.RecordCounter))
	if n, err := w.Write(tmp29[:]); err != nil || n != 8 {
		return fmt.Errorf("encode t.RecordCounter: %w", err)
	}
	if n, err := w.Write([]byte{byte(t.Kind)}); err != nil || n != 1 {
		return fmt.Errorf("encode t.Kind: %w", err)
	}
	switch {
	case (t.Kind == IndexKind_Cert):
		if _, ok := t.union23_.(*union_25_t); !ok {
			return fmt.Errorf("encode t.union23_: union is not set to union_25_t")
		}
		if err := t.union23_.(*union_25_t).Cert.Write(w); err != nil {
			return fmt.Errorf("encode Cert: %w", err)
		}
	case (t.Kind == IndexKind_Priv):
		if _, ok := t.union23_.(*union_26_t); !ok {
			return fmt.Errorf("encode t.union23_: union is not set to union_26_t")
		}
		if err := t.union23_.(*union_26_t).Priv.Write(w); err != nil {
			return fmt.Errorf("encode Priv: %w", err)
		}
	case (t.Kind == IndexKind_Keypair):
		if _, ok := t.union23_.(*union_27_t); !ok {
			return fmt.Errorf("encode t.union23_: union is not set to union_27_t")
		}
		if err := t.union23_.(*union_27_t).KeyPair.Write(w); err != nil {
			return fmt.Errorf("encode KeyPair: %w", err)
		}
	case (t.Kind == IndexKind_Blob):
		if _, ok := t.union23_.(*union_28_t); !ok {
			return fmt.Errorf("encode t.union23_: union is not set to union_28_t")
		}
		if err := t.union23_.(*union_28_t).Blob.Write(w); err != nil {
			return fmt.Errorf("encode Blob: %w", err)
		}
	}
	return nil
}
func (t *Index) Encode() ([]byte, error) {
	w := bytes.NewBuffer(make([]byte, 0, 9))
	if err := t.Write(w); err != nil {
		return nil, err
	}
	return w.Bytes(), nil
}
func (t *Index) MustEncode() []byte {
	buf, err := t.Encode()
	if err != nil {
		panic(err)
	}
	return buf
}
func (t *Index) Read(r io.Reader) (err error) {
	tmpRecordCounter := [8]byte{}
	n_RecordCounter, err := io.ReadFull(r, tmpRecordCounter[:])
	if err != nil {
		return fmt.Errorf("read RecordCounter: expect 8 bytes but read %d bytes: %w", n_RecordCounter, err)
	}
	t.RecordCounter = uint64(binary.BigEndian.Uint64(tmpRecordCounter[:]))
	tmpKind := [1]byte{}
	n_Kind, err := io.ReadFull(r, tmpKind[:])
	if err != nil {
		return fmt.Errorf("read Kind: expect 1 byte but read %d bytes: %w", n_Kind, err)
	}
	t.Kind = IndexKind(tmpKind[0])
	switch {
	case (t.Kind == IndexKind_Cert):
		t.union23_ = &union_25_t{}
		if err := t.union23_.(*union_25_t).Cert.Read(r); err != nil {
			return fmt.Errorf("read Cert: %w", err)
		}
	case (t.Kind == IndexKind_Priv):
		t.union23_ = &union_26_t{}
		if err := t.union23_.(*union_26_t).Priv.Read(r); err != nil {
			return fmt.Errorf("read Priv: %w", err)
		}
	case (t.Kind == IndexKind_Keypair):
		t.union23_ = &union_27_t{}
		if err := t.union23_.(*union_27_t).KeyPair.Read(r); err != nil {
			return fmt.Errorf("read KeyPair: %w", err)
		}
	case (t.Kind == IndexKind_Blob):
		t.union23_ = &union_28_t{}
		if err := t.union23_.(*union_28_t).Blob.Read(r); err != nil {
			return fmt.Errorf("read Blob: %w", err)
		}
	}
	return nil
}

func (t *Index) Decode(d []byte) (int, error) {
	r := bytes.NewReader(d)
	err := t.Read(r)
	return int(int(r.Size()) - r.Len()), err
}
func (t *Index) DecodeExact(d []byte) error {
	if n, err := t.Decode(d); err != nil {
		return err
	} else if n != len(d) {
		return fmt.Errorf("decode Index: expect %d bytes but got %d bytes", len(d), n)
	}
	return nil
}
