// Code generated by protoc-gen-ksdk. DO NOT EDIT.
package stat

import (
	bytes "bytes"
	fmt "fmt"
	wire "github.com/on-keyday/kscale/protobuf/wire"
	io "io"
	unsafe "unsafe"
)

type StatStreamHeader struct {
	Type string `json:"type,omitempty"`
}

func (p *StatStreamHeader) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Type unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Type = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *StatStreamHeader) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Type unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Type = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *StatStreamHeader) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Type unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Type = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *StatStreamHeader) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Type) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Type))})
		field.SetValueData([]byte(p.Type))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *StatStreamHeader) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Type) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Type))})
		field.SetValueData([]byte(p.Type))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *StatStreamHeader) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Type) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Type))})
		field.SetValueData([]byte(p.Type))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}

type StatBatch struct {
	Stats []*Stats `json:"stats,omitempty"`
}

func (p *StatBatch) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Stats unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *Stats
				tmp = new(Stats)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Stats = append(p.Stats, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *StatBatch) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Stats unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *Stats
				tmp = new(Stats)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Stats = append(p.Stats, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *StatBatch) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Stats unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *Stats
				tmp = new(Stats)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Stats = append(p.Stats, tmp)
			}
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *StatBatch) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Stats {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *StatBatch) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Stats {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *StatBatch) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Stats {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return nil, err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}

type StatReport struct {
	Body *Stats `json:"body,omitempty"`
}

func (p *StatReport) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Body unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Body = new(Stats)
			if err := p.Body.Decode((*val)); err != nil {
				return err
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *StatReport) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Body unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Body = new(Stats)
			if err := p.Body.Decode((*val)); err != nil {
				return err
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *StatReport) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Body unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Body = new(Stats)
			if err := p.Body.Decode((*val)); err != nil {
				return err
			}
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *StatReport) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if p.Body != nil {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := p.Body.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *StatReport) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if p.Body != nil {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := p.Body.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *StatReport) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	if p.Body != nil {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := p.Body.Append(mBuf); err != nil {
				return nil, err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}
