package generator

import (
	"bytes"
	"path/filepath"
)

// GenerateServiceRegister emits service/register_gen.go: a GateDeps bundle of the
// control-plane singletons every gated adapter needs, plus a Register<R> helper
// per rpc_service resource that wraps a business handler (Inner) in its generated
// <R>Gated (authz + audit gate) and registers it. This collapses cmd/controlplane's
// ~14 identical Register*ServiceServer{Inner, Controller, Resource, Root, Audit}
// blocks to one line each — only the resource-specific Inner stays hand-written —
// and makes it impossible to register a gate with a mismatched Resource/Root/Audit
// (which would be a silent authz hole).
func GenerateServiceRegister(input *Input) []GatedAdapterFile {
	var buf bytes.Buffer
	w := &Writer{W: &buf}
	w.Printf("// Code generated by kscale/access/generator. DO NOT EDIT.\n")
	w.Printf("package service\n\n")
	w.Printf("import (\n")
	w.Indented(func(w *Writer) {
		w.Printf("%q\n", "github.com/on-keyday/kscale/access")
		w.Printf("%q\n", "github.com/on-keyday/kscale/access/audit")
		w.Printf("%q\n", "github.com/on-keyday/kscale/access/predefined")
		w.Printf("pb %q\n", "github.com/on-keyday/kscale/protobuf/proto")
		w.Printf("%q\n", "github.com/on-keyday/kscale/rpc")
	})
	w.Printf(")\n\n")

	w.Printf("// GateDeps bundles the control-plane singletons shared by every gated\n")
	w.Printf("// service adapter, so a resource's registration is Register<R>(mgr, gd, inner).\n")
	w.Printf("type GateDeps struct {\n")
	w.Indented(func(w *Writer) {
		w.Printf("Controller access.AccessController\n")
		w.Printf("Root       access.RootAuthority\n")
		w.Printf("Audit      audit.Audit\n")
		w.Printf("Resources  map[string]access.ResourceTemplate // predefined.ResourceMap()\n")
	})
	w.Printf("}\n\n")

	for i := range input.Definition.Resources {
		r := &input.Definition.Resources[i]
		if !r.generatesGate() {
			continue
		}
		svc := toCamelCase(r.Name)
		w.Printf("// Register%s wraps inner in %sGated (authz + audit) and registers it.\n", svc, svc)
		w.Printf("func Register%s(mgr *rpc.RPCManager, gd GateDeps, inner pb.%sServiceServer) {\n", svc, svc)
		w.Indented(func(w *Writer) {
			w.Printf("pb.Register%sServiceServer(mgr, &%sGated{\n", svc, svc)
			w.Indented(func(w *Writer) {
				w.Printf("Inner:      inner,\n")
				w.Printf("Controller: gd.Controller,\n")
				w.Printf("Resource:   gd.Resources[predefined.Resource%s],\n", svc)
				w.Printf("Root:       gd.Root,\n")
				w.Printf("Audit:      gd.Audit,\n")
			})
			w.Printf("})\n")
		})
		w.Printf("}\n\n")
	}

	return []GatedAdapterFile{{
		Path:    filepath.Join("service", "register_gen.go"),
		Content: buf.String(),
	}}
}
