// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/sample.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 様々なWire Typeを含むメッセージ
type Sample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wire Type 0: Varint
	Id     int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Active bool  `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	// Wire Type 2: Length-delimited
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Wire Type 1: Fixed64
	BigVal uint64  `protobuf:"fixed64,5,opt,name=big_val,json=bigVal,proto3" json:"big_val,omitempty"`
	Score  float64 `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	// Wire Type 5: Fixed32
	SmallVal uint32  `protobuf:"fixed32,7,opt,name=small_val,json=smallVal,proto3" json:"small_val,omitempty"`
	Ratio    float32 `protobuf:"fixed32,8,opt,name=ratio,proto3" json:"ratio,omitempty"`
	// 入れ子のメッセージ (Wire Type 2)
	Inner *InnerMessage `protobuf:"bytes,9,opt,name=inner,proto3" json:"inner,omitempty"`
	// 繰り返しフィールド (Packedの場合は Wire Type 2)
	Numbers []int32         `protobuf:"varint,10,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Help    []*InnerMessage `protobuf:"bytes,11,rep,name=help,proto3" json:"help,omitempty"`
	// Types that are valid to be assigned to Item:
	//
	//	*Sample_Why
	//	*Sample_Hage
	Item          isSample_Item            `protobuf_oneof:"item"`
	Boke          *float32                 `protobuf:"fixed32,14,opt,name=boke,proto3,oneof" json:"boke,omitempty"`
	Demo          map[string]*InnerMessage `protobuf:"bytes,15,rep,name=demo,proto3" json:"demo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_proto_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_proto_sample_proto_rawDescGZIP(), []int{0}
}

func (x *Sample) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sample) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Sample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sample) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Sample) GetBigVal() uint64 {
	if x != nil {
		return x.BigVal
	}
	return 0
}

func (x *Sample) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Sample) GetSmallVal() uint32 {
	if x != nil {
		return x.SmallVal
	}
	return 0
}

func (x *Sample) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *Sample) GetInner() *InnerMessage {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *Sample) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *Sample) GetHelp() []*InnerMessage {
	if x != nil {
		return x.Help
	}
	return nil
}

func (x *Sample) GetItem() isSample_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Sample) GetWhy() float32 {
	if x != nil {
		if x, ok := x.Item.(*Sample_Why); ok {
			return x.Why
		}
	}
	return 0
}

func (x *Sample) GetHage() *InnerMessage {
	if x != nil {
		if x, ok := x.Item.(*Sample_Hage); ok {
			return x.Hage
		}
	}
	return nil
}

func (x *Sample) GetBoke() float32 {
	if x != nil && x.Boke != nil {
		return *x.Boke
	}
	return 0
}

func (x *Sample) GetDemo() map[string]*InnerMessage {
	if x != nil {
		return x.Demo
	}
	return nil
}

type isSample_Item interface {
	isSample_Item()
}

type Sample_Why struct {
	Why float32 `protobuf:"fixed32,12,opt,name=why,proto3,oneof"`
}

type Sample_Hage struct {
	Hage *InnerMessage `protobuf:"bytes,13,opt,name=hage,proto3,oneof"`
}

func (*Sample_Why) isSample_Item() {}

func (*Sample_Hage) isSample_Item() {}

type InnerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerMessage) Reset() {
	*x = InnerMessage{}
	mi := &file_proto_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerMessage) ProtoMessage() {}

func (x *InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerMessage.ProtoReflect.Descriptor instead.
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return file_proto_sample_proto_rawDescGZIP(), []int{1}
}

func (x *InnerMessage) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_proto_sample_proto protoreflect.FileDescriptor

const file_proto_sample_proto_rawDesc = "" +
	"\n" +
	"\x12proto/sample.proto\x12\x06sample\"\x97\x04\n" +
	"\x06Sample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x17\n" +
	"\abig_val\x18\x05 \x01(\x06R\x06bigVal\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x12\x1b\n" +
	"\tsmall_val\x18\a \x01(\aR\bsmallVal\x12\x14\n" +
	"\x05ratio\x18\b \x01(\x02R\x05ratio\x12*\n" +
	"\x05inner\x18\t \x01(\v2\x14.sample.InnerMessageR\x05inner\x12\x18\n" +
	"\anumbers\x18\n" +
	" \x03(\x05R\anumbers\x12(\n" +
	"\x04help\x18\v \x03(\v2\x14.sample.InnerMessageR\x04help\x12\x12\n" +
	"\x03why\x18\f \x01(\x02H\x00R\x03why\x12*\n" +
	"\x04hage\x18\r \x01(\v2\x14.sample.InnerMessageH\x00R\x04hage\x12\x17\n" +
	"\x04boke\x18\x0e \x01(\x02H\x01R\x04boke\x88\x01\x01\x12,\n" +
	"\x04demo\x18\x0f \x03(\v2\x18.sample.Sample.DemoEntryR\x04demo\x1aM\n" +
	"\tDemoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.sample.InnerMessageR\x05value:\x028\x01B\x06\n" +
	"\x04itemB\a\n" +
	"\x05_boke\"&\n" +
	"\fInnerMessage\x12\x16\n" +
	"\x06detail\x18\x01 \x01(\tR\x06detailB#Z!github.com/example/protobuf/protob\x06proto3"

var (
	file_proto_sample_proto_rawDescOnce sync.Once
	file_proto_sample_proto_rawDescData []byte
)

func file_proto_sample_proto_rawDescGZIP() []byte {
	file_proto_sample_proto_rawDescOnce.Do(func() {
		file_proto_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sample_proto_rawDesc), len(file_proto_sample_proto_rawDesc)))
	})
	return file_proto_sample_proto_rawDescData
}

var file_proto_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sample_proto_goTypes = []any{
	(*Sample)(nil),       // 0: sample.Sample
	(*InnerMessage)(nil), // 1: sample.InnerMessage
	nil,                  // 2: sample.Sample.DemoEntry
}
var file_proto_sample_proto_depIdxs = []int32{
	1, // 0: sample.Sample.inner:type_name -> sample.InnerMessage
	1, // 1: sample.Sample.help:type_name -> sample.InnerMessage
	1, // 2: sample.Sample.hage:type_name -> sample.InnerMessage
	2, // 3: sample.Sample.demo:type_name -> sample.Sample.DemoEntry
	1, // 4: sample.Sample.DemoEntry.value:type_name -> sample.InnerMessage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_sample_proto_init() }
func file_proto_sample_proto_init() {
	if File_proto_sample_proto != nil {
		return
	}
	file_proto_sample_proto_msgTypes[0].OneofWrappers = []any{
		(*Sample_Why)(nil),
		(*Sample_Hage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sample_proto_rawDesc), len(file_proto_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sample_proto_goTypes,
		DependencyIndexes: file_proto_sample_proto_depIdxs,
		MessageInfos:      file_proto_sample_proto_msgTypes,
	}.Build()
	File_proto_sample_proto = out.File
	file_proto_sample_proto_goTypes = nil
	file_proto_sample_proto_depIdxs = nil
}
