// Code generated by protoc-gen-ksdk. DO NOT EDIT.
package trsf_proxy

import (
	bytes "bytes"
	fmt "fmt"
	wire "github.com/on-keyday/kscale/protobuf/wire"
	io "io"
	unsafe "unsafe"
)

type DialPreface struct {
	Network string `json:"network,omitempty"`
	Addr    string `json:"addr,omitempty"`
}

func (p *DialPreface) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Network unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Network = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Addr unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Addr = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *DialPreface) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Network unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Network = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Addr unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Addr = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *DialPreface) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Network unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Network = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Addr unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Addr = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *DialPreface) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Network) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Network))})
		field.SetValueData([]byte(p.Network))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if len(p.Addr) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Addr))})
		field.SetValueData([]byte(p.Addr))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *DialPreface) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Network) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Network))})
		field.SetValueData([]byte(p.Network))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if len(p.Addr) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Addr))})
		field.SetValueData([]byte(p.Addr))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *DialPreface) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Network) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Network))})
		field.SetValueData([]byte(p.Network))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(2)
	if len(p.Addr) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Addr))})
		field.SetValueData([]byte(p.Addr))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}
