// Code generated by kscale/access/generator. DO NOT EDIT.
package reconcile

import (
	"context"
	"log/slog"
	"time"

	"github.com/on-keyday/kscale/dpbroker"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
	pbstat "github.com/on-keyday/kscale/protobuf/proto/stat"
	"github.com/on-keyday/kscale/rpc"
)

// InterfaceDesired is the desired-state source the Interface controller reconciles.
type InterfaceDesired interface {
	Desired() []*pbaccess.ResourceInterfaceActionGetResponseDTO
	OnChange(func())
}

// Interface wires the per-node reconcile loop: each desired item targets nodes via a
// selector (node: a node, a "<dp_type>/*" group, or "*"). Each node gets the
// value of its MOST SPECIFIC matching selector (node > group > *) via DataplaneService.BindInterface,
// on desired change and on node connect.
func Interface(ctx context.Context, store InterfaceDesired, broker *dpbroker.Broker, status *Status, logger *slog.Logger) {
	apply := func(dpType string, p *peer.Peer) {
		if !dpbroker.Matches("*", dpType) {
			return
		}
		// most-specific matching selector wins (node > group > *).
		var best *pbaccess.ResourceInterfaceActionGetResponseDTO
		bestSpec := 0
		for _, item := range store.Desired() {
			if spec := broker.MatchSpecificity(item.Node, dpType, p); spec > bestSpec {
				bestSpec, best = spec, item
			}
		}
		if best == nil {
			return
		}
		c := pb.NewDataplaneServiceClient(rpc.NewTrsfStreamSource(p.Streams(), logger))
		_, err := c.BindInterface(ctx, &pb.DataplaneServiceBindInterfaceRequest{Interface: best.Interface})
		status.Record("interface", p.CommonName(), time.Now(), err)
		if err != nil {
			logger.Error("reconcile interface: BindInterface failed", "node", best.Node, "item", best.Interface, "error", err)
		}
	}
	store.OnChange(func() { broker.ForEachNode(apply) })
	broker.OnConnect(apply)
}

// InterfaceStatSource is the per-node stat snapshot the observer reads.
type InterfaceStatSource interface {
	Get(commonName string) *pbstat.StatBatch
}

// InterfaceObserver reports the observed status of a Interface: the nodes whose latest
// reported stats list it at CdnAppRealtime.BoundIfaces.
type InterfaceObserver struct {
	Cache  InterfaceStatSource
	Broker *dpbroker.Broker
}

func NewInterfaceObserver(cache InterfaceStatSource, broker *dpbroker.Broker) *InterfaceObserver {
	return &InterfaceObserver{Cache: cache, Broker: broker}
}

// AppliedNodes returns the nodes whose reported state includes item.
func (o *InterfaceObserver) AppliedNodes(item string) []string {
	var nodes []string
	for _, ni := range o.Broker.Nodes() {
		for _, s := range o.Cache.Get(ni.CommonName).Stats {
			if s.CdnAppRealtime == nil || s.CdnAppRealtime.BoundIfaces == nil {
				continue
			}
			for _, v := range s.CdnAppRealtime.BoundIfaces.Items {
				if v == item {
					nodes = append(nodes, ni.CommonName)
				}
			}
		}
	}
	return nodes
}

// ObservedSets returns each connected node's reported items at CdnAppRealtime.BoundIfaces
// (actual state, for drift detection against desired).
func (o *InterfaceObserver) ObservedSets() map[string][]string {
	out := map[string][]string{}
	for _, ni := range o.Broker.Nodes() {
		for _, s := range o.Cache.Get(ni.CommonName).Stats {
			if s.CdnAppRealtime == nil || s.CdnAppRealtime.BoundIfaces == nil {
				continue
			}
			out[ni.CommonName] = append(out[ni.CommonName], s.CdnAppRealtime.BoundIfaces.Items...)
		}
	}
	return out
}
