// Code generated by kscale/access/generator. DO NOT EDIT.
package reconcile

import (
	"context"
	"log/slog"
	"time"

	"github.com/on-keyday/kscale/dpbroker"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
	"github.com/on-keyday/kscale/rpc"
)

// L4LbObjectDesired is the desired-state source the L4LbObject controller reconciles.
type L4LbObjectDesired interface {
	Desired() []*pbaccess.ResourceL4LbObjectActionGetResponseDTO
	OnChange(func())
}

// L4LbObject wires the per-node reconcile loop: each desired item targets nodes via a
// selector (node: a node, a "<dp_type>/*" group, or "*"). Each node gets the
// value of its MOST SPECIFIC matching selector (node > group > *) via DataplaneService.SetBalancerObject,
// on desired change and on node connect.
func L4LbObject(ctx context.Context, store L4LbObjectDesired, broker *dpbroker.Broker, status *Status, logger *slog.Logger) {
	apply := func(dpType string, p *peer.Peer) {
		if !dpbroker.Matches("l4lb", dpType) {
			return
		}
		// most-specific matching selector wins (node > group > *).
		var best *pbaccess.ResourceL4LbObjectActionGetResponseDTO
		bestSpec := 0
		for _, item := range store.Desired() {
			if spec := broker.MatchSpecificity(item.Node, dpType, p); spec > bestSpec {
				bestSpec, best = spec, item
			}
		}
		if best == nil {
			return
		}
		c := pb.NewDataplaneServiceClient(rpc.NewTrsfStreamSource(p.Streams(), logger))
		_, err := c.SetBalancerObject(ctx, &pb.DataplaneServiceSetBalancerObjectRequest{Object: best.Object, CryptoObject: best.CryptoObject, PinDir: best.PinDir})
		status.Record("l4lb_object", p.CommonName(), time.Now(), err)
		if err != nil {
			logger.Error("reconcile l4lb_object: SetBalancerObject failed", "node", best.Node, "error", err)
		}
	}
	store.OnChange(func() { broker.ForEachNode(apply) })
	broker.OnConnect(apply)
}
