// Code generated by kscale/access/generator. DO NOT EDIT.
package reconcile

import (
	"context"
	"log/slog"
	"time"

	"github.com/on-keyday/kscale/dpbroker"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
	"github.com/on-keyday/kscale/rpc"
)

// PopcacheConfigDesired is the desired-state source the PopcacheConfig controller reconciles.
type PopcacheConfigDesired interface {
	Desired() []*pbaccess.ResourcePopcacheConfigActionGetResponseDTO
	OnChange(func())
}

// PopcacheConfig wires the reconcile loop: push the desired popcache_config set to every "popcache"
// dataplane node via PopcacheControlService.ApplyConfig, on desired change and on node connect.
func PopcacheConfig(ctx context.Context, store PopcacheConfigDesired, broker *dpbroker.Broker, status *Status, logger *slog.Logger) {
	push := func(p *peer.Peer) {
		c := pb.NewPopcacheControlServiceClient(rpc.NewTrsfStreamSource(p.Streams(), logger))
		var pushErr error
		for _, item := range store.Desired() {
			if _, err := c.ApplyConfig(ctx, &pb.PopcacheControlServiceApplyConfigRequest{Origin: item.Origin, Port: item.HttpPort, HttpsPort: item.HttpsPort, Http3Port: item.Http3Port, QlogEnabled: item.QlogEnabled, WasmComputeDefaultMs: item.WasmComputeDefaultMs, WasmComputeMaxMs: item.WasmComputeMaxMs, CertPath: item.CertPath, KeyPath: item.KeyPath}); err != nil {
				logger.Error("reconcile popcache_config: ApplyConfig failed", "item", item.Name, "error", err)
				pushErr = err
			}
		}
		status.Record("popcache_config", p.CommonName(), time.Now(), pushErr)
	}
	store.OnChange(func() {
		for _, p := range broker.List("popcache") {
			push(p)
		}
	})
	broker.OnConnect(func(dpType string, p *peer.Peer) {
		if dpbroker.Matches("popcache", dpType) {
			push(p) // converge the new node to current desired state
		}
	})
}
