// Code generated by kscale/access/generator. DO NOT EDIT.
package reconcile

import (
	"context"
	"log/slog"
	"time"

	"github.com/on-keyday/kscale/dpbroker"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
	"github.com/on-keyday/kscale/protobuf/wkt"
	"github.com/on-keyday/kscale/rpc"
)

// WasmModuleDesired is the desired-state source the WasmModule controller reconciles.
type WasmModuleDesired interface {
	Desired() []*pbaccess.ResourceWasmModuleActionGetResponseDTO
	OnChange(func())
}

// WasmModule wires the reconcile loop: push the desired wasm_module set to every "popcache"
// dataplane node via WasmService.Register, on desired change and on node connect.
func WasmModule(ctx context.Context, store WasmModuleDesired, broker *dpbroker.Broker, status *Status, logger *slog.Logger) {
	push := func(p *peer.Peer) {
		c := pb.NewWasmServiceClient(rpc.NewTrsfStreamSource(p.Streams(), logger))
		var pushErr error
		for _, item := range store.Desired() {
			if _, err := c.Register(ctx, &pb.WasmServiceRegisterRequest{Id: item.ModuleId, BinaryPath: item.FilePath, Method: item.Method, Path: item.Path, MatchType: item.MatchType, AllowedHosts: item.AllowedHosts, ComputeBudgetMs: item.ComputeBudgetMs}); err != nil {
				logger.Error("reconcile wasm_module: Register failed", "item", item.ModuleId, "error", err)
				pushErr = err
			}
		}
		// prune: remove anything on the node no longer in the desired set.
		desired := map[uint32]bool{}
		for _, item := range store.Desired() {
			desired[item.ModuleId] = true
		}
		if resp, err := c.ListAttached(ctx, &wkt.Empty{}); err == nil {
			for _, actual := range resp.Info {
				if !desired[actual.Id] {
					if _, err := c.Unregister(ctx, &pb.WasmServiceUnregisterRequest{Id: actual.Id}); err != nil {
						logger.Error("reconcile wasm_module: Unregister failed", "key", actual.Id, "error", err)
					}
				}
			}
		}
		status.Record("wasm_module", p.CommonName(), time.Now(), pushErr)
	}
	store.OnChange(func() {
		for _, p := range broker.List("popcache") {
			push(p)
		}
	})
	broker.OnConnect(func(dpType string, p *peer.Peer) {
		if dpbroker.Matches("popcache", dpType) {
			push(p) // converge the new node to current desired state
		}
	})
}
