// Code generated by kscale/access/generator. DO NOT EDIT.
package reconcile

import (
	"context"
	"log/slog"
	"time"

	"github.com/on-keyday/kscale/dpbroker"
	"github.com/on-keyday/kscale/peer"
	pb "github.com/on-keyday/kscale/protobuf/proto"
	pbaccess "github.com/on-keyday/kscale/protobuf/proto/access"
	"github.com/on-keyday/kscale/rpc"
)

// WorkloadNetdpObjectDesired is the desired-state source the WorkloadNetdpObject controller reconciles.
type WorkloadNetdpObjectDesired interface {
	Desired() []*pbaccess.ResourceWorkloadNetdpObjectActionGetResponseDTO
	OnChange(func())
}

// WorkloadNetdpObject wires the per-node reconcile loop: each desired item targets nodes via a
// selector (node: a node, a "<dp_type>/*" group, or "*"). Each node gets the
// value of its MOST SPECIFIC matching selector (node > group > *) via WorkloadService.SetNetdpObject,
// on desired change and on node connect.
func WorkloadNetdpObject(ctx context.Context, store WorkloadNetdpObjectDesired, broker *dpbroker.Broker, status *Status, logger *slog.Logger) {
	apply := func(dpType string, p *peer.Peer) {
		if !dpbroker.Matches("workload", dpType) {
			return
		}
		// most-specific matching selector wins (node > group > *).
		var best *pbaccess.ResourceWorkloadNetdpObjectActionGetResponseDTO
		bestSpec := 0
		for _, item := range store.Desired() {
			if spec := broker.MatchSpecificity(item.Node, dpType, p); spec > bestSpec {
				bestSpec, best = spec, item
			}
		}
		if best == nil {
			return
		}
		c := pb.NewWorkloadServiceClient(rpc.NewTrsfStreamSource(p.Streams(), logger))
		_, err := c.SetNetdpObject(ctx, &pb.WorkloadServiceSetNetdpObjectRequest{Object: best.Object})
		status.Record("workload_netdp_object", p.CommonName(), time.Now(), err)
		if err != nil {
			logger.Error("reconcile workload_netdp_object: SetNetdpObject failed", "node", best.Node, "error", err)
		}
	}
	store.OnChange(func() { broker.ForEachNode(apply) })
	broker.OnConnect(apply)
}
