// Code generated by protoc-gen-ksdk. DO NOT EDIT.
package wkt

import (
	bytes "bytes"
	fmt "fmt"
	wire "github.com/on-keyday/kscale/protobuf/wire"
	io "io"
)

type Timestamp struct {
	Seconds int64 `json:"seconds,omitempty"`
	Nanos   int32 `json:"nanos,omitempty"`
}

func (p *Timestamp) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Seconds unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Seconds = int64((*val).Value)
		case 2:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Nanos unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Nanos = int32((*val).Value)
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *Timestamp) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Seconds unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Seconds = int64((*val).Value)
		case 2:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Nanos unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Nanos = int32((*val).Value)
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *Timestamp) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Seconds unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Seconds = int64((*val).Value)
		case 2:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Nanos unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Nanos = int32((*val).Value)
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *Timestamp) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if p.Seconds != 0 {
		field.Tag.SetType(wire.WireType_Varint)
		field.SetValueVi(wire.Varint{Value: uint64(p.Seconds)})
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if p.Nanos != 0 {
		field.Tag.SetType(wire.WireType_Varint)
		field.SetValueVi(wire.Varint{Value: uint64(int32(p.Nanos))})
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *Timestamp) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if p.Seconds != 0 {
		field.Tag.SetType(wire.WireType_Varint)
		field.SetValueVi(wire.Varint{Value: uint64(p.Seconds)})
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if p.Nanos != 0 {
		field.Tag.SetType(wire.WireType_Varint)
		field.SetValueVi(wire.Varint{Value: uint64(int32(p.Nanos))})
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *Timestamp) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	if p.Seconds != 0 {
		field.Tag.SetType(wire.WireType_Varint)
		field.SetValueVi(wire.Varint{Value: uint64(p.Seconds)})
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(2)
	if p.Nanos != 0 {
		field.Tag.SetType(wire.WireType_Varint)
		field.SetValueVi(wire.Varint{Value: uint64(int32(p.Nanos))})
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}
