// Code generated by protoc-gen-ksdk. DO NOT EDIT.
package proto

import (
	bytes "bytes"
	context "context"
	errors "errors"
	fmt "fmt"
	wire "github.com/on-keyday/kscale/protobuf/wire"
	wkt "github.com/on-keyday/kscale/protobuf/wkt"
	rpc "github.com/on-keyday/kscale/rpc"
	io "io"
	unsafe "unsafe"
)

type WorkloadServiceContainerSpec struct {
	Name    string   `json:"name,omitempty"`
	Image   string   `json:"image,omitempty"`
	Command []string `json:"command,omitempty"`
	Args    []string `json:"args,omitempty"`
	Env     []string `json:"env,omitempty"`
	Mounts  []string `json:"mounts,omitempty"`
	Restart string   `json:"restart,omitempty"`
	Network string   `json:"network,omitempty"`
	Ports   []string `json:"ports,omitempty"`
}

func (p *WorkloadServiceContainerSpec) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Name unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Name = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Image unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Image = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 3:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Command unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Command = append(p.Command, tmp)
			}
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Args unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Args = append(p.Args, tmp)
			}
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Env unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Env = append(p.Env, tmp)
			}
		case 6:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Mounts unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Mounts = append(p.Mounts, tmp)
			}
		case 7:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Restart unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Restart = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 8:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Network unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Network = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 9:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Ports unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Ports = append(p.Ports, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceContainerSpec) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Name unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Name = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Image unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Image = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 3:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Command unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Command = append(p.Command, tmp)
			}
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Args unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Args = append(p.Args, tmp)
			}
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Env unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Env = append(p.Env, tmp)
			}
		case 6:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Mounts unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Mounts = append(p.Mounts, tmp)
			}
		case 7:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Restart unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Restart = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 8:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Network unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Network = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 9:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Ports unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Ports = append(p.Ports, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceContainerSpec) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Name unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Name = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Image unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Image = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 3:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Command unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Command = append(p.Command, tmp)
			}
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Args unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Args = append(p.Args, tmp)
			}
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Env unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Env = append(p.Env, tmp)
			}
		case 6:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Mounts unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Mounts = append(p.Mounts, tmp)
			}
		case 7:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Restart unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Restart = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 8:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Network unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Network = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 9:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Ports unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Ports = append(p.Ports, tmp)
			}
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *WorkloadServiceContainerSpec) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Name) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Name))})
		field.SetValueData([]byte(p.Name))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if len(p.Image) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Image))})
		field.SetValueData([]byte(p.Image))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(3)
	for _, v := range p.Command {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(4)
	for _, v := range p.Args {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(5)
	for _, v := range p.Env {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(6)
	for _, v := range p.Mounts {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(7)
	if len(p.Restart) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Restart))})
		field.SetValueData([]byte(p.Restart))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(8)
	if len(p.Network) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Network))})
		field.SetValueData([]byte(p.Network))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(9)
	for _, v := range p.Ports {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceContainerSpec) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Name) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Name))})
		field.SetValueData([]byte(p.Name))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if len(p.Image) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Image))})
		field.SetValueData([]byte(p.Image))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(3)
	for _, v := range p.Command {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(4)
	for _, v := range p.Args {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(5)
	for _, v := range p.Env {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(6)
	for _, v := range p.Mounts {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(7)
	if len(p.Restart) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Restart))})
		field.SetValueData([]byte(p.Restart))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(8)
	if len(p.Network) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Network))})
		field.SetValueData([]byte(p.Network))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(9)
	for _, v := range p.Ports {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceContainerSpec) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Name) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Name))})
		field.SetValueData([]byte(p.Name))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(2)
	if len(p.Image) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Image))})
		field.SetValueData([]byte(p.Image))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(3)
	for _, v := range p.Command {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(4)
	for _, v := range p.Args {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(5)
	for _, v := range p.Env {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(6)
	for _, v := range p.Mounts {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(7)
	if len(p.Restart) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Restart))})
		field.SetValueData([]byte(p.Restart))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(8)
	if len(p.Network) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Network))})
		field.SetValueData([]byte(p.Network))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(9)
	for _, v := range p.Ports {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}

type WorkloadServiceApplyContainersRequest struct {
	Containers []*WorkloadServiceContainerSpec `json:"containers,omitempty"`
}

func (p *WorkloadServiceApplyContainersRequest) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Containers unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *WorkloadServiceContainerSpec
				tmp = new(WorkloadServiceContainerSpec)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Containers = append(p.Containers, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceApplyContainersRequest) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Containers unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *WorkloadServiceContainerSpec
				tmp = new(WorkloadServiceContainerSpec)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Containers = append(p.Containers, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceApplyContainersRequest) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Containers unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *WorkloadServiceContainerSpec
				tmp = new(WorkloadServiceContainerSpec)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Containers = append(p.Containers, tmp)
			}
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *WorkloadServiceApplyContainersRequest) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Containers {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceApplyContainersRequest) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Containers {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceApplyContainersRequest) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Containers {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return nil, err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}

type WorkloadServiceContainerStatus struct {
	Name         string `json:"name,omitempty"`
	ContainerId  string `json:"container_id,omitempty"`
	Image        string `json:"image,omitempty"`
	State        string `json:"state,omitempty"`
	PodSandboxId string `json:"pod_sandbox_id,omitempty"`
}

func (p *WorkloadServiceContainerStatus) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Name unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Name = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field ContainerId unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.ContainerId = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 3:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Image unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Image = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field State unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.State = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field PodSandboxId unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.PodSandboxId = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceContainerStatus) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Name unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Name = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field ContainerId unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.ContainerId = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 3:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Image unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Image = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field State unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.State = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field PodSandboxId unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.PodSandboxId = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceContainerStatus) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Name unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Name = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field ContainerId unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.ContainerId = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 3:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Image unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Image = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field State unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.State = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field PodSandboxId unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.PodSandboxId = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *WorkloadServiceContainerStatus) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Name) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Name))})
		field.SetValueData([]byte(p.Name))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if len(p.ContainerId) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.ContainerId))})
		field.SetValueData([]byte(p.ContainerId))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(3)
	if len(p.Image) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Image))})
		field.SetValueData([]byte(p.Image))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(4)
	if len(p.State) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.State))})
		field.SetValueData([]byte(p.State))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(5)
	if len(p.PodSandboxId) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.PodSandboxId))})
		field.SetValueData([]byte(p.PodSandboxId))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceContainerStatus) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Name) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Name))})
		field.SetValueData([]byte(p.Name))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	if len(p.ContainerId) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.ContainerId))})
		field.SetValueData([]byte(p.ContainerId))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(3)
	if len(p.Image) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Image))})
		field.SetValueData([]byte(p.Image))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(4)
	if len(p.State) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.State))})
		field.SetValueData([]byte(p.State))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(5)
	if len(p.PodSandboxId) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.PodSandboxId))})
		field.SetValueData([]byte(p.PodSandboxId))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceContainerStatus) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Name) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Name))})
		field.SetValueData([]byte(p.Name))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(2)
	if len(p.ContainerId) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.ContainerId))})
		field.SetValueData([]byte(p.ContainerId))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(3)
	if len(p.Image) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Image))})
		field.SetValueData([]byte(p.Image))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(4)
	if len(p.State) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.State))})
		field.SetValueData([]byte(p.State))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(5)
	if len(p.PodSandboxId) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.PodSandboxId))})
		field.SetValueData([]byte(p.PodSandboxId))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}

type WorkloadServiceListContainersResponse struct {
	Containers []*WorkloadServiceContainerStatus `json:"containers,omitempty"`
}

func (p *WorkloadServiceListContainersResponse) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Containers unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *WorkloadServiceContainerStatus
				tmp = new(WorkloadServiceContainerStatus)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Containers = append(p.Containers, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceListContainersResponse) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Containers unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *WorkloadServiceContainerStatus
				tmp = new(WorkloadServiceContainerStatus)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Containers = append(p.Containers, tmp)
			}
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *WorkloadServiceListContainersResponse) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Containers unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp *WorkloadServiceContainerStatus
				tmp = new(WorkloadServiceContainerStatus)
				if err := tmp.Decode((*val)); err != nil {
					return err
				}
				p.Containers = append(p.Containers, tmp)
			}
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *WorkloadServiceListContainersResponse) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Containers {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceListContainersResponse) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Containers {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *WorkloadServiceListContainersResponse) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	for _, v := range p.Containers {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		{
			mBuf := make([]byte, 0)
			if appendTmp, err := v.Append(mBuf); err != nil {
				return nil, err
			} else {
				mBuf = appendTmp
			}
			field.SetLength(wire.Varint{Value: uint64(len(mBuf))})
			field.SetValueData(mBuf)
		}
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}

type WorkloadServiceServer interface {
	ApplyContainers(context.Context, *WorkloadServiceApplyContainersRequest) (*wkt.Empty, error)
	ListContainers(context.Context, *wkt.Empty) (*WorkloadServiceListContainersResponse, error)
}

type UnimplementedWorkloadServiceServer struct {
}

func (s *UnimplementedWorkloadServiceServer) ApplyContainers(context.Context, *WorkloadServiceApplyContainersRequest) (*wkt.Empty, error) {
	return nil, errors.New("method ksdk.rpc.WorkloadService.ApplyContainers not implemented")
}

func (s *UnimplementedWorkloadServiceServer) ListContainers(context.Context, *wkt.Empty) (*WorkloadServiceListContainersResponse, error) {
	return nil, errors.New("method ksdk.rpc.WorkloadService.ListContainers not implemented")
}

type WorkloadServiceClient interface {
	ApplyContainers(context.Context, *WorkloadServiceApplyContainersRequest) (*wkt.Empty, error)
	ListContainers(context.Context, *wkt.Empty) (*WorkloadServiceListContainersResponse, error)
}

type DefaultWorkloadServiceClient struct {
	stream *wire.StreamSource
}

func (c *DefaultWorkloadServiceClient) ApplyContainers(arg0 context.Context, arg1 *WorkloadServiceApplyContainersRequest) (*wkt.Empty, error) {
	return wire.NewCall[WorkloadServiceApplyContainersRequest, wkt.Empty](arg0, "ksdk.rpc.WorkloadService", "ApplyContainers", c.stream, arg1)
}

func (c *DefaultWorkloadServiceClient) ListContainers(arg0 context.Context, arg1 *wkt.Empty) (*WorkloadServiceListContainersResponse, error) {
	return wire.NewCall[wkt.Empty, WorkloadServiceListContainersResponse](arg0, "ksdk.rpc.WorkloadService", "ListContainers", c.stream, arg1)
}

func NewWorkloadServiceClient(stream *wire.StreamSource) WorkloadServiceClient {
	return &DefaultWorkloadServiceClient{stream: stream}
}

func RegisterWorkloadServiceServer(reg rpc.Registry, impl WorkloadServiceServer) {
	reg.RegisterMethod("ksdk.rpc.WorkloadService", "ApplyContainers",
		func(ctx context.Context, body []byte) ([]byte, error) {
			req := &WorkloadServiceApplyContainersRequest{}
			if err := req.Decode(body); err != nil {
				return nil, err
			}
			resp, err := impl.ApplyContainers(ctx, req)
			if err != nil {
				return nil, err
			}
			return resp.Append(nil)
		})
	reg.RegisterMethod("ksdk.rpc.WorkloadService", "ListContainers",
		func(ctx context.Context, body []byte) ([]byte, error) {
			req := &wkt.Empty{}
			if err := req.Decode(body); err != nil {
				return nil, err
			}
			resp, err := impl.ListContainers(ctx, req)
			if err != nil {
				return nil, err
			}
			return resp.Append(nil)
		})
}
