// Code generated by protoc-gen-ksdk. DO NOT EDIT.
package exec

import (
	bytes "bytes"
	fmt "fmt"
	wire "github.com/on-keyday/kscale/protobuf/wire"
	io "io"
	unsafe "unsafe"
)

type ExecCommand struct {
	Cmd     string   `json:"cmd,omitempty"`
	Args    []string `json:"args,omitempty"`
	Pty     bool     `json:"pty,omitempty"`
	DpType  string   `json:"dp_type,omitempty"`
	Address string   `json:"address,omitempty"`
}

func (p *ExecCommand) Read(data io.Reader) error {
	var field wire.Field
	for {
		err := field.Read(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Cmd unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Cmd = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Args unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Args = append(p.Args, tmp)
			}
		case 3:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Pty unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Pty = (*val).Value != 0
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field DpType unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.DpType = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Address unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Address = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *ExecCommand) ReadBuffer(data *bytes.Reader) error {
	var field wire.Field
	for {
		err := field.ReadBuffer(data)
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Cmd unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Cmd = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Args unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Args = append(p.Args, tmp)
			}
		case 3:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Pty unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Pty = (*val).Value != 0
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field DpType unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.DpType = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Address unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Address = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
	}
	return nil
}
func (p *ExecCommand) Decode(data []byte) error {
	var field wire.Field
	for len(data) > 0 {
		remain, err := field.Decode(data)
		if err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		switch field.Tag.Number() {
		case 1:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Cmd unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Cmd = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 2:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Args unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			{
				var tmp string
				tmp = unsafe.String(unsafe.SliceData((*val)), len((*val)))
				p.Args = append(p.Args, tmp)
			}
		case 3:
			val := field.ValueVi()
			if val == nil {
				return fmt.Errorf("field Pty unexpected wire type. expect Varint but got %s", field.Tag.Type())
			}
			p.Pty = (*val).Value != 0
		case 4:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field DpType unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.DpType = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		case 5:
			val := field.ValueData()
			if val == nil {
				return fmt.Errorf("field Address unexpected wire type. expect LengthDelimited but got %s", field.Tag.Type())
			}
			p.Address = unsafe.String(unsafe.SliceData((*val)), len((*val)))
		default:
			// skip unknown
		}
		data = remain
	}
	return nil
}

func (p *ExecCommand) Encode(w io.Writer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Cmd) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Cmd))})
		field.SetValueData([]byte(p.Cmd))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	for _, v := range p.Args {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(3)
	if p.Pty {
		field.Tag.SetType(wire.WireType_Varint)
		{
			bVal := uint64(0)
			if p.Pty {
				bVal = 1
			}
			field.SetValueVi(wire.Varint{Value: bVal})
		}
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(4)
	if len(p.DpType) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.DpType))})
		field.SetValueData([]byte(p.DpType))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(5)
	if len(p.Address) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Address))})
		field.SetValueData([]byte(p.Address))
		if err := field.Write(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *ExecCommand) EncodeBuffer(w *bytes.Buffer) error {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Cmd) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Cmd))})
		field.SetValueData([]byte(p.Cmd))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(2)
	for _, v := range p.Args {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(3)
	if p.Pty {
		field.Tag.SetType(wire.WireType_Varint)
		{
			bVal := uint64(0)
			if p.Pty {
				bVal = 1
			}
			field.SetValueVi(wire.Varint{Value: bVal})
		}
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(4)
	if len(p.DpType) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.DpType))})
		field.SetValueData([]byte(p.DpType))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	field.Tag.SetNumber(5)
	if len(p.Address) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Address))})
		field.SetValueData([]byte(p.Address))
		if err := field.WriteBuffer(w); err != nil {
			return err
		}
	}
	return nil
}
func (p *ExecCommand) Append(w []byte) ([]byte, error) {
	var field wire.Field
	field.Tag.SetNumber(1)
	if len(p.Cmd) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Cmd))})
		field.SetValueData([]byte(p.Cmd))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(2)
	for _, v := range p.Args {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(v))})
		field.SetValueData([]byte(v))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(3)
	if p.Pty {
		field.Tag.SetType(wire.WireType_Varint)
		{
			bVal := uint64(0)
			if p.Pty {
				bVal = 1
			}
			field.SetValueVi(wire.Varint{Value: bVal})
		}
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(4)
	if len(p.DpType) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.DpType))})
		field.SetValueData([]byte(p.DpType))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	field.Tag.SetNumber(5)
	if len(p.Address) > 0 {
		field.Tag.SetType(wire.WireType_LengthDelimited)
		field.SetLength(wire.Varint{Value: uint64(len(p.Address))})
		field.SetValueData([]byte(p.Address))
		if appendTmp, err := field.Append(w); err != nil {
			return nil, err
		} else {
			w = appendTmp
		}
	}
	return w, nil
}
