// Code generated by script/internal_value.py. DO NOT EDIT.

package consts

// The initial Maximum Transmission Unit (MTU) size for network packets.
const MagicNumberInitialMTU = 1200

// The default Maximum Transmission Unit (MTU) size for network packets.
const MagicNumberDefaultMTU = 1500

