// Code generated by ebm2go at https://github.com/on-keyday/brgen, DO NOT EDIT.
package hpack

import (
	"fmt"
)

/* config.go.package("hpack")*/
type FieldType int

const (
	FieldType_Index                    FieldType = 0
	FieldType_IndexLiteralInsert       FieldType = 1
	FieldType_IndexLiteralNeverIndexed FieldType = 2
	FieldType_IndexLiteralNoInsert     FieldType = 3
	FieldType_DynTableUpdate           FieldType = 4
	FieldType_Unknown                  FieldType = 5
)

func (e FieldType) String() string {
	switch e {
	case FieldType_Index:
		return "Index"
	case FieldType_IndexLiteralInsert:
		return "IndexLiteralInsert"
	case FieldType_IndexLiteralNeverIndexed:
		return "IndexLiteralNeverIndexed"
	case FieldType_IndexLiteralNoInsert:
		return "IndexLiteralNoInsert"
	case FieldType_DynTableUpdate:
		return "DynTableUpdate"
	case FieldType_Unknown:
		return "Unknown"
	default:
		return fmt.Sprintf("FieldType(%d)", e)
	}
}
func FieldPrefixLen(T FieldType) uint8 {
	tmp6 := uint8(0)
	if T == FieldType_Index {
		tmp6 = 7
	} else if T == FieldType_IndexLiteralInsert {
		tmp6 = 6
	} else if T == FieldType_IndexLiteralNeverIndexed {
		tmp6 = 4
	} else if T == FieldType_IndexLiteralNoInsert {
		tmp6 = 4
	} else if T == FieldType_DynTableUpdate {
		tmp6 = 5
	} else {
		tmp6 = 255
	}
	return tmp6
}
func MaskFieldType(T FieldType) uint8 {
	tmp10 := uint8(0)
	if T == FieldType_Index {
		tmp10 = 128
	} else if T == FieldType_IndexLiteralInsert {
		tmp10 = 192
	} else if T == FieldType_IndexLiteralNeverIndexed {
		tmp10 = 240
	} else if T == FieldType_IndexLiteralNoInsert {
		tmp10 = 240
	} else if T == FieldType_DynTableUpdate {
		tmp10 = 224
	} else {
		tmp10 = 15
	}
	return tmp10
}
func MatchFieldType(T FieldType) uint8 {
	tmp9 := uint8(0)
	if T == FieldType_Index {
		tmp9 = 128
	} else if T == FieldType_IndexLiteralInsert {
		tmp9 = 64
	} else if T == FieldType_IndexLiteralNeverIndexed {
		tmp9 = 16
	} else if T == FieldType_IndexLiteralNoInsert {
		tmp9 = 0
	} else if T == FieldType_DynTableUpdate {
		tmp9 = 32
	} else {
		tmp9 = 240
	}
	return tmp9
}
func IsFieldType(T uint8, M FieldType) bool {
	return ((MaskFieldType(M) & T) == MatchFieldType(M))
}
func GetFieldType(T uint8) FieldType {
	tmp8 := FieldType(0)
	if IsFieldType(T, FieldType_Index) {
		tmp8 = FieldType_Index
	} else if IsFieldType(T, FieldType_IndexLiteralInsert) {
		tmp8 = FieldType_IndexLiteralInsert
	} else if IsFieldType(T, FieldType_IndexLiteralNeverIndexed) {
		tmp8 = FieldType_IndexLiteralNeverIndexed
	} else if IsFieldType(T, FieldType_IndexLiteralNoInsert) {
		tmp8 = FieldType_IndexLiteralNoInsert
	} else if IsFieldType(T, FieldType_DynTableUpdate) {
		tmp8 = FieldType_DynTableUpdate
	} else {
		tmp8 = FieldType_Unknown
	}
	return tmp8
}
func SizeOfField(KeyLen uint64, ValueLen uint64) uint64 {
	return ((KeyLen + ValueLen) + 32)
}
