// Code generated by script/internal_value.py. DO NOT EDIT.

package netdpmetrics

import (
    "fmt"
    "strings"
    "sync/atomic"
    "sync"
)

type NetdpMetrics struct {
    InSteeredTotal uint64
    InNotLbSrcTotal uint64
    InNoPortTotal uint64
    InErrTotal uint64
    OutSnatTotal uint64
    OutErrTotal uint64
    SteeredPorts uint64
}

type NetdpMetricsWithLock struct {
    metricsLock sync.RWMutex
    metrics     NetdpMetrics
}

func (p *NetdpMetrics) AddInSteeredTotal(v uint64) {
    atomic.AddUint64(&p.InSteeredTotal, uint64(v))
}

func (p *NetdpMetrics) IncrementInSteeredTotal() {
    p.AddInSteeredTotal(1)
}

func (p *NetdpMetricsWithLock) AddInSteeredTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddInSteeredTotal(v)
}

func (p *NetdpMetricsWithLock) IncrementInSteeredTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementInSteeredTotal()
}

func (p *NetdpMetrics) AddInNotLbSrcTotal(v uint64) {
    atomic.AddUint64(&p.InNotLbSrcTotal, uint64(v))
}

func (p *NetdpMetrics) IncrementInNotLbSrcTotal() {
    p.AddInNotLbSrcTotal(1)
}

func (p *NetdpMetricsWithLock) AddInNotLbSrcTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddInNotLbSrcTotal(v)
}

func (p *NetdpMetricsWithLock) IncrementInNotLbSrcTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementInNotLbSrcTotal()
}

func (p *NetdpMetrics) AddInNoPortTotal(v uint64) {
    atomic.AddUint64(&p.InNoPortTotal, uint64(v))
}

func (p *NetdpMetrics) IncrementInNoPortTotal() {
    p.AddInNoPortTotal(1)
}

func (p *NetdpMetricsWithLock) AddInNoPortTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddInNoPortTotal(v)
}

func (p *NetdpMetricsWithLock) IncrementInNoPortTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementInNoPortTotal()
}

func (p *NetdpMetrics) AddInErrTotal(v uint64) {
    atomic.AddUint64(&p.InErrTotal, uint64(v))
}

func (p *NetdpMetrics) IncrementInErrTotal() {
    p.AddInErrTotal(1)
}

func (p *NetdpMetricsWithLock) AddInErrTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddInErrTotal(v)
}

func (p *NetdpMetricsWithLock) IncrementInErrTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementInErrTotal()
}

func (p *NetdpMetrics) AddOutSnatTotal(v uint64) {
    atomic.AddUint64(&p.OutSnatTotal, uint64(v))
}

func (p *NetdpMetrics) IncrementOutSnatTotal() {
    p.AddOutSnatTotal(1)
}

func (p *NetdpMetricsWithLock) AddOutSnatTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddOutSnatTotal(v)
}

func (p *NetdpMetricsWithLock) IncrementOutSnatTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementOutSnatTotal()
}

func (p *NetdpMetrics) AddOutErrTotal(v uint64) {
    atomic.AddUint64(&p.OutErrTotal, uint64(v))
}

func (p *NetdpMetrics) IncrementOutErrTotal() {
    p.AddOutErrTotal(1)
}

func (p *NetdpMetricsWithLock) AddOutErrTotal(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.AddOutErrTotal(v)
}

func (p *NetdpMetricsWithLock) IncrementOutErrTotal() {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.IncrementOutErrTotal()
}

func (p *NetdpMetrics) SetSteeredPorts(v uint64) {
    atomic.StoreUint64(&p.SteeredPorts, uint64(v))
}

func (p *NetdpMetricsWithLock) SetSteeredPorts(v uint64) {
    p.metricsLock.RLock()
    defer p.metricsLock.RUnlock()
    p.metrics.SetSteeredPorts(v)
}

type NetdpMetricsMetricsInterface interface {
    AddInSteeredTotal(v uint64)
    IncrementInSteeredTotal()
    AddInNotLbSrcTotal(v uint64)
    IncrementInNotLbSrcTotal()
    AddInNoPortTotal(v uint64)
    IncrementInNoPortTotal()
    AddInErrTotal(v uint64)
    IncrementInErrTotal()
    AddOutSnatTotal(v uint64)
    IncrementOutSnatTotal()
    AddOutErrTotal(v uint64)
    IncrementOutErrTotal()
    SetSteeredPorts(v uint64)
}

func (p *NetdpMetrics) String() string {
    var buf strings.Builder
    buf.WriteString("NetdpMetrics{")
 if p.InSteeredTotal != 0 {
    if buf.Len() > len("NetdpMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("InSteeredTotal: %v", p.InSteeredTotal))
 }
 if p.InNotLbSrcTotal != 0 {
    if buf.Len() > len("NetdpMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("InNotLbSrcTotal: %v", p.InNotLbSrcTotal))
 }
 if p.InNoPortTotal != 0 {
    if buf.Len() > len("NetdpMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("InNoPortTotal: %v", p.InNoPortTotal))
 }
 if p.InErrTotal != 0 {
    if buf.Len() > len("NetdpMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("InErrTotal: %v", p.InErrTotal))
 }
 if p.OutSnatTotal != 0 {
    if buf.Len() > len("NetdpMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("OutSnatTotal: %v", p.OutSnatTotal))
 }
 if p.OutErrTotal != 0 {
    if buf.Len() > len("NetdpMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("OutErrTotal: %v", p.OutErrTotal))
 }
 if p.SteeredPorts != 0 {
    if buf.Len() > len("NetdpMetrics{") { buf.WriteString(", ") }
    buf.WriteString(fmt.Sprintf("SteeredPorts: %v", p.SteeredPorts))
 }
    buf.WriteString("}")
    return buf.String()
}

func (p *NetdpMetricsWithLock) GetMetrics() NetdpMetrics {
    p.metricsLock.Lock()
    defer p.metricsLock.Unlock()
    return p.metrics
}

func (p *NetdpMetricsWithLock) WithLock(cb func(m *NetdpMetrics)) {
    p.metricsLock.Lock()
    defer p.metricsLock.Unlock()
    cb(&p.metrics)
}

